### ISSUE TITLE
OData v4 Client code Generator v2.4.0 - Running transformation: System.InvalidCastException

### ISSUE THREAD

**Issue by v-lealli** [OData/odata.net#1019]
Hi, I'm using OData v4 Client code Generator v2.4.0, and I'm getting an error when trying to generate an OData proxy file using an EDMX file, which I already checked is well formed, and the only thing particularly different from other files I've worked with seems to be its size, which is 13Mb.

I just set the path to my local file in the TT template, hit save, and get the error below..

For various reasons I can't provide the file right now.

**The error and stack trace is the following**
```
Error                        Running transformation: System.InvalidCastException: Unable to cast object of type 'Microsoft.OData.Edm.Library.AmbiguousTypeBinding' to type 'Microsoft.OData.Edm.IEdmCollectionType'.
   at Microsoft.VisualStudio.TextTemplating38D594C4A7740AF8C58830F3DCD33DA08B69ADAE9BC7D3015F5BCA884F5569B87AB8AD40A2C17F0B13B4B19E4A8CDDB5BBAD540A98BD837FB2557195836C0C3A.GeneratedTextTransformation.Utils.GetClrTypeName(IEdmTypeReference edmTypeReference, Boolean useDataServiceCollection, ODataClientTemplate clientTemplate, CodeGenerationContext context, Boolean addNullableTemplate, Boolean needGlobalPrefix, Boolean isOperationParameter) in :line 2799
   at Microsoft.VisualStudio.TextTemplating38D594C4A7740AF8C58830F3DCD33DA08B69ADAE9BC7D3015F5BCA884F5569B87AB8AD40A2C17F0B13B4B19E4A8CDDB5BBAD540A98BD837FB2557195836C0C3A.GeneratedTextTransformation.ODataClientTemplate.<>c__DisplayClass224_0.<WritePropertiesForStructuredType>b__0(IEdmProperty property) in :line 2237
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TextTemplating38D594C4A7740AF8C58830F3DCD33DA08B69ADAE9BC7D3015F5BCA884F5569B87AB8AD40A2C17F0B13B4B19E4A8CDDB5BBAD540A98BD837FB2557195836C0C3A.GeneratedTextTransformation.ODataClientTemplate.WritePropertiesForStructuredType(IEnumerable`1 properties) in :line 2232
   at Microsoft.VisualStudio.TextTemplating38D594C4A7740AF8C58830F3DCD33DA08B69ADAE9BC7D3015F5BCA884F5569B87AB8AD40A2C17F0B13B4B19E4A8CDDB5BBAD540A98BD837FB2557195836C0C3A.GeneratedTextTransformation.ODataClientTemplate.WriteEntityType(IEdmEntityType entityType, Dictionary`2 boundOperationsMap) in :line 1772
   at Microsoft.VisualStudio.TextTemplating38D594C4A7740AF8C58830F3DCD33DA08B69ADAE9BC7D3015F5BCA884F5569B87AB8AD40A2C17F0B13B4B19E4A8CDDB5BBAD540A98BD837FB2557195836C0C3A.GeneratedTextTransformation.ODataClientTemplate.WriteNamespace(String fullNamespace) in :line 1265
   at Microsoft.VisualStudio.TextTemplating38D594C4A7740AF8C58830F3DCD33DA08B69ADAE9BC7D3015F5BCA884F5569B87AB8AD40A2C17F0B13B4B19E4A8CDDB5BBAD540A98BD837FB2557195836C0C3A.GeneratedTextTransformation.ODataClientTemplate.WriteNamespaces() in :line 1212
   at Microsoft.VisualStudio.TextTemplating38D594C4A7740AF8C58830F3DCD33DA08B69ADAE9BC7D3015F5BCA884F5569B87AB8AD40A2C17F0B13B4B19E4A8CDDB5BBAD540A98BD837FB2557195836C0C3A.GeneratedTextTransformation.ODataClientTemplate.TransformText() in :line 1204
   at Microsoft.VisualStudio.TextTemplating38D594C4A7740AF8C58830F3DCD33DA08B69ADAE9BC7D3015F5BCA884F5569B87AB8AD40A2C17F0B13B4B19E4A8CDDB5BBAD540A98BD837FB2557195836C0C3A.GeneratedTextTransformation.TransformText() in :line 97                                 2799        
```

### Assemblies affected

OData .Net lib 6.19.0.11114

I would appreciate any help regarding this error. 
Thanks.

**Comment by fw1978** [comment]
I am having the same issue.
Working against Dynamics 365 for operations.
Version 7.2 of Dynamics worked but after upgrading to 7.3 I started receiving this error.
The metadata file was 12. something MB large in 7.2 but now in 7.3 it is over 13 MB.

**Comment by sbones88** [comment]
I am having the same issue as well working with Dynamics 365 version 7.3.  I haven't tried this with previous versions.  
Did you find a solution for this?

**Comment by dcs-kartik** [comment]
Did anyone got the solution for this error?

**Comment by VPoonguzhali** [comment]
Is there any luck on this issue? I am getting the same error. Please tell me if anyone fixed this issue.

**Comment by gangstasoftware** [comment]
I also get the same error against D365FOEE 7.3 PU12.

**Comment by VPoonguzhali** [comment]
v-lealli solution worked for me. Try it once.

**Comment by ahmadz01** [comment]
Hi @VPoonguzhali can you please point out which solution worked for you? I could not find in this thread a solution by v-lealli. Thank you!

**Comment by VPoonguzhali** [comment]
Hi @ahmadz01 , I hope the thread has been deleted. Find the below steps I have done:

1. In the ODataClient.ttinclude file, Go to the line no: **2681**.
2. You can find an else part
3. Replace the else part with the below code:
                    **else
                    {
					clrTypeName = "caughtExceptionName";
					try
					{
					
                        IEdmCollectionType edmCollectionType = (IEdmCollectionType)edmType;
                        IEdmTypeReference elementTypeReference = edmCollectionType.ElementType;
                        IEdmPrimitiveType primitiveElementType = elementTypeReference.Definition as IEdmPrimitiveType;
                        if (primitiveElementType != null)
                        {
                            clrTypeName = Utils.GetClrTypeName(primitiveElementType, clientTemplate);
                        }
                        else
                        {
                            IEdmSchemaElement schemaElement = (IEdmSchemaElement)elementTypeReference.Definition;
                            clrTypeName = context.GetPrefixedFullName(schemaElement,
                                context.EnableNamingAlias ? clientTemplate.GetFixedName(Customization.CustomizeNaming(schemaElement.Name)) : clientTemplate.GetFixedName(schemaElement.Name), clientTemplate);
                        }    
                
                        string collectionTypeName = isOperationParameter
                                                        ? clientTemplate.ICollectionOfTStructureTemplate
                                                        : (useDataServiceCollection
                                                            ? (elementTypeReference.TypeKind() == EdmTypeKind.Entity
                                                                ? clientTemplate.DataServiceCollectionStructureTemplate
                                                                : clientTemplate.ObservableCollectionStructureTemplate)
                                                            : clientTemplate.ObjectModelCollectionStructureTemplate);

                        clrTypeName = string.Format(collectionTypeName, clrTypeName);
                    }
					catch(Exception ex)
					{
					}
					}**

4. Now generate the OData file, The OData will be generated but you will be facing around 6 errors
5. Comment the methods where you are facing the error till the solution build successfully.
6. Once the solution build successfully you can use the OData class file.

Try it once. This solution worked for me.

**Comment by dcs-kartik** [comment]
Hello... 
The actual problem is in metadata. There is an Enum with name "ItemType" and also the Data Entity with same name "ItemType". Due to which the proxy file is not generated due to same name and giving the error.

The solution will be changing the name of Data Entity "ItemType" to "ItemTypes"
<EntityType Name="ItemTypes">
 and also do not forget to change the name in Entity Set in container.
<EntitySet Name="ItemTypes" EntityType="Microsoft.Dynamics.DataEntities.ItemTypes" />

We have tested the same and it works fine.

**Comment by tek9iner** [comment]
The solution that worked for me was suggested by @dcs-kartik .  I was finally able to regenerate my files by locally downloading the metadata file from D365 and then changing the name of the EntityType.   Thanks @dcs-kartik .

**Comment by gangstasoftware** [comment]
The solution provided by @dcs-kartik worked for me as well. Thanks.

**Comment by VPoonguzhali** [comment]
@dcs-kartik , Thanks for the solution. But when I tried to change the Data Entity name to "ItemTypes" I am getting "Access denied" issue. i even tried to replace the XML file in AOS directory but still I am getting the error.

The Entity Name is "EMItemType" which comes under "Regulatory services" model. Please provide me a solution to update the Public entity name.

**Comment by skyd365** [comment]
@dcs-kartik , I have tried but still not clear where i need to change the EntityName please provide more detail and exact path of file where i need ti change.Please help

**Comment by madhus-ch** [comment]
@dcs-kartik, after changing from ItemType to ItemTypes in two places as mentioned also getting the same issue. Is there any other place that I need to change?

**Comment by dcs-kartik** [comment]
@madhus-ch, @skyd365  You need to change the name of EntityType Name="ItemTypes" and EntitySet Name="ItemTypes" EntityType="Microsoft.Dynamics.DataEntities.ItemTypes". There is not other change required. Might be some other issues...

**Comment by maveloso** [comment]
@dcs-kartik where exactly are you changing these? can you provide detailed steps?

**Comment by LOGIN2BALU** [comment]
http://d365issuesandresolution.blogspot.com/2018/06/odata-v4-client-code-generator.html

**Comment by JohnLBevan** [comment]
@dcs-kartik 's solution worked perfectly for me too; thanks-you.  

To help avoid any ambiguity, search the metadata file for the FROM value and replace with the TO value; there should be one occurrence of each of the lines below:

From: `<EnumType Name="ItemType">`
To: `<EnumType Name="ItemTypes">`

From: `<EntitySet Name="ItemTypes" EntityType="Microsoft.Dynamics.DataEntities.ItemType" />`
To: `<EntitySet Name="ItemTypes" EntityType="Microsoft.Dynamics.DataEntities.ItemTypes" />`

**Comment by madansr7** [comment]
the large file issue has been addressed but we need to follow up with D365 to make sure the metadata issue has been addressed as well.
