### ISSUE TITLE
System.OutOfMemoryException and System.IndexOutOfRangeException: Probable I/O race condition detected while copying memory when loading large JSON-files 

### ISSUE THREAD

**Issue by erikves** [OData/odata.net#1024]
We recently hit an issue when using the OData .NET library during load with files >10GB size. Our application stops loading the metadata after a while (probably when it exceeds the 10GB mark) since files around 9-9.9GB loads perfectly fine.

The same initial JSON works after splitting it to smaller chunks.

### Assemblies affected

OData .Net lib 5.8.2 and OData .Net lib 5.8.3

### Reproduce steps

Load a large JSON through the OData .NET lib.

### Expected result

The metadata would read perfectly fine from the JSON.

### Actual result

Application stops loading the JSON and the following error message is visible in the log file:

2017-12-13 22:17:17.802 ERROR [1] UserControlImportOData - LoadMetaData
System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Microsoft.Data.OData.Json.JsonReader.ReadInput()
   at Microsoft.Data.OData.Json.JsonReader.ParseStringPrimitiveValue(Boolean& hasLeadingBackslash)
   at Microsoft.Data.OData.Json.JsonReader.ParseValue(String& rawValue)
   at Microsoft.Data.OData.Json.JsonReader.Read()
   at Microsoft.Data.OData.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.Data.OData.Json.BufferingJsonReader.ReadNextAndCheckForInStreamError()
   at Microsoft.Data.OData.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ParseProperty(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Func`2 readPropertyAnnotationValue, String& parsedPropertyName)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadEntryContent(IODataJsonLightReaderEntryState entryState)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightReader.ReadAtNavigationLinkEndImplementationSynchronously()
   at Microsoft.Data.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.Data.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at .OData.AbstractODataReader`1.ReadNextItem()
   at .OData.AbstractODataReader`1.<ReadMessage>d__16.MoveNext()
   at .OData.AbstractODataReader`1.<ReadFromFile>d__14.MoveNext()
   at .OData.ProjectVic.ProjectVicImporter.ReadMetadata(String filePath)
   at GUI.UserControlImportOData._Closure$__194-1._Lambda$__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at GUI.UserControlImportOData.ReadMetadata(String filePath)
   at GUI.UserControlImportOData.LoadMetaData()
---> (Inner Exception #0) System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Microsoft.Data.OData.Json.JsonReader.ReadInput()
   at Microsoft.Data.OData.Json.JsonReader.ParseStringPrimitiveValue(Boolean& hasLeadingBackslash)
   at Microsoft.Data.OData.Json.JsonReader.ParseValue(String& rawValue)
   at Microsoft.Data.OData.Json.JsonReader.Read()
   at Microsoft.Data.OData.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.Data.OData.Json.BufferingJsonReader.ReadNextAndCheckForInStreamError()
   at Microsoft.Data.OData.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ParseProperty(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Func`2 readPropertyAnnotationValue, String& parsedPropertyName)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadEntryContent(IODataJsonLightReaderEntryState entryState)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightReader.ReadAtNavigationLinkEndImplementationSynchronously()
   at Microsoft.Data.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.Data.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at .OData.AbstractODataReader`1.ReadNextItem()
   at .OData.AbstractODataReader`1.<ReadMessage>d__16.MoveNext()
   at .OData.AbstractODataReader`1.<ReadFromFile>d__14.MoveNext()
   at .OData.ProjectVic.ProjectVicImporter.ReadMetadata(String filePath)
   at GUI.UserControlImportOData._Closure$__194-1._Lambda$__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

With <gcAllowVeryLargeObjects enabled="true" /> in the application config, the following error message is thrown instead:

2017-12-14 09:11:04.268 ERROR [1] UserControlImportOData - LoadMetaData
System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
   at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at Microsoft.Data.OData.Json.JsonReader.ReadInput()
   at Microsoft.Data.OData.Json.JsonReader.ParseStringPrimitiveValue(Boolean& hasLeadingBackslash)
   at Microsoft.Data.OData.Json.JsonReader.ParseValue(String& rawValue)
   at Microsoft.Data.OData.Json.JsonReader.Read()
   at Microsoft.Data.OData.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.Data.OData.Json.BufferingJsonReader.ReadNextAndCheckForInStreamError()
   at Microsoft.Data.OData.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ParseProperty(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Func`2 readPropertyAnnotationValue, String& parsedPropertyName)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadEntryContent(IODataJsonLightReaderEntryState entryState)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightReader.ReadAtNavigationLinkEndImplementationSynchronously()
   at Microsoft.Data.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.Data.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at .OData.AbstractODataReader`1.ReadNextItem()
   at .OData.AbstractODataReader`1.<ReadMessage>d__16.MoveNext()
   at .OData.AbstractODataReader`1.<ReadFromFile>d__14.MoveNext()
   at .OData.ProjectVic.ProjectVicImporter.ReadMetadata(String filePath)
   at GUI.UserControlImportOData._Closure$__194-1._Lambda$__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at GUI.UserControlImportOData.ReadMetadata(String filePath)
   at GUI.UserControlImportOData.LoadMetaData()
---> (Inner Exception #0) System.IndexOutOfRangeException: Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
   at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at Microsoft.Data.OData.Json.JsonReader.ReadInput()
   at Microsoft.Data.OData.Json.JsonReader.ParseStringPrimitiveValue(Boolean& hasLeadingBackslash)
   at Microsoft.Data.OData.Json.JsonReader.ParseValue(String& rawValue)
   at Microsoft.Data.OData.Json.JsonReader.Read()
   at Microsoft.Data.OData.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.Data.OData.Json.BufferingJsonReader.ReadNextAndCheckForInStreamError()
   at Microsoft.Data.OData.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ParseProperty(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Func`2 readPropertyAnnotationValue, String& parsedPropertyName)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadEntryContent(IODataJsonLightReaderEntryState entryState)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightReader.ReadAtNavigationLinkEndImplementationSynchronously()
   at Microsoft.Data.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.Data.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at .OData.AbstractODataReader`1.ReadNextItem()
   at .OData.AbstractODataReader`1.<ReadMessage>d__16.MoveNext()
   at .OData.AbstractODataReader`1.<ReadFromFile>d__14.MoveNext()
   at .OData.ProjectVic.ProjectVicImporter.ReadMetadata(String filePath)
   at GUI.UserControlImportOData._Closure$__194-1._Lambda$__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

### Additional detail

Please refer to the email conversation that we have raised offline.

**Comment by mikepizzo** [comment]
I'm a bit confused from the title which talks about reading a large CSDL JSON file.  Neither the 5.8.3 version, nor the latest version, support a JSON-formatted CSDL.  From the stack trace it does appear that you are reading JSON, though; I assume this is a JSON payload (i.e., the data), and not the CSDL (metadata)?

Are you reading the payload with streaming=true (i.e., by setting the content-type header to application/json;odata.streaming=true)?

**Comment by andreas-eriksson** [comment]
Hi Mike,

the error occurs when reading a json formatted OData file. I have included a part of the code we use to read the file beow.
`public IEnumerable<T> ReadFromStream(Stream inputStream, bool readFormatFromStream = false)
        {
            string format = "application/json;streaming=true";
            IEdmModel model = dataModel.GetMetadata();

            message = new FileResponseMessage(stream);
            message.SetHeader("Content-Type", format);
            message.SetHeader("DataServiceVersion", ODataVersion.V3.ToHeaderValue());
            message.SetHeader("MaxDataServiceVersion", ODataVersion.V3.ToHeaderValue());

            var settings = new ODataMessageReaderSettings();

            settings.EnableWcfDataServicesServerBehavior(false);

            settings.MessageQuotas.MaxReceivedMessageSize = maxSizeOfFiles;
            settings.UndeclaredPropertyBehaviorKinds = ODataUndeclaredPropertyBehaviorKinds.IgnoreUndeclaredValueProperty;
            messageReader = new ODataMessageReader(message, settings, model);

            return ReadMessage();
        }

        private IEnumerable<T> ReadMessage()
        {
            reader = messageReader.CreateODataFeedReader();

            T finishedItem;
            while (ReadNextItem())
            {
                switch (reader.State)
                {
                    case ODataReaderState.EntryStart:
                        StartEntity((ODataEntry)reader.Item);
                        break;
                    case ODataReaderState.EntryEnd:
                        if (HandleFinishedEntity((ODataEntry)reader.Item, out finishedItem))
                        {
                            yield return finishedItem;
                        }
                        break;
                    default:
                        continue;
                }
            }
        }`

The OData json file looks like this but with millions of media entries.

`{
  "odata.metadata":"http://github.com/ICMEC/ProjectVic/DataModels/1.3.xml#Media","value":[
    {
      "odata.id":"Media(\"0\")","AlternativeHashes@odata.navigationLinkUrl":"/Media(076E3CAED758A1C18C91A0E9CAE3368F)/AlternativeHashes","AlternativeHashes":[
        {
          "MD5":"076E3CAED758A1C18C91A0E9CAE3368F","HashName":"PhotoDNA","HashValue":"xwsskTEPEBkaVW4RZDFsOxgDIgMJIAMzoayRU6lJCV5MiiGqr4Avp1AeBTQ9i0tcTZt0GpOecTCjiaUzkoqUIGlNRjZhXVpUY2E1PVQlNzYaKi4KQFtGN0YhPkMgezkldywuD0w/RzMfFwsiKEs4SlFWOFhHlTU0QQISAwcQGQQ8azg7XYJtQHoqYScUECoB"
        },{
          "MD5":"076E3CAED758A1C18C91A0E9CAE3368F","HashName":"ACME","HashValue":"ACMEF5F8AD26819A471318D24631FA5055036712A87E"
        }
      ],"Exifs@odata.navigationLinkUrl":"/Media(076E3CAED758A1C18C91A0E9CAE3368F)/Exifs","Exifs":[
        {
          "MD5":"076E3CAED758A1C18C91A0E9CAE3368F","PropertyName":"DateTimeDigitized","PropertyValue":"2000:05:17 16:22:50"
        },{
          "MD5":"076E3CAED758A1C18C91A0E9CAE3368F","PropertyName":"Manufacturer","PropertyValue":"CASIO"
        }
      ],"MediaFiles@odata.navigationLinkUrl":"/Media(076E3CAED758A1C18C91A0E9CAE3368F)/MediaFiles","MediaFiles":[
        {
          "MD5":"076E3CAED758A1C18C91A0E9CAE3368F","FileName":"Chrysant|hemum.jpg","FilePath":"C:\\Us|ers\\John\\OneDrive\\Hub\\Sample Pictures","Created":"2010-01-01T00:00:00","Written":"2012-01-01T00:00:00","Accessed":"2011-01-01T00:00:00","Unallocated":true,"SourceID":"1","PhysicalLocation":"123456789","Deleted":true,"ParentMD5":"A123456789","ParentFileName":"Parent","ParentFilePath":"c:\\temp","ParentPhysicalLocation":"987654321"
        }
      ],"Repositories@odata.navigationLinkUrl":"/Media(076E3CAED758A1C18C91A0E9CAE3368F)/Repositories","Repositories":[
        {
          "MD5":"076E3CAED758A1C18C91A0E9CAE3368F","RepositoryName":"ABC"
        }
      ],"Segments@odata.navigationLinkUrl":"/Media(076E3CAED758A1C18C91A0E9CAE3368F)/Segments","Segments":[
        {
          "MD5":"076E3CAED758A1C18C91A0E9CAE3368F","SegmentIndex":1,"Start":"14:00:00","End":"14:01:02","Category":1
        },{
          "MD5":"076E3CAED758A1C18C91A0E9CAE3368F","SegmentIndex":2,"Start":"14:01:02","End":"14:02:21","Category":2
        }
      ],"MediaID":0,"Category":1,"MD5":"076E3CAED758A1C18C91A0E9CAE3368F","Comments":"These are the comments for this image","VictimIdentified":true,"IsDistributed":true,"Series":"TEST","SHA1":"F5F8AD26819A471318D24631FA5055036712A87E","Tags":"#ABCD","DateUpdated":"2016-05-18T13:13:13.714529-07:00","MediaSize":"879394","RelativeFilePath":"Sample Pictures\\Chrysanthemum.jpg","OffenderIdentified":true,"IsPrecategorized":true,"PrecategorizationSource":"CAID","IsSuspected":true,"MimeType":"application\\jpeg"
    }
  ]
}`

**Comment by erikves** [comment]
@mikepizzo did you had the opportunity to look at @andreas-eriksson post above? I noticed that @xuzhg added the label P4 shortly after we posted it and it does not sound that it is going to be prioritized. Are we doing something wrong in the source code that causes the race conditions or is this expected when loading files larger than 10GB?

**Comment by mikepizzo** [comment]
The P4 priority was largely because this appears to be an issue with an older version of the library which is in maintenance mode.

At least in ODL 7.4, ReadInput() attempts to re-use the existing buffer, shifting unread characters to try and free up room, and doubling the size of the buffer once the buffer gets full of unread characters.  However, the buffer *should* only need to be large enough to contain the characters for a single string value; it *shouldn't* matter how large the overall file is.

I'll have to look into the possible race condition; there should only be one thread accessing the stream

**Comment by mikepizzo** [comment]
Thanks for the repo; running through the large data file uncovered one bug in our code, and another in our logic, for growing the buffer.  The buffer should never grow for your scenario, but if the start character is within 64 characters of the end we will double the size of the buffer and copy the entire old buffer to the new, rather than just the characters read so far for the current string.

The fix for this will significantly improve the performance and memory usage for your and other scenarios, as well as avoid the out of memory/index out of range exceptions.

**Comment by xuzhg** [comment]
@erikves Would you please take a try for the nightly build? 

Feed URL : https://www.myget.org/F/odlnightly/api/v3/index.json

The version is : 7.6.0-Nightly201901300241

**Comment by erikves** [comment]
@xuzhg thanks for your fix. We haven’t moved to ODL 7.x due to that it isn’t backwards compatible with OData v1-v3 and we are several vendors using the old data model in Project VIC. By the looks of it, I am guessing that this fix only applies on ODL 7.6/OData v4?

We currently don’t have a way testing it unless the fix is applied in ODL 5.x. I know that ODL 5.x is not maintained anymore, but is that something that can be fixed in the same way? I know we are asking a lot of a library that is not maintained anymore, but we are a number of vendors still stuck with the old model until we have decided to adjust our currently data model in Project VIC, which is still in discussion...

Thanks again.

**Comment by johnlundberg** [comment]
@xuzhg the nightly build fixes the issue for us, ( I am a colleague of @erikves )
I assume this means that we will have to upgrade to OData v4? 
We are currently using OData v3 which is not supported by ODL 7.x.

**Comment by KanishManuja-MS** [comment]
This is fixed in v4, tagging this issue for v3 only.

**Comment by xuzhg** [comment]
No v3 requirements since the fix. Close it and please file new issue if you have further concerns.
