### ISSUE TITLE
OData client not generated metadata

### ISSUE THREAD

**Issue by abhijitChodankar** [OData/odata.net#1088]
Odata metadata is not getting generated using the ODataClient.tt >> **Run custom tool**

### Reproduce steps
1. Create OData console application (https://github.com/Microsoft/Dynamics-AX-Integration)
2. Go to Utilities > ODataUtility> ODataClient.tt
3. Specify URL in the MetadataDocumentUri e.g. https://DEVBOXdevaos.cloudax.dynamics.com/data/$metadata
4. Save

### Expected result

Metadata should generate.

### Actual result

Error Message:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.InvalidCastException: Unable to cast object of type 'Microsoft.OData.Edm.Library.AmbiguousTypeBinding' to type 'Microsoft.OData.Edm.IEdmCollectionType'.
   at Microsoft.VisualStudio.TextTemplating2B5E7DF371B3381CC82650C57D972C5BC96A0274D09C0F84A1145526F3539EE761AE7EF02EE20A05CAF4AEDD69CA4B16C403CE8BFDE068898055BCA9958B93D9.GeneratedTextTransformation.Utils.GetClrTypeName(IEdmTypeReference edmTypeReference, Boolean useDataServiceCollection, ODataClientTemplate clientTemplate, CodeGenerationContext context, Boolean addNullableTemplate, Boolean needGlobalPrefix, Boolean isOperationParameter) in :line 2790
   at Microsoft.VisualStudio.TextTemplating2B5E7DF371B3381CC82650C57D972C5BC96A0274D09C0F84A1145526F3539EE761AE7EF02EE20A05CAF4AEDD69CA4B16C403CE8BFDE068898055BCA9958B93D9.GeneratedTextTransformation.ODataClientTemplate.<>c__DisplayClass224_0.<WritePropertiesForStructuredType>b__0(IEdmProperty property) in :line 2228
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TextTemplating2B5E7DF371B3381CC82650C57D972C5BC96A0274D09C0F84A1145526F3539EE761AE7EF02EE20A05CAF4AEDD69CA4B16C403CE8BFDE068898055BCA9958B93D9.GeneratedTextTransformation.ODataClientTemplate.WritePropertiesForStructuredType(IEnumerable`1 properties) in :line 2223
   at Microsoft.VisualStudio.TextTemplating2B5E7DF371B3381CC82650C57D972C5BC96A0274D09C0F84A1145526F3539EE761AE7EF02EE20A05CAF4AEDD69CA4B16C403CE8BFDE068898055BCA9958B93D9.GeneratedTextTransformation.ODataClientTemplate.WriteEntityType(IEdmEntityType entityType, Dictionary`2 boundOperationsMap) in :line 1763
   at Microsoft.VisualStudio.TextTemplating2B5E7DF371B3381CC82650C57D972C5BC96A0274D09C0F84A1145526F3539EE761AE7EF02EE20A05CAF4AEDD69CA4B16C403CE8BFDE068898055BCA9958B93D9.GeneratedTextTransformation.ODataClientTemplate.WriteNamespace(String fullNamespace) in :line 1256
   at Microsoft.VisualStudio.TextTemplating2B5E7DF371B3381CC82650C57D972C5BC96A0274D09C0F84A1145526F3539EE761AE7EF02EE20A05CAF4AEDD69CA4B16C403CE8BFDE068898055BCA9958B93D9.GeneratedTextTransformation.ODataClientTemplate.WriteNamespaces() in :line 1203
   at Microsoft.VisualStudio.TextTemplating2B5E7DF371B3381CC82650C57D972C5BC96A0274D09C0F84A1145526F3539EE761AE7EF02EE20A05CAF4AEDD69CA4B16C403CE8BFDE068898055BCA9958B93D9.GeneratedTextTransformation.ODataClientTemplate.TransformText() in :line 1195
   at Microsoft.VisualStudio.TextTemplating2B5E7DF371B3381CC82650C57D972C5BC96A0274D09C0F84A1145526F3539EE761AE7EF02EE20A05CAF4AEDD69CA4B16C403CE8BFDE068898055BCA9958B93D9.GeneratedTextTransformation.TransformText() in :line 96			2790

**Comment by thc72** [comment]
+1, I'm in the same boat.

**Comment by gathogojr** [comment]
Issue no longer reproducible due to code evolution (Utilities directory no longer exists) and dead link to service metadata (https://devboxdevaos.cloudax.dynamics.com/data/$metadata)
