### ISSUE TITLE
ODatalib 7.4; url convention $count is failing in particular case

### ISSUE THREAD

**Issue by dgq111** [OData/odata.net#1129]
Query:
http://domain.com/xxx/xxx/EnitySet(123)/ChildEntity(567)/NavigationPropertyChildEntityCollection/$count
or
http://domain.com/xxx/xxx/EnitySet(123)/ChildEntity(567)/NavigationPropertyChildEntityCollection?$count

This was working in our ODatalib 6.14 solution.

*Exception type:* InvalidOperationException
*Message:* The property 'PropertyUnits' cannot be used for $count.
*Source:* System.Web.OData
*Stack Trace:*
  at System.Web.OData.Query.Validators.CountQueryValidator.Validate(CountQueryOption countQueryOption, ODataValidationSettings validationSettings)
   at System.Web.OData.Query.CountQueryOption.Validate(ODataValidationSettings validationSettings)
   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)
   at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)

**Comment by mikepizzo** [comment]
Hi @dgq111;

It looks like this is failing in System.Web.OData; do you have a repo for ODatalib, or is this only happening in System.Web.OData?  Which specific version of System.Web.OData are you using?

Also note that the error message references a property "PropertyUnits" which is not in your URL (I assume a copy/paste/fixup error).

Can you provide a simple repo, such as the below?

~~~c#
            EdmModel model = new EdmModel();
            var entityType = model.AddEntityType("ns", "entityType");
            entityType.AddKeys(entityType.AddStructuralProperty("id", EdmPrimitiveTypeKind.Int32));
            var childEntityType = model.AddEntityType("ns", "childEntityType");
            childEntityType.AddKeys(childEntityType.AddStructuralProperty("id", EdmPrimitiveTypeKind.Int32));
            childEntityType.AddStructuralProperty("ChildEntityProperty", EdmPrimitiveTypeKind.String);
            var grandChildEntityType = model.AddEntityType("ns", "grandChildEntityType");
            grandChildEntityType.AddKeys(grandChildEntityType.AddStructuralProperty("id", EdmPrimitiveTypeKind.Int32));
            entityType.AddUnidirectionalNavigation(new EdmNavigationPropertyInfo()
            {
                Name = "ChildEntity",
                Target = childEntityType,
                TargetMultiplicity = EdmMultiplicity.Many
            });
            childEntityType.AddUnidirectionalNavigation(new EdmNavigationPropertyInfo()
            {
                Name = "NavigationPropertyChildEntityCollection",
                Target = grandChildEntityType,
                TargetMultiplicity = EdmMultiplicity.Many
            });
            var container = model.AddEntityContainer("ns", "container");
            container.AddEntitySet("EntitySet", entityType);

            relativeUri = @"EntitySet(123)/ChildEntity(567)/NavigationPropertyChildEntityCollection?$count=true";
            parser = new ODataUriParser(model, new Uri(relativeUri, UriKind.Relative));
            var count = parser.ParseCount();
            Debug.Assert(count.Value);

**Comment by mikepizzo** [comment]
Make sure that you are setting EnableCount to true in the DefaultQuerySettings passed to your FilterQueryValidator:

~~~c#
 var filterQueryValidator = new FilterQueryValidator(
         new DefaultQuerySettings() { 
             EnableCount = true
          } );
~~~

I believe that Microsoft.AspNet.OData 5.x defaulted to true for the various Enable flags, where-as in 6.x they need to be explicitly set to enable.
