### ISSUE TITLE
OData Code Generator does not install on VS2015.

### ISSUE THREAD

**Issue by AlanWong-MS** [OData/odata.net#1148]
### Assemblies affected
ODataT4ItemTemplate.7.4.4.vsix

### Reproduce steps
Attempt to install the extension on VS2015.

### Expected result
Extension installs on VS2015.

### Actual result
The extension does not install on VS2015.

```
Log file:
3/28/2018 11:17:56 PM - 
3/28/2018 11:17:56 PM - Supported Products : 
3/28/2018 11:17:56 PM - Microsoft.VisualStudio.Community
3/28/2018 11:17:56 PM - Version : [15.0]
3/28/2018 11:17:56 PM - 
3/28/2018 11:17:56 PM - References : 
3/28/2018 11:17:56 PM - Signature Details...
3/28/2018 11:17:56 PM - Extension is signed with a valid signature.
3/28/2018 11:17:56 PM - 
3/28/2018 11:17:56 PM - Searching for applicable products...
3/28/2018 11:17:56 PM - Found installed product - Microsoft Visual Studio Professional 2015
3/28/2018 11:17:56 PM - Found installed product - Microsoft Visual Studio Community 2015
3/28/2018 11:17:56 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
3/28/2018 11:17:56 PM - Found installed product - Global Location
3/28/2018 11:17:56 PM - Found installed product - ssms
3/28/2018 11:17:56 PM - Found installed product - ssms
3/28/2018 11:17:56 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
at VSIXInstaller.App.InitializeInstall()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
```

**Comment by AlanWong-MS** [comment]
Fixed with #1150.
