### ISSUE TITLE
$filter in $expand can't work if the $expand applied on function results

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#1162]
We are seeing an Internal Server Error AGS-side when trying this URL: 
https://graph.microsoft.com/v1.0/me/activities/recent?$expand=historyItems($filter=lastModifiedDateTime%20gt%202018-01-22T21:45:00.347Z%20and%20lastModifiedDateTime%20lt%202018-01-22T22:00:00.347Z)

Here’s the error I see in the logs:
```C#
[Microsoft.Online.AggregatorService.Common.InternalServerErrorException: Value cannot be null. Parameter name: type;;[System.ArgumentNullException: Value cannot be null. Parameter name: type;
at Microsoft.OData.Edm.EdmTypeSemantics.IsStructured(IEdmTypeReference type)
at Microsoft.OData.UriParser.SelectExpandBinder.BuildNewMetadataBinder(IEdmNavigationSource targetNavigationSource)
at Microsoft.OData.UriParser.SelectExpandBinder.GenerateExpandItem(ExpandTermToken tokenIn)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
at Microsoft.OData.UriParser.SelectExpandBinder.Bind(ExpandToken tokenIn)
at Microsoft.OData.UriParser.SelectExpandSemanticBinder.Bind(ODataPathInfo odataPathInfo, ExpandToken expandToken, SelectToken selectToken, ODataUriParserConfiguration configuration)
at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpand()
at Microsoft.Online.AggregatorService.Controller.ParserEngine.<Parse>d__0.MoveNext() in x:\bt\880268\repo\src\dev\Controller\Parser\ParserEngine.cs:line 105 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.Online.AggregatorService.Controller.RequestController.<HandleRequest>d__6.MoveNext() in x:\bt\880268\repo\src\dev\Controller\Controllers\RequestController.cs:line 68;]]
```

This looks like a bug. The following all work:
https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=microsoft.graph.driveItem/children
https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=microsoft.graph.driveItem/children($expand=children) 
https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=microsoft.graph.driveItem/children($select=id) 

but these do not:
https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=microsoft.graph.driveItem/children($filter=id eq ‘x’) 
https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=microsoft.graph.driveItem/children($orderby=id) 

### Assemblies affected

* e.g. OData .Net lib 7.x.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
I took a quick look the source codes, basically, “delta” is an edm function which returns a collection of entity. But, it doesn’t set the corresponding target navigation source binding.

The returned navigation source is necessary (at least from the source code) to process the nested $filter, $orderby, $search, $compute. But, it’s not necessary to process the nested $select and $expand.

That’s why the following scenarios can work:
https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=microsoft.graph.driveItem/children
https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=microsoft.graph.driveItem/children($expand=children) 
https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=microsoft.graph.driveItem/children($select=id) 

But, the following scenarios can’t work:
https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=microsoft.graph.driveItem/children($filter=id eq ‘x’) 
https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=microsoft.graph.driveItem/children($orderby=id)

I tested it, if I added the an entity set path (see highlight below) for the delta function, the above failing scenarios can work. 

<Function Name=""delta"" IsBound =""true"" EntitySetPath=""bindingParameter/driveItems"">

I think we should take time to investigate why it needs the path in order to resolve the URL.
Thanks

**Comment by iriszhou320** [comment]
@biaol-odata hey any progress pr workaround on this? currently we cant use $expand with delta query. thanks!!

**Comment by habbes** [comment]
Why not set an `EntitySetPath`?

**Comment by KenitoInc** [comment]
@iriszhou320 Add `EntitySetPath` to your function e.g

```
<Function Name=""GetMyDog"" IsBound=""true"" EntitySetPath=""person/MyDog"">
    <Parameter Name=""person"" Type=""Fully.Qualified.Namespace.Person"" />
    <ReturnType Type=""Fully.Qualified.Namespace.Dog"" />
</Function>
```
