### ISSUE TITLE
The type initializer for 'Microsoft.OData.Edm.Vocabularies.V1.CoreVocabularyModel' threw an exception

### ISSUE THREAD

**Issue by figuerres** [OData/odata.net#1168]
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.OData.Edm.Vocabularies.V1.CoreVocabularyModel' threw an exception.
  Source=Microsoft.OData.Edm
  StackTrace:
   at Microsoft.OData.Edm.EdmModelBase..ctor(IEnumerable`1 referencedModels, IEdmDirectValueAnnotationsManager annotationsManager)
   at Microsoft.OData.Edm.EdmModel..ctor()
   at System.Web.OData.Builder.EdmModelHelperMethods.BuildEdmModel(ODataModelBuilder builder)
   at System.Web.OData.Builder.ODataConventionModelBuilder.GetEdmModel()
   at ADL.Web.Services.WebApiConfig.Register(HttpConfiguration config) in C:\TFSAzure\ATRAK Services\ADL.Web.Services\App_Start\WebApiConfig.cs:line 146
   at System.Web.Http.GlobalConfiguration.Configure(Action`1 configurationCallback)
   at ADL.Web.Services.WebApiApplication.Application_Start() in C:\TFSAzure\ATRAK Services\ADL.Web.Services\Global.asax.cs:line 20

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### Reproduce steps

hard to say as i do not know why i am getting the error.
we have an EF 6.1.3 model that we have Odata endpoints for and build works but running the website throws this error.
the exception and inner exception are not giving any clue like which entity it is trying to resolve.

### Expected result

*What would happen if there wasn't a bug.*

**Comment by figuerres** [comment]
my bad, found a part of the solution had a bad framework version and it only appeared as a reflection error in the edm builder, why there i do not know , the code was not directly related.
