### ISSUE TITLE
Exception is thrown when attempting to read results using 'DataServiceContext'

### ISSUE THREAD

**Issue by julealgon** [OData/odata.net#1281]
I have an OData API endpoint in my .Net Core API and now I'm trying to build a simple test client application by leveraging `Microsoft.OData.Client`s `DataServiceContext` class.

Instead of getting actual results from the API, I'm presented with an exception on the client.

How do I call an OData API using `DataServiceContext`?

### Assemblies affected

Microsoft.OData.Client 7.5.1

### Reproduce steps

1. Create a simple OData API for a single Entity type
2. Try fetching the results from this API from a separate application using `DataServiceContext`
3. Observe exception when materializing the values

Sample client:
```csharp
class SampleModel
{
    int Id { get; set; }
    string Text { get; set; }
}

class Program
{
    static void Main(string[] args)
    {
        var baseApiUrl = new Uri("http://localhost:1200/api");
        var context = new DataServiceContext(baseApiUrl);

        var results = context
            .CreateQuery<SampleModel>("samples")
            .ToList();
    }
}
```

These are the responses I get from my API (in other words, the API itself looks to be working as expected).

1. Metadata (`http://localhost:1200/api/$metadata#samples`):
```xml
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
    <edmx:DataServices>
        <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="MyNamespace.Samples">
            <EntityType Name="SampleModel">
                <Key>
                    <PropertyRef Name="Id"/>
                </Key>
                <Property Name="Id" Type="Edm.Int32" Nullable="false"/>
                <Property Name="Text" Type="Edm.String"/>
            </EntityType>
        </Schema>
        <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Default">
            <EntityContainer Name="Container">
                <EntitySet Name="samples" EntityType="MyNamespace.Samples.SampleModel"/>
            </EntityContainer>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>
```

2. Results (`http://localhost:1200/api/samples`)
```json
{
	"@odata.context": "http://localhost:1200/api/$metadata#samples",
	"value": [{
			"Id": 1,
			"Text": "First"
		}, {
			"Id": 2,
			"Text": "Second"
		}, {
			"Id": 3,
			"Text": "Third"
		}
	],
	"@odata.nextLink": "http://localhost:1200/api/samples?$skip=3"
}
```

### Expected result

The `results` variable in the client would contain the 3 results from the server response (server-side paging set to 3).

### Actual result

An exception is thrown:
- Message: **The complex type 'System.Object' has no settable properties.**
- Full text:
> Microsoft.OData.Client.DataServiceQueryException: An error occurred while processing this request. ---> System.InvalidOperationException: **The complex type 'System.Object' has no settable properties.**
   at Microsoft.OData.Client.ClientEdmModel.ValidateComplexType(Type type, EdmTypeCacheValue cachedEdmType)
   at Microsoft.OData.Client.ClientEdmModel.GetOrCreateEdmType(Type type)
   at Microsoft.OData.Client.TypeResolver.ResolveWireTypeName(IEdmType expectedEdmType, String wireName)
   at Microsoft.OData.Metadata.MetadataUtils.ResolveTypeName(IEdmModel model, IEdmType expectedType, String typeName, Func`3 customTypeResolver, EdmTypeKind& typeKind)
   at Microsoft.OData.JsonLight.ODataJsonLightContextUriParser.ResolveType(String typeName, Func`3 clientCustomTypeResolver, Boolean throwIfMetadataConflict)
   at Microsoft.OData.JsonLight.ODataJsonLightContextUriParser.ParseContextUriFragment(String fragment, Func`3 clientCustomTypeResolver, Boolean throwIfMetadataConflict, Boolean& isUndeclared)
   at Microsoft.OData.JsonLight.ODataJsonLightContextUriParser.ParseContextUri(ODataPayloadKind expectedPayloadKind, Func`3 clientCustomTypeResolver, Boolean throwIfMetadataConflict)
   at Microsoft.OData.JsonLight.ODataJsonLightContextUriParser.Parse(IEdmModel model, String contextUriFromPayload, ODataPayloadKind payloadKind, Func`3 clientCustomTypeResolver, Boolean needParseFragment, Boolean throwIfMetadataConflict)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStart(ODataPayloadKind payloadKind, PropertyAndAnnotationCollector propertyAndAnnotationCollector, Boolean isReadingNestedPayload, Boolean allowEmptyPayload)
   at Microsoft.OData.JsonLight.ODataJsonLightPayloadKindDetectionDeserializer.DetectPayloadKind(ODataPayloadKindDetectionInfo detectionInfo)
   at Microsoft.OData.JsonLight.ODataJsonLightInputContext.DetectPayloadKind(ODataPayloadKindDetectionInfo detectionInfo)
   at Microsoft.OData.Json.ODataJsonFormat.DetectPayloadKindImplementation(ODataMessageInfo messageInfo, ODataMessageReaderSettings settings)
   at Microsoft.OData.Json.ODataJsonFormat.DetectPayloadKind(ODataMessageInfo messageInfo, ODataMessageReaderSettings settings)
   at Microsoft.OData.ODataMessageReader.DetectPayloadKind()
   at Microsoft.OData.Client.Materialization.ODataMaterializer.CreateODataMessageReader(IODataResponseMessage responseMessage, ResponseInfo responseInfo, ODataPayloadKind& payloadKind)
   at Microsoft.OData.Client.Materialization.ODataMaterializer.CreateMaterializerForMessage(IODataResponseMessage responseMessage, ResponseInfo responseInfo, Type materializerType, QueryComponents queryComponents, ProjectionPlan plan, ODataPayloadKind payloadKind)
   at Microsoft.OData.Client.MaterializeAtom..ctor(ResponseInfo responseInfo, QueryComponents queryComponents, ProjectionPlan plan, IODataResponseMessage responseMessage, ODataPayloadKind payloadKind)
   at Microsoft.OData.Client.QueryResult.CreateMaterializer(ProjectionPlan plan, ODataPayloadKind payloadKind)
   at Microsoft.OData.Client.QueryResult.ProcessResult[TElement](ProjectionPlan plan)
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   --- End of inner exception stack trace ---
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at Microsoft.OData.Client.DataServiceQuery`1.Execute()
   at Microsoft.OData.Client.DataServiceQuery`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

### Additional detail

- The client component is somehow thinking I'm dealing with a complex type here, while the model is actually an entity. Is there a way to "tell it" `SampleModel` is an entity and not a complex type?
- When fetching the results using the `Simple.OData.Client` library I get the expected results. I'd like to avoid the extra library dependency if possible though as we have a very simple use case.
- Several years ago when I used this same class to fetch results from a WCF Data Service endpoint, it worked as expected

**Comment by biaol-odata** [comment]
@julealgon I think the issue is the EDMModel in the dataservicecontext of your client is not setup correctly, and the samples entityset cannot be found from the model. 

With ODL-7.5.1, in the DataServiceContext instance, the edmModel used for deserialize the payload needs to be initialized before creating query, as follows based on your program:
```
context.Format.UseJson(edmModel);
```
You can use existing edmModel if you already have one handy, or you can try retrieving it from the service:
```
            HttpWebRequestMessage message = new HttpWebRequestMessage(new Uri(ServiceBaseUri.AbsoluteUri + "$metadata", UriKind.Absolute));
            message.SetHeader("Accept", MimeTypes.ApplicationXml);

            IEdmModel edmModel = null;
            using (var messageReader = new ODataMessageReader(message.GetResponse()))
            {
                Func<Uri, XmlReader> getReferencedSchemaFunc = uri =>
                {
                    return XmlReader.Create(GetStreamFromUrl(uri.AbsoluteUri));
                };
                edmModel = messageReader.ReadMetadataDocument(getReferencedSchemaFunc);
            }
```

**Comment by julealgon** [comment]
> @julealgon Did you have chance to try the solution from Biao's comment? Please let us know any further questions.

I saw it but didn't manage to try yet @xuzhg . I'll need this in 2 weeks at the most as I'll be building an OData consumer over here. Will report back as soon as I can.

Does anybody know why this isn't done automatically though. like SimpleOData does?

**Comment by biaol-odata** [comment]
@julealgon Please let's know whether adding the model init solve the problem. I believe this is by design for DataServiceContext. You can submit an issue with more details related to OData vs. SimpleOData so that we can triage. Thanks!

**Comment by vitaliipanchenko** [comment]
Hi
I have same issue but with navigation property.
Please let me know if there is a fix or workaround.

**Comment by gathogojr** [comment]
To summarize, it's easier to use the [OData Connected Service extension](https://marketplace.visualstudio.com/items?itemName=marketplace.ODataConnectedService) to generate client-side proxy for interacting with an OData service.
If you want to use `DataServiceContext` directly, then you need to supply the Edm model. Here's sample code that does the job
```csharp
var baseApiUrl = new Uri("http://localhost:1200/api");
var metadataUri = new Uri(baseApiUrl.AbsoluteUri + "/$metadata");
var context = new DataServiceContext(baseApiUrl);

IEdmModel model;
var request = WebRequest.CreateHttp(metadataUri);

using (var response = request.GetResponse())
{
    using (var stream = response.GetResponseStream())
    {
        using (var reader = XmlReader.Create(stream))
        {
            model = CsdlReader.Parse(reader);
        }
    }
}

context.Format.UseJson(model);

var results = context
    .CreateQuery<SampleModel>("Samples")
   .ToList();
```
