### ISSUE TITLE
Change Request: Remove null check on 'ODataFeature().TotalCount' property

### ISSUE THREAD

**Issue by julealgon** [OData/odata.net#1283]
The `TotalCount` property under `Request.ODataFeature()` extension throws an exception when an attempt is made to set it to `null`. This is inconsistent with other properties that are also nullable, like `NextLink` and `SelectExpandClause`.

I suggest removing the "not `null`" restriction as there is no problem when this value is null, and it would make our life easier being able to set the value without having to write checks upfront.

### Assemblies affected

Microsoft.OData.Client 7.5.1

### Reproduce steps

Assign a null value to the `TotalCount` property, like this:
```csharp
Request.ODataFeature().TotalCount = (oDataQueryOptions.Count?.Value ?? false) 
    ? data.Length 
    : default(long?);
```

### Expected result

No exception should be thrown and the property should be set to `null`. When it is `null`, no `@odata.count` property should be emitted in the OData response.

### Actual result

An `ArgumentNullException` is thrown in the assignment:

> System.ArgumentNullException: Value cannot be null.
Parameter name: value
 -at Microsoft.AspNet.OData.ODataFeature.set_TotalCount(Nullable`1 value)
 -at Dell.Premier.Product.API.Controllers.ProductDetailController.GetData(ODataQueryOptions`1 oDataQueryOptions) in C:\Github\premier-productapi\ProductApi\Dell.Premier.Product.API\Controllers\ProductDetailController.cs:line 167
 -at lambda_method(Closure , Object , Object[] )
 -at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
 -at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
...

### Additional detail

- There is a workaround to this by actually setting the `TotalCountFunc` property instead, but it is quite convoluted as it is typed as a `Func<long>` and not a `Func<long?>`:

```csharp
Request.ODataFeature().TotalCountFunc = (oDataQueryOptions.Count?.Value ?? false) 
    ? () => data.Length 
    : default(Func<long>);
```

**Comment by julealgon** [comment]
Closing this as I incorrectly created the issue in the client side. This is supposed to be a server assembly issue.

New item here:
https://github.com/OData/WebApi/issues/1637
