### ISSUE TITLE
Exception while attempting to parse non-lowercase value in '$count' query option

### ISSUE THREAD

**Issue by julealgon** [OData/odata.net#1330]
When making an OData request and passing the `$count=true|false` query option, query validation fails when the Boolean values are not 100% lowercase. This is inconsistent with C# Boolean parsing as well as with the default `True|False` values generated by `bool.ToString()` and `bool.TrueString|FalseString`.

### Assemblies affected

Microsoft.AspNetCore.OData 7.1.0

### Reproduce steps

1. Create an API that supports the `$count` option
2. Make a request specifying the `$count` value with an explicit boolean
    a. `GET http://localhost/api/odata/productdetails?$count=true`
    b. `GET http://localhost/api/odata/productdetails?$count=True`
    c. `GET http://localhost/api/odata/productdetails?$count=TRUE`

### Expected result

All 3 requests should pass parsing and hit the controller with `count` set to `true`.

### Actual result

Requests 2.a pass as expected.
Request 2.b, and 2.c fail with an exception

>Microsoft.OData.ODataException: 'TRUE' is not a valid count option.
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseCount(String count)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseCount()
   at Microsoft.AspNet.OData.Query.CountQueryOption.get_Value()
   ...

### Additional detail
This appears to have already been posted 2 years ago (!):
https://github.com/OData/odata.net/issues/718

I'll keep this in here and leave it up to you to decide which one is still considered valid. Notice that versions have since changed drastically (so I'd consider keeping this more recent one open).

I found this out while playing with the `DataServiceContext` `.AddQueryOption` method. This code generated the URL which failed on the server:
```csharp
dataServiceQuery.AddQueryOption("$count", false);
```

For some context, I wanted to make sure that I had an explicit `$count=false` on my query since I'm handling the logic manually on the server using `ODataQueryOptions<T>`. AFAIK it is not possible to generate a `$count=false` using abstractions like `IncludeTotalCount()`, as it only adds the `true` version to the query and is not parameterized (I'll create another issue to discuss that particular point).

**Comment by julealgon** [comment]
Created the issue in the wrong place once again 😠 

Replicated on the server repo now:
https://github.com/OData/WebApi/issues/1690

Please follow-up there.
