### ISSUE TITLE
Accessing OData endpoint from Blazor application

### ISSUE THREAD

**Issue by cilerler** [OData/odata.net#1335]
I was playing with [Blazor](https://blazor.net/) v0.7.0 and OData v7.5.2 client.

- used `dotnet new blazorhosted` command to create the projects
- added ODataClient to **shared** one.

## MyProject.Shared.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.OData.Client" Version="7.5.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ODataClient1.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ODataClient1.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ODataClient1.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ODataClient1.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
```

- updated **ODataClient1.tt** with `public const string MetadataDocumentUri = "https://services.odata.org/V4/(S(qc322lduoxrqt13nhydbdcvx))/TripPinServiceRW/";`

- changed the **SampleDataController.cs** `WeatherForecasts` function with code below

## MyProject.Server.Controllers.SampleDataController.cs

```csharp
[HttpGet("[action]")]
public IEnumerable<WeatherForecast> WeatherForecasts()
{
    const string serviceUri = "https://services.odata.org/V4/(S(qc322lduoxrqt13nhydbdcvx))/TripPinServiceRW/";
    var container = new DefaultContainer(new Uri(serviceUri));

    var nquery = container.People.Where(p => p.Gender == PersonGender.Female)
                          .Take(10);
    string[] summaries = nquery.Select(p => p.FirstName)
                               .ToArray();

    var rng = new Random();
    return Enumerable.Range(1
                          , 5)
                     .Select(index => new WeatherForecast
                                      {
                                          Date = DateTime.Now.AddDays(index)
                                        , TemperatureC = rng.Next(-20
                                                                , 55)
                                        , Summary = summaries[rng.Next(summaries.Length)]
                                      });
}
```

- received the error below _(and started to poke around...)_

```
System.NotSupportedException
  HResult=0x80131515
  Message=This target framework does not enable you to directly enumerate over a data service query. This is because enumeration automatically sends a synchronous request to the data service. Because this framework only supports asynchronous operations, you must instead call the BeginExecute and EndExecute methods to obtain a query result that supports enumeration.
  Source=Microsoft.OData.Client
  StackTrace:
   at Microsoft.OData.Client.DataServiceQuery`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MyProject.Server.Controllers.SampleDataController.WeatherForecasts() in C:\Source\!repos\MyProject\MyProject.Server\Controllers\SampleDataController.cs:line 28
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

- changed code below

```csharp
    string[] summaries = nquery.Select(p => p.FirstName)
                               .ToArray();
```
with this one

```csharp
    var query = (DataServiceQuery<Person>) nquery;
    var taskFactory = new TaskFactory<IEnumerable<Person>>();
    IEnumerable<Person> result = taskFactory.FromAsync(query.BeginExecute(null
                                                                        , null)
                                                     , iar => query.EndExecute(iar))
                                            .Result;
    string[] summaries = result.Select(p => p.FirstName)
                               .ToArray();
```

and it worked.

Now, my question is, is there a simplified _(prettier syntax etc.)_ way of handling things?

**Comment by robertmclaws** [comment]
Yes. Don't use ODataClient at all and just use the built-in Blazor JsonRequest code. The juice is not worth the squeeze in this case. Seriously, that client is so freakin old, it needs to be put out into the street and shot.

**Comment by cilerler** [comment]
Thanks @robertmclaws It is sad that your thoughts are pretty close to mine.  I just hoped maybe someone _(such as @xuzhg or @AlanWong-MS)_ out there can give a light on this.  I feel like Microsoft doesn't want people to use OData at all. 

Leaving it open for now to hope that it may get attention. 

Also I just saw this one https://github.com/OData/odata.net/issues/1303

**Comment by robertmclaws** [comment]
Well, I mean the code under the covers is still using whatever pre-HttpClient nonsense the framework was using back in 2011. OData's a pretty huge framework to modernize, and it's not like other teams at Microsoft made it any easier with this .NET Core stuff. I have faith they'll get to it, it's just a lot on their plate.

I've had a problem with the architecture for a long time, in that what could arguably be the most common use case (corporate or government apps building services to consume with their own apps), there is just too damn much code generation. I still use EDMX files for my databases, and do a lot of my code generation from there. I have a set of T4 templates that generate a single code model that can be used from both the EF AND OData clients, but T4 is getting long in the tooth as well.

So I've been putting some thought about how to generate these things in the .NET Standard world, potentially either with Roslyn or an approach similar to TypeLite and my TypeLitePlus fork.

In the meantime, I feel like Simple.OData.Client is probably the best bet for .NET apps, and just using JSON for Blazor apps. I realize that doesn't always get you batch support, but I think I may have a solution for that sometime soon.

@cilerler If I tried to put a project together, would you be interested in contributing?

**Comment by cilerler** [comment]
@robertmclaws  I'm sorry about the very delayed response, somewhat I didn't get notification for this _(most likely I accidentally deleted it)_.  

I appreciate that you shared your thoughts.  I wish ODATA team will start doing open weekly _(or at least monthly)_ stand-up like DOTNET team does.

> _"If I tried to put a project together, would you be interested in contributing"_ 

Even I love the idea, I have too much in my plate these days and I don't want to commit something I can't give enough attention and become the bottleneck.  Such a project would be definitely in my radar.  Thank you for asking!

**Comment by madansr7** [comment]
@cilerler , unfortunately there isn't a simpler async pattern supported for these frameworks.

**Comment by madansr7** [comment]
@cilerler , great idea on open weekly stand-up. We have been thinking along the same lines of having a regular OData community call.

**Comment by itVico** [comment]
This is might be a prettier syntax:
```
    var response = await nquery.ExecuteAsync();
    foreach (var p in (response as QueryOperationResponse<Person>))
    {
        System.Diagnostics.Debug.WriteLine("result: " + p.FirstName);
    }
```

**Comment by raffaeler** [comment]
This extension method can be used to avoid the mess:
```
public static class QueryExtensions
{
    public async static Task<IEnumerable<T>> ToAsync<T>(this IQueryable<T> query)
    {
        if (query is System.Data.Services.Client.DataServiceQuery<T> dataServiceQuery)
        {
            var factory = new TaskFactory<IEnumerable<T>>();
            var result = await factory.FromAsync(
                dataServiceQuery.BeginExecute(null, null),
                a => dataServiceQuery.EndExecute(a));

            return result;
        }

        return query;
    }
}
```

Usage:
```
var client = new MyContext();
var myarticles = (await client.Articles
    .Where(a => a.Descrizione.StartsWith("abc"))
    .ToAsync())
    .ToList();
```

Note: the client context code was generated in a .NET Core 3.1 library using the [Unchase generator](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice) installed on VS2019.

HTH
