### ISSUE TITLE
Client: OData actions returning partial objects won't deserialize.

### ISSUE THREAD

**Issue by twastvedt** [OData/odata.net#1339]
I'm not sure if this is a bug, an unsupported feature, or a lack of my understanding of the library. I'm using OData .Net Client with a Dynamics 365 CRM instance. When I use the action [InstantiateTemplate](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/instantiatetemplate?view=dynamics-ce-odata-9), the response looks something like this:
```
{
  "@odata.context": "https://azahner.crm.dynamics.com/api/data/v9.0/$metadata#emails",
  "value": [{
    "@odata.type": "#Microsoft.Dynamics.CRM.email",
    "desscription": "Template message text",
    "subject": "Message subject"
  }]
}
```

When I try to access the response content though, it looks like OData .Net Client tries to deserialize the response into an `email` object and can't because an id isn't provided: `The entity instance value of type 'Microsoft.Dynamics.CRM.email' doesn't have a value for property 'activityid'. To compute an entity's metadata, its key and concurrency-token property values must be provided.`

### Assemblies affected

OData .Net Client 7.5.0.20627

### Reproduce steps

Generate code for Dynamics CRM instance using OData v4 Client Code Generator. Create an opportunity and an email template in CRM and get their IDs. Run this:
```
var emailText = (await client
  .InstantiateTemplate( templateId, "opportunity", opportunityId )
  .ExecuteAsync()).First();
```

### Expected result

What makes sense to me would be for ExecuteAsync to return partial objects (not full `email` objects) with the fields present in the response. Maybe there's another way already though?

### Actual result

Enumerating the `IEnumerable` returned by `ExecuteAsync` fails because it tries to create an `email` object from the response json, which only contains a couple email fields (notably not an id).
`The entity instance value of type 'Microsoft.Dynamics.CRM.email' doesn't have a value for property 'activityid'. To compute an entity's metadata, its key and concurrency-token property values must be provided.`

**Comment by madansr7** [comment]
@twastvedt , can you please provide a stacktrace and $metadata response.

**Comment by twastvedt** [comment]
Stack trace:
```
   at Microsoft.OData.Evaluation.ODataResourceMetadataContext.GetPrimitiveOrEnumPropertyValue(ODataResourceBase resource, String propertyName, String entityTypeName, Boolean isKeyProperty)
   at Microsoft.OData.Evaluation.ODataResourceMetadataContext.ODataResourceMetadataContextWithModel.<get_KeyProperties>b__5_0(IEdmStructuralProperty p)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.OData.Evaluation.ODataResourceMetadataContext.ODataResourceMetadataContextWithModel.get_KeyProperties()
   at Microsoft.OData.Evaluation.ODataConventionalEntityMetadataBuilder.get_ComputedKeyProperties()
   at Microsoft.OData.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeId()
   at Microsoft.OData.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeAndCacheId()
   at Microsoft.OData.Evaluation.ODataConventionalEntityMetadataBuilder.GetId()
   at Microsoft.OData.Client.Materialization.MaterializerEntry.UpdateEntityDescriptor()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.ReadEntryCore()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryReadEntry(MaterializerEntry& entry)
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.<LazyReadEntries>d__22.MoveNext()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.Read()
   at Microsoft.OData.Client.Materialization.ODataReaderEntityMaterializer.ReadNextFeedOrEntry()
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at <project name omitted>.CreateProposalEmailAction.<>c__DisplayClass4_0.<<ExecuteAsync>b__1>d.MoveNext() in C:\<path omitted>\CreateProposalEmailAction.cs:line 112
```
Are you looking for the full site metadata? (https://tenant.crm.dynamics.com/api/data/v9.0/$metadata) Here's that, but let me know if you meant something different.

[$metadata.txt](https://github.com/OData/odata.net/files/2649541/metadata.txt)

Thanks!

**Comment by ElizabethOkerio** [comment]
@twastvedt. Hi. You can achieve this by not using the code generator. You can create a class that extends the <code> OData.Client.DataServiceContext </code> class then create POCO classes that are partials of the types that you need then resolve them as of that type. 
Like below: 
<pre>
    public partial class ExtendedDataServiceContext : DataServiceContext
    {
        public ExtendedDataServiceContext(Uri serviceUri)
            : base(serviceUri)
        {
            Format.LoadServiceModel = LoadServiceModel;
            Format.UseJson();
        }

        private IEdmModel LoadServiceModel()
        {
            // Get the service metadata's Uri
            var metadataUri = GetMetadataUri();
            // Create a HTTP request to the metadata's Uri 
            // in order to get a representation for the data model
            var request = WebRequest.CreateHttp(metadataUri);
            
            using (var response = request.GetResponse())
            {
                // Translate the response into an in-memory stream
                using (var stream = response.GetResponseStream())
                {
                    // Convert the stream into an XML representation
                    using (var reader = System.Xml.XmlReader.Create(stream))
                    {
                        // Parse the XML representation of the data model
                        // into an EDM that can be utilized by OData client libraries
                        return Microsoft.OData.Edm.Csdl.CsdlReader.Parse(reader);
                    }
                }
            }
        }
    }
</pre>

then create a POCO class that has only the fields you want.
<pre>
   public class EmailPartial
    {
        public string subject{ get; set; }
        public string description{ get; set; }
    }
</pre>

then get your action like this: 
       var serviceUri = new Uri("http://localhost/odata");
       var context = new ExtendedDataServiceContext(serviceUri);
       context.ResolveType = name => {
                switch(name)
                {
                    case "Microsoft.Dynamics.CRM.email":
                        return typeof(EmailPartial);
                    default:
                        return null;
                }
            };
   var emailText = (await context.InstantiateTemplate( templateId, "opportunity", opportunityId )
  .ExecuteAsync()).First();

**Comment by ElizabethOkerio** [comment]
am closing this issue but you can reopen it if you run into any problem or if this does not solve your issue.
