### ISSUE TITLE
OData Client Request Pipeline not working in Odata V4

### ISSUE THREAD

**Issue by sammym1982** [OData/odata.net#134]
I am following the sample blog below to remove and add properties in request ODataEntry class. 

http://blogs.msdn.com/b/odatateam/archive/2013/07/26/using-the-new-client-hooks-in-wcf-data-services-client.aspx

But even if the code works fine and adds and removes the properties correctly when I put breakpoint, all the entity properties goes to server un changed.

Seems like this issue is specific to OdataV4 and new odata client side proxies. 

sample client side code
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Client.Default;

namespace Client
{

using Client.MvcApplication1.Models;

using Microsoft.OData.Core;

internal class Program
{
    private static void Main(string[] args)
    {
        Container container = new Container(new Uri("http://localhost:55000/api/"));

        container.Configurations.RequestPipeline.OnEntryEnding(
            w =>
            {
                w.Entry.RemoveProperties("Name");
            });

        Test test = new Test();
        test.Name = "Foo";
        container.AddToTests(test);
        container.SaveChanges();
    }
}

public static class Extensions
{

    public static void RemoveProperties(this ODataEntry entry, params string[] propertyNames)
    {

        var properties = entry.Properties as List<ODataProperty>;
        if (properties == null)
        {
            properties = new List<ODataProperty>(entry.Properties);
        }

        var propertiesToRemove = properties.Where(p => propertyNames.Any(rp => rp == p.Name));
        foreach (var propertyToRemove in propertiesToRemove.ToArray())
        {
            properties.Remove(propertyToRemove);
        }

        entry.Properties = properties;

    }

    public static void AddProperties(this ODataEntry entry, params ODataProperty[] newProperties)
    {
        var properties = entry.Properties as List<ODataProperty>;
        if (properties == null)
        {
            properties = new List<ODataProperty>(entry.Properties);
        }

        properties.AddRange(newProperties);

        entry.Properties = properties;

    }
}
}
```

**Comment by sammym1982** [comment]
If I change and start listening to RequestPipeline.OnEntryStarting I get the validation error that new property is not defined in owning entity. But as per code for Microsoft.OData.CLient this error should not occure as there is a check for IEdmStructuredType.IsOpen but still error occurs. So issue seems deep in how owningStructuredType is calculated. On my container I do see the correct edm model with entities marked as IsOpen = true.

Odata lib code which should pass but is failing

```c#
internal static IEdmProperty ValidatePropertyDefined(string propertyName, IEdmStructuredType owningStructuredType)
        {
            Debug.Assert(!string.IsNullOrEmpty(propertyName), "!string.IsNullOrEmpty(propertyName)");

            if (owningStructuredType == null)
            {
                return null;
            }

            IEdmProperty property = owningStructuredType.FindProperty(propertyName);

            // verify that the property is declared if the type is not an open type.
            if (!owningStructuredType.IsOpen && property == null)
            {
                throw new ODataException(Strings.ValidationUtils_PropertyDoesNotExistOnType(propertyName, owningStructuredType.ODataFullName()));
            }

            return property;
        }
```

Client code:

```c#
container.Configurations.RequestPipeline.OnEntryStarting(
                w =>
                {
                    w.Entry.RemoveProperties("Name");
                    w.Entry.AddProperties(new ODataProperty
                                              {
                                                  Name = "NewProperty",
                                                  Value = 1
                                              });
                });
```

Error:

```error


The property 'NewProperty' does not exist on type 'Client.MvcApplication1.Models.Test'. Make sure to only use property names that are defined by the type.

   at Microsoft.OData.Core.WriterValidationUtils.ValidatePropertyDefined(String propertyName, IEdmStructuredType owningStructuredType)
   at Microsoft.OData.Core.JsonLight.ODataJsonLightPropertySerializer.WriteProperty(ODataProperty property, IEdmStructuredType owningType, Boolean isTopLevel, Boolean allowStreamProperty, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, ProjectedPropertiesAnnotation projectedProperties)
   at Microsoft.OData.Core.JsonLight.ODataJsonLightPropertySerializer.WriteProperties(IEdmStructuredType owningType, IEnumerable`1 properties, Boolean isComplexValue, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, ProjectedPropertiesAnnotation projectedProperties)
   at Microsoft.OData.Core.JsonLight.ODataJsonLightWriter.StartEntry(ODataEntry entry)
   at Microsoft.OData.Core.ODataWriterCore.<>c__DisplayClass14.<WriteStartEntryImplementation>b__12()
   at Microsoft.OData.Core.ODataWriterCore.InterceptException(Action action)
   at Microsoft.OData.Core.ODataWriterCore.WriteStartEntryImplementation(ODataEntry entry)
   at Microsoft.OData.Core.ODataWriterCore.WriteStart(ODataEntry entry)
   at Microsoft.OData.Client.ODataWriterWrapper.WriteStart(ODataEntry entry, Object entity)
   at Microsoft.OData.Client.Serializer.WriteEntry(EntityDescriptor entityDescriptor, IEnumerable`1 relatedLinks, ODataRequestMessageWrapper requestMessage)
   at Microsoft.OData.Client.BaseSaveResult.CreateRequestData(EntityDescriptor entityDescriptor, ODataRequestMessageWrapper requestMessage)
   at Microsoft.OData.Client.BaseSaveResult.CreateChangeData(Int32 index, ODataRequestMessageWrapper requestMessage)
   at Microsoft.OData.Client.SaveResult.CreateNonBatchChangeData(Int32 index, ODataRequestMessageWrapper requestMessage)
   at Microsoft.OData.Client.SaveResult.CreateNextChange()
```

**Comment by LaylaLiu** [comment]
@ sammym1982， About the first issue you reported, the doc is for OData V3. For OData V4, you need to use OnEntryStarting, just as you mentioned in your comment.

To use open property, actually you can add a CLR property into your entity class just as other properties in this CLR class.

**Comment by sammym1982** [comment]
Hi Layla,

Thanks for responding. My reasoning is same as that provided by AdamCaviness in issue #143 . In our scenario entity goes through different lifecycle states which adds the dynamic properties dynamically therefore we don't have the option of adding the static fields on our entity on client side.

I use the somewhat same approach as mentioned by AdamCaviness to get all dynamic properties only I hook up in ResponsePipeline. 

As I mentioned above ideally the OnEntryStarting should have worked if the ValidatePropertyDefined would not have the potential bug because the following condition not taking excluding open types as intended

```c#
// verify that the property is declared if the type is not an open type.
if (!owningStructuredType.IsOpen && property == null)
{
throw new ODataException(Strings.ValidationUtils_PropertyDoesNotExistOnType(propertyName, owningStructuredType.ODataFullName()));
}
```

**Comment by sammym1982** [comment]
@LaylaLiu any update on if this is accepted and be fixed in future release?

**Comment by LaylaLiu** [comment]
@sammym1982, yes, you are right now. But i think it is reasonable to check whether a property is a valid property of a type. The way to fix this issue should be to add a mechanism to indicate a structuredType is open type on client side. Would you like to contribute? Thanks.

**Comment by AdamCaviness** [comment]
@LaylaLiu I think that @sammym1982 and I are both pointing out that there is apparently **already a mechanism** in Microsoft.OData.Core.WriterValidationUtils.ValidatePropertyDefined for checking if the type is an Open Type but it is not functioning.  The following code is currently in WriterValidationUtils in OData Core:
```CSharp
internal static IEdmProperty ValidatePropertyDefined(string propertyName, IEdmStructuredType owningStructuredType)
{
	Debug.Assert(!string.IsNullOrEmpty(propertyName), "!string.IsNullOrEmpty(propertyName)");

	if (owningStructuredType == null)
	{
		return null;
	}

	IEdmProperty property = owningStructuredType.FindProperty(propertyName);

	// verify that the property is declared if the type is not an open type.
	if (!owningStructuredType.IsOpen && property == null)
	{
		throw new ODataException(Strings.ValidationUtils_PropertyDoesNotExistOnType(propertyName, owningStructuredType.ODataFullName()));
	}

	return property;
}
```
Notice there is even a comment in the existing code stating there **should not be an exception** if it is an open type.
