### ISSUE TITLE
IN operator not working with invalid array value list on string properties

### ISSUE THREAD

**Issue by sebastienrob** [OData/odata.net#1378]
An IndexOutOfRangeException is thrown while parsing a filter expression with the IN operator and an extra comma at the end for a string property. 

Example:
```
http://host/service/TestEntity?$filter=PropertyString in ('a','b',)
```

The problem seems to be related to this line of code:
https://github.com/OData/odata.net/blob/2cf5247da1fde1bfde63d3daf8acdd56ec8a156e/src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs#L174
If str is empty, then the str[str.Length-1] will fail with the IndexOutOfRangeException.

### Assemblies affected

ODataLib 7.5.3

### Reproduce steps

Sample Model
```c#
public class TestEntity
{
   [Key]
   public int PropertyKey { get; set; }

   public int PropertyInt { get; set; }

   public string PropertyString { get; set; }
}
```
Sample query
```
http://host/service/TestEntity?$filter=PropertyString in ('a','b',)
```
### Expected result

An ODataException explaining that the IN value list is in an incorrect format.

### Actual result

An IndexOutOfRangeException is thrown:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.OData.UriParser.InBinder.NormalizeStringItem(String str)
   at Microsoft.OData.UriParser.InBinder.NormalizeCollectionItems(String bracketLiteralText, NormalizeFunction normalizeFunc)
   at Microsoft.OData.UriParser.InBinder.GetCollectionOperandFromToken(QueryToken queryToken, IEdmTypeReference expectedType, IEdmModel model)
   at Microsoft.OData.UriParser.InBinder.BindInOperator(InToken inToken, BindingState state)
   at Microsoft.OData.UriParser.MetadataBinder.BindIn(InToken inToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()
   at Microsoft.OData.UriParser.ODataUriParser.ParseFilter()
```
### Additional detail

if we try the same query on a int property, we are receiving an ODataException explaining the value list is not in a correct format, which is correct.

```
http://host/service/TestEntity?$filter=PropertyInt in (1,2,)
```

```
Microsoft.OData.ODataException: Invalid JSON. An unexpected comma was found in scope 'Array'. A comma is only valid between properties of an object or between elements of an array.
   at Microsoft.OData.Json.JsonReader.Read()
   at Microsoft.OData.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.OData.Json.BufferingJsonReader.ReadNextAndCheckForInStreamError()
   at Microsoft.OData.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.OData.Json.BufferingJsonReader.Read()
   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadPrimitiveValue(Boolean insideJsonObjectValue, IEdmPrimitiveTypeReference expectedValueTypeReference, Boolean validateNullValue, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String payloadTypeName, IEdmTypeReference expectedTypeReference, PropertyAndAnnotationCollector propertyAndAnnotationCollector, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideResourceValue, String propertyName, Nullable`1 isDynamicProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadCollectionValue(IEdmCollectionTypeReference collectionValueTypeReference, String payloadTypeName, ODataTypeAnnotation typeAnnotation)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String payloadTypeName, IEdmTypeReference expectedTypeReference, PropertyAndAnnotationCollector propertyAndAnnotationCollector, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideResourceValue, String propertyName, Nullable`1 isDynamicProperty)
   at Microsoft.OData.ODataUriConversionUtils.ConvertFromResourceOrCollectionValue(String value, IEdmModel model, IEdmTypeReference typeReference)
   at Microsoft.OData.UriParser.InBinder.GetCollectionOperandFromToken(QueryToken queryToken, IEdmTypeReference expectedType, IEdmModel model)
   at Microsoft.OData.UriParser.InBinder.BindInOperator(InToken inToken, BindingState state)
   at Microsoft.OData.UriParser.MetadataBinder.BindIn(InToken inToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()
   at Microsoft.OData.UriParser.ODataUriParser.ParseFilter()
```

**Comment by KanishManuja-MS** [comment]
@KanishManuja-MS Should fix this as it should not be time consuming.

**Comment by gathogojr** [comment]
This issue has since been fixed. Expected error message is currently returned when the array comprises of strings
Request: `/Categories?$filter=Name in ('Food',)`
Response:
>>{
    "error": {
        "code": "",
        "message": "The query specified in the URI is not valid. Invalid JSON. An unexpected comma was found in scope 'Array'. A comma is only valid between properties of an object or between elements of an array.",
        "details": [],
        "innererror": {
            "message": "Invalid JSON. An unexpected comma was found in scope 'Array'. A comma is only valid between properties of an object or between elements of an array.",
            "type": "Microsoft.OData.ODataException",
            "stacktrace": "   at Microsoft.OData.Json.JsonReader.Read()\r\n   at Microsoft.OData.Json.BufferingJsonReader.ReadInternal()\r\n   at Microsoft.OData.Json.BufferingJsonReader.ReadNextAndCheckForInStreamError()\r\n   at Microsoft.OData.Json.BufferingJsonReader.ReadInternal()\r\n   at Microsoft.OData.Json.BufferingJsonReader.Read()\r\n   at Microsoft.OData.Json.JsonReaderExtensions.ReadNext(IJsonReader jsonReader, JsonNodeType expectedNodeType)\r\n   at Microsoft.OData.Json.JsonReaderExtensions.ReadPrimitiveValue(IJsonReader jsonReader)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadPrimitiveValue(Boolean insideJsonObjectValue, IEdmPrimitiveTypeReference expectedValueTypeReference, Boolean validateNullValue, String propertyName)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String payloadTypeName, IEdmTypeReference expectedTypeReference, PropertyAndAnnotationCollector propertyAndAnnotationCollector, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideResourceValue, String propertyName, Nullable`1 isDynamicProperty)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadCollectionValue(IEdmCollectionTypeReference collectionValueTypeReference, String payloadTypeName, ODataTypeAnnotation typeAnnotation)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String payloadTypeName, IEdmTypeReference expectedTypeReference, PropertyAndAnnotationCollector propertyAndAnnotationCollector, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideResourceValue, String propertyName, Nullable`1 isDynamicProperty)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValue(String payloadTypeName, IEdmTypeReference expectedValueTypeReference, PropertyAndAnnotationCollector propertyAndAnnotationCollector, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideResourceValue, String propertyName, Nullable`1 isDynamicProperty)\r\n   at Microsoft.OData.ODataUriConversionUtils.ConvertFromResourceOrCollectionValue(String value, IEdmModel model, IEdmTypeReference typeReference)\r\n   at Microsoft.OData.ODataUriConversionUtils.ConvertFromCollectionValue(String value, IEdmModel model, IEdmTypeReference typeReference)\r\n   at Microsoft.OData.UriParser.InBinder.GetCollectionOperandFromToken(QueryToken queryToken, IEdmTypeReference expectedType, IEdmModel model)\r\n   at Microsoft.OData.UriParser.InBinder.BindInOperator(InToken inToken, BindingState state)\r\n   at Microsoft.OData.UriParser.MetadataBinder.BindIn(InToken inToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()\r\n   at Microsoft.AspNet.OData.Query.FilterQueryOption.get_FilterClause() in ..."
        }
    }
}
