### ISSUE TITLE
Defining custom uri function with name 'contains' causes exception

### ISSUE THREAD

**Issue by Nikiflav** [OData/odata.net#1395]
*Defining a custom uri function named 'contains' with complex type as first argument and string as a second causes exception.*

### Assemblies affected

Microsoft.OData.Core 

### Reproduce steps

Register a new uri function contains(MultilanguageString, string) .
MultilanguageString is complex type.

Try to parse
$filter=contains(PartNumber,'0001') and contains(Name,'a')
PartNumber is of type string, Name is of type MultilanguageString.

### Expected result

*Both functions to be parsed correctly.*

### Actual result

*Exception is thrown when parsing the standard contains(string,string) function.*

### Additional detail

System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Microsoft.OData.Edm.EdmCoreModelPrimitiveType' to type 'Microsoft.OData.Edm.IEdmStructuredType'.
  Source=Microsoft.OData.Core
  StackTrace:
   at Microsoft.OData.UriParser.TypePromotionUtils.CanConvertTo(SingleValueNode sourceNodeOrNull, IEdmTypeReference sourceReference, IEdmTypeReference targetReference)
   at Microsoft.OData.UriParser.TypePromotionUtils.CanPromoteNodeTo(SingleValueNode sourceNodeOrNull, IEdmTypeReference sourceType, IEdmTypeReference targetType)
   at Microsoft.OData.UriParser.TypePromotionUtils.FindBestFunctionSignature(IList`1 nameFunctions, SingleValueNode[] argumentNodes, String functionCallToken)
   at Microsoft.OData.UriParser.FunctionCallBinder.MatchSignatureToUriFunction(String functionCallToken, SingleValueNode[] argumentNodes, IList`1 nameSignatures)
   at Microsoft.OData.UriParser.FunctionCallBinder.BindAsUriFunction(FunctionCallToken functionCallToken, List`1 argumentNodes)
   at Microsoft.OData.UriParser.FunctionCallBinder.BindFunctionCall(FunctionCallToken functionCallToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, QueryToken queryToken)
   at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()
   at Microsoft.OData.UriParser.ODataUriParser.ParseUri()
   
The problem is in method Microsoft.OData.UriParser.TypePromotionUtils.CanConvertTo() when targetReference is complex type but sourceReference is primitive type.

**Comment by KanishManuja-MS** [comment]
@Nikiflav There is already a built in function name called contains. You 'd have to invoke your function with a fully qualified name.

**Comment by Nikiflav** [comment]
I define my function like this:        
            Microsoft.OData.UriParser.CustomUriFunctions.
                AddCustomUriFunction("contains", new Microsoft.OData.UriParser.FunctionSignatureWithReturnType(
                    EdmPrimitiveTypes.GetEdmPrimitiveType<bool>().ToEdmTypeReference(false),
                    edmMultiLanguageStringType.ToEdmTypeReference(false),
                    EdmPrimitiveTypes.GetEdmPrimitiveType<string>().ToEdmTypeReference(false)));

CustomUriFunctions support functions with equal name but different signature. 

There is a missing check in method Microsoft.OData.UriParser.TypePromotionUtils.CanConvertTo()
in the section
            if (targetReference.IsODataComplexTypeKind() || targetReference.IsODataEntityTypeKind())
            {               
                // for structured types, use IsAssignableFrom
                return EdmLibraryExtensions.IsAssignableFrom(
                    (IEdmStructuredType)targetReference.Definition,
                    (IEdmStructuredType)sourceReference.Definition);
            }
The cast (IEdmStructuredType)sourceReference.Definition) throws exception.
If I add this code before the return, everything works as expected.
                if (!sourceReference.IsODataComplexTypeKind() && !sourceReference.IsODataEntityTypeKind())
                    return false;

**Comment by mikepizzo** [comment]
It appears that this is not due to the name of the function, but the fact that the overload resolution fails when comparing a structured type to an unstructured type, which is addressed in PR #1489.
