### ISSUE TITLE
EnableLowerCamelCase() rises incorrect missing property exception on not mapped property from base class

### ISSUE THREAD

**Issue by rdhainaut** [OData/odata.net#1424]
The method "EnableLowerCamelCase()" from the class "ODataConventionModelBuilderExtensions" rises an incorrect missing property exception when the property is come from a base class and added using fluent api on ODataConventionModelBuilder.  Note: the property is tagged as [NotMapped].
### Assemblies affected
Microsoft.AspNetCore.OData" Version="7.1.0"

### Reproduce steps
I have created a repository with this issue avaible on github at https://github.com/rdhainaut/ODataSample.git
Just run the project to rise the exception.

Note: I have created a new fresh ASP.NET Core Web Application with Web Api template then add latest OData nuget package and some sample classes (models, controllers) and add OData configuration.

### Expected result
Request a GET at https://localhost:5001/odata/people 
Response exepected (someting similar) 
{"@odata.context":"https://localhost:5001/odata/$metadata#People","value":[{"Id":0,"UniqueIdentifier":"ac791bbb-684d-4039-be9e-633a498f2543","Firstname":"John"},{"Id":0,"UniqueIdentifier":"ac636608-ca5e-4054-b601-1ff40e02d855","Firstname":"Bob"},{"Id":0,"UniqueIdentifier":"215cb189-37d4-4a9c-ac79-461e0b1e91bc","Firstname":"Will"}]}
### Actual result

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLLB3Q4TQ9EA", Request id "0HLLB3Q4TQ9EA:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: The EDM instance of type '[ODataIssue.Models.Person Nullable=True]' is missing the property 'uniqueIdentifier'.
   at Microsoft.AspNet.OData.ResourceContext.GetPropertyValue(String propertyName)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralProperty(IEdmStructuralProperty structuralProperty, ResourceContext resourceContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralPropertyBag(IEnumerable`1 structuralProperties, ResourceContext resourceContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateResource(SelectExpandNode selectExpandNode, ResourceContext resourceContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

### Additional detail
If you comment the line 46 in the Startup.cs (so remove the oDataConventionModelBuilder.EnableLowerCamelCase ()) It works as expected.

A simple workaround could be to rename the property in lowerCamelCase in the Base model class but it s not ideal.

Any help will be appreciated.

**Comment by rdhainaut** [comment]
A simple workaround consists to rename the property in lowerCamelCase in the Base model class.

**Comment by rdhainaut** [comment]
Sorry the issue do not concern OData/odata.net but is related to OData/Webapi (see https://github.com/OData/WebApi/issues/1784 )
