### ISSUE TITLE
ExecuteQuery() occasionally fails - how to improve logging?

### ISSUE THREAD

**Issue by BlairMcc** [OData/odata.net#1439]
ExecuteQuery occasionally fails instantly on basic queries, eg "?$top=10&$count=true"

### Assemblies affected

We are using Microsoft.Odata.Client, .Core, and .Edm v7.5.3

### Reproduce steps

Unable to reproduce, having to rely on logs so far

### Expected result

This issue to not happen occasionally

### Actual result

Instantaneous exception thrown in Microsoft.OData.Client.QueryResult.ExecuteQuery()

### Additional detail

Here is some information from our logs

```
9-04-02 09:18:37.6163 MyCompany.External.WebAPI.Filters.LogActionFilter DEBUG 4/2/2019 9:18:37 AM - OnActionExecuting: Controller: 'EntityPrices' Action: 'Get', Request Url: 'https://myclient-api-ci.MyCompany.com/EntityPrices?$top=10&$count=true'
2019-04-02 09:18:42.3039 MyCompany.External.WebAPI.Filters.LogActionFilter DEBUG 4/2/2019 9:18:42 AM - OnActionExecuting: Controller: 'EntityPrices' Action: 'Get', Request Url: 'https://myclient-api-ci.MyCompany.com/EntityPrices?$top=10&$count=true'
2019-04-02 09:18:42.3039 MyCompany.External.WebAPI.Filters.LogActionFilter DEBUG 4/2/2019 9:18:42 AM - OnActionExecuted: Controller: 'EntityPrices' Action: 'Get'
2019-04-02 09:18:42.3319 MyCompany.WebUI.Controllers.EntityPricingExtractController ERROR Microsoft.OData.Client.DataServiceQueryException: An error occurred while processing this request. ---> Microsoft.OData.Client.DataServiceClientException: {"error":{"code":"","message":"An error has occurred."}}
   at Microsoft.OData.Client.QueryResult.ExecuteQuery()
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   --- End of inner exception stack trace ---
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at MyCompany.WebUI.Controllers.EntityPricingExtractController.Search(EntityPricingViewModel viewModel, DataTableParamsViewModel serverParams, String& url, Int32& filteredCnt, Int32& totalCnt) in C:\TeamCity\buildAgent\work\648842038d393c00\WebProject\Controllers\Extracts\EntityPricingExtractController.cs:line 160
   at MyCompany.WebUI.Controllers.EntityPricingExtractController.Search(EntityPricingViewModel viewModel, DataTableParamsViewModel serverParams) in C:\TeamCity\buildAgent\work\648842038d393c00\WebProject\Controllers\Extracts\EntityPricingExtractController.cs:line 106
2019-04-02 09:18:42.3319 MyCompany.WebUI.Controllers.EntityPricingExtractController ERROR Microsoft.OData.Client.DataServiceClientException: {"error":{"code":"","message":"An error has occurred."}}
   at Microsoft.OData.Client.QueryResult.ExecuteQuery()
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
```

**Comment by ArchSerpo** [comment]
And this is the block of code that is executed that fails - 

`var uri = new Uri(ConfigurationManager.AppSettings["oDataUrl"]);
            var container = new Container(uri);
            container.Credentials = ODataHelper.GetCredentials(User.Identity.Name);

            var factEntityPrice =
                from p in container.EntityPrices.IncludeTotalCount() select p;

            if (serverParams != null)
            {
                //Get total count of records
                var totalQuery = (DataServiceQuery<EntityPrice>)factEntityPrice.Take(10);
                var totalResponse = (QueryOperationResponse<EntityPrice>)totalQuery.Execute();
                totalCnt = (int)totalResponse.TotalCount;
            }`

**Comment by KanishManuja-MS** [comment]
@ArchSerpo Can you check into what your log action filter does? If the framework were to support such filter, what kind of information would you like to see in the logs?
Are you able to debug your log filter, if yes then can you please share what information you have available then?

**Comment by ArchSerpo** [comment]
Hi @KanishManuja-MS,

I am hoping to see a full error log that can help us diagnose the error, more than "an error has occurred", similar to the one that is pasted here - https://github.com/OData/odata.net/issues/633

Our LogActionFilter overrides the System.Web.Http ActionFilterAttribute class to do some logging. Here is the log method for 'OnActionExecuted'. I can see some potential for improvement so will investigate that this morning, along with the QueryOperationResponse object

```
private void Log(string methodName, HttpActionExecutedContext context)
        {
            var controllerName = context.ActionContext.ControllerContext.ControllerDescriptor.ControllerName;
            var actionName = context.ActionContext.ActionDescriptor.ActionName;

            var message = $"{DateTime.Now} - {methodName}: Controller: '{controllerName}' Action: '{actionName}'";
            var statusCode = context?.Response?.StatusCode;
            if (statusCode != null)
            {
                message += $", Http status: '{statusCode.ToString()}'";
            }

            _log.Debug(message);

            if (statusCode != null && statusCode != HttpStatusCode.OK)
            {
                if(context?.Exception != null)
                    _log.Error($"Exception: '{context.Exception.Message}', Inner: '{context.Exception.InnerException}'");
            }
        }
```

I think I can see some improvements I could mae

**Comment by ArchSerpo** [comment]
Am now throwing an DataServiceQueryException if the response error is not null. Will report back once we see it again

```
                //Get total count of records
                var totalQuery = (DataServiceQuery<EntityPrice>)factEntityPrice.Take(10);
                var totalResponse = (QueryOperationResponse<EntityPrice>)totalQuery.Execute();
                if (totalResponse.Error != null)
                {
                    // TODO :: If this does generate the logs we're hoping for, turn this into a helper
                    throw new DataServiceQueryException("Search failed to execute", totalResponse.Error, totalResponse);
                }
```

**Comment by KenitoInc** [comment]
@BlairMcc Was this issue resolved?

**Comment by BlairMcc** [comment]
Hey @KenitoInc, this is too long ago to remember sorry, I hope you're able to find a resolution!

**Comment by KenitoInc** [comment]
Closing this issue
