### ISSUE TITLE
Deserialization of unknown c property fails with NullReferenceException

### ISSUE THREAD

**Issue by brjohnstmsft** [OData/odata.net#1510]
When `ODataMessageReaderSettings.ReadUntypedAsString` is set to `false`, deserialization of a resource with an undeclared non-empty collection property will fail with `NullReferenceException`, resulting in a useless error message for customers. The same happens when deserializing a complex collection of an abstract type where the resources in the collection are missing the `@odata.type` annotation.

### Assemblies affected

Microsoft.OData.Core 7.5.3, reproduced via Microsoft.AspNet.OData 7.1.0.

### Reproduce steps

Full repros available via these tests:

- Repro using a complex collection that's missing a type annotation: https://github.com/brjohnstmsft/odata-repros/blob/877c03fe8767cc4b808fa53b110f6a978b08bbd2/UnknownFieldErrorMessage/Repro/StaticallyTypedRepro.cs#L85
- Repros using a primitive collection property that is undeclared:
  - https://github.com/brjohnstmsft/odata-repros/blob/877c03fe8767cc4b808fa53b110f6a978b08bbd2/UnknownFieldErrorMessage/Repro/DynamicallyTypedRepro.cs#L56
  - https://github.com/brjohnstmsft/odata-repros/blob/877c03fe8767cc4b808fa53b110f6a978b08bbd2/UnknownFieldErrorMessage/Repro/DynamicallyTypedRepro.cs#L81

### Expected result

These cases should fail with a helpful error message that specifically names the property being deserialized, and what is wrong (either missing `@odata.type`, or the property is undeclared in the type).

### Actual result

A `NullReferenceException` is being thrown during deserialization, which is subsequently caught and turned into a very unhelpful error message, "Object reference is not set to an instance of an object."

Here is the stack trace of the nullref:

```
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceSetStart(ODataResourceSet resourceSet, SelectedPropertiesNode selectedProperties)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadNextNestedResourceInfoContentItemInRequest()
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtNestedResourceInfoStartImplementationSynchronously()
   at Microsoft.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataActionPayloadDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
   at Microsoft.AspNet.OData.Formatter.ODataInputFormatterHelper.ReadFromStream(Type type, Object defaultValue, IEdmModel model, Uri baseAddress, IWebApiRequestMessage internalRequest, Func`1 getODataRequestMessage, Func`2 getEdmTypeDeserializer, Func`2 getODataPayloadDeserializer, Func`1 getODataDeserializerContext, Action`1 registerForDisposeAction, Action`1 logErrorAction)
```

### Additional detail

I diagnosed this after many hours of debugging (very challenging with only release builds). The issue stems from behavior in a method called by `ODataJsonLightResourceDeserializer.InnerReadUndeclaredProperty`. When `ODataMessageReaderSettings.ReadUntypedAsString` is `true`, `InnerReadUndeclaredProperty` reads the property as untyped and returns null, which results in a better error message later on. When `ReadUntypedAsString` is `false`, `InnerReadUndeclaredProperty` somehow returns a nested resource info, which causes the JSON deserializer to make an incorrect state transition. It assumes that an upcoming primitive value is a resource (it can't be; there's no `StartObject` token!), causing the nullref.

Fixing either this issue, or [this related issue](https://github.com/OData/odata.net/issues/1372) is a high priority for Azure Search. We set `ReadUntypedAsString` to `false` as part of a workaround for issue #1372, so if that issue is fixed, we can at least avoid this one. However, this bug is egregious enough that it should be fixed regardless.

Customers make mistakes all the time with the names of properties in request payloads. It is a big driver of DSAT and creates support issues for us when they get "Object reference not set to an instance of an object" instead of a helpful error message that names the misspelled/undeclared/malformed property.

**Comment by mikepizzo** [comment]
OData library seems to be working correctly for reading untyped as value -- it will correctly read an undeclared collection of primitive or complex type as long as the ThrowOnUndeclaredPropertyForNonOpenType validation is not set and ReadUntypedAsString=false.

It is likely an issue in WebAPI that doesn't expect/know how to handle the unknown collection.
