### ISSUE TITLE
OData service fails in ASP.NET Core 2.2

### ISSUE THREAD

**Issue by weitzhandler** [OData/odata.net#1519]
As soon as we upgrade ASP.NET Core version from 2.1 to 2.2, the ex. method `routeBuilder.MapODataServiceRoute("odata", "odata", GetEdmModel());` throws the following exception:
> System.InvalidOperationException
HResult=0x80131509
Message=Cannot use 'Microsoft.AspNet.OData.Routing.ODataRoute' with Endpoint Routing.
Source=Microsoft.AspNetCore.Mvc.Core
StackTrace:
at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
at BookStore.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in D:\Users\Shimmy\Source\Repos\AspNetCore2\src\BookStore\BookStore\Startup.cs:line 45

Example of the code:

```c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
  /* ... */
  app.UseMvc(routeBuilder =>
  {
    // this line   
    routeBuilder.MapODataServiceRoute("odata", "odata", GetEdmModel());
  });
}

### Reproduce steps

https://github.com/weitzhandler/AspNetCore-1/tree/aspnetcore_2_2

### Expected result

Project fails on initialization

### Actual result

Exception thrown

**Comment by weitzhandler** [comment]
@hassanhabib gave me a good workaround, setting `EnableEndpointRouting` to `false`:

public void ConfigureServices(IServiceCollection services)
{
  /* ... */
  services.AddOData();

  services
    .AddMvc(options =>
      options.EnableEndpointRouting = false)
    .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
}

I'm gonna close this issue, hope I don't have to re-open it.
