### ISSUE TITLE
Exception if the entity has Equals and GetHashcode implementation

### ISSUE THREAD

**Issue by DarkGraySun** [OData/odata.net#1531]
I want to build a project with an OData interface. There exists a server and a client for this.
Server and client use an identical library of classes with which the exchange between server and client takes place (EDMModel). The problem arises when these classes (Entities) have the functions Equals and GetHashCode.
Then the client can not perform a successful update or add on the server.

### Assemblies affected
Microsoft.OData.Client 7.6.0

### Reproduce steps

The Client (DataserviceContext) uses an entity that implements "Equals" and "GetHashcode" by using the id (key) of the class.

The server receives the entity changes the id (store the entity in the database) and returns the entity with the changed id to the client.

Then the client gets an exception when receiving the response

### Expected result

The client gets no exception..

### Actual result

The client gets an exception.

Microsoft.OData.Client.DataServiceRequestException: An error occurred while processing this request. ---> System.InvalidOperationException: The context is already tracking a different entity with the same resource Uri.

Stacktrace:
 at Microsoft.OData.Client.EntityTracker.InternalAttachEntityDescriptor(EntityDescriptor entityDescriptorFromMaterializer, Boolean failIfDuplicated)
   at Microsoft.OData.Client.AtomMaterializerLog.ApplyToContext()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
   at Microsoft.OData.Client.BaseSaveResult.MaterializeResponse(EntityDescriptor entityDescriptor, ResponseInfo responseInfo, String etag)
   at Microsoft.OData.Client.BaseSaveResult.HandleResponsePost(EntityDescriptor entityDescriptor, String etag)
   at Microsoft.OData.Client.BaseSaveResult.HandleResponsePost(Descriptor descriptor, HeaderCollection contentHeaders)
   at Microsoft.OData.Client.SaveResult.HandleResponse()
   --- End of inner exception stack trace ---
   at Microsoft.OData.Client.SaveResult.HandleResponse()
   at Microsoft.OData.Client.BaseSaveResult.EndRequest()
   at Microsoft.OData.Client.DataServiceContext.EndSaveChanges(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TestClient.Program.AddObject() in 
Program.cs:line 34
   at TestClient.Program.Main(String[] args) in 
Program.cs:line 17
---> (Inner Exception #0) Microsoft.OData.Client.DataServiceRequestException: An error occurred while processing this request. ---> System.InvalidOperationException: The context is already tracking a different entity with the same resource Uri.
   at Microsoft.OData.Client.EntityTracker.InternalAttachEntityDescriptor(EntityDescriptor entityDescriptorFromMaterializer, Boolean failIfDuplicated)
   at Microsoft.OData.Client.AtomMaterializerLog.ApplyToContext()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
   at Microsoft.OData.Client.BaseSaveResult.MaterializeResponse(EntityDescriptor entityDescriptor, ResponseInfo responseInfo, String etag)
   at Microsoft.OData.Client.BaseSaveResult.HandleResponsePost(EntityDescriptor entityDescriptor, String etag)
   at Microsoft.OData.Client.BaseSaveResult.HandleResponsePost(Descriptor descriptor, HeaderCollection contentHeaders)
   at Microsoft.OData.Client.SaveResult.HandleResponse()
   --- End of inner exception stack trace ---
   at Microsoft.OData.Client.SaveResult.HandleResponse()
   at Microsoft.OData.Client.BaseSaveResult.EndRequest()
   at Microsoft.OData.Client.DataServiceContext.EndSaveChanges(IAsyncResult asyncResult)
### Additional detail

It is interesting that the entity in the client is updated to the server values, although an exception occurred.
A complete example project to reproduce the error:
[TestProject.zip](https://github.com/OData/odata.net/files/3565705/TestProject.zip)

**Comment by ElizabethOkerio** [comment]
Hey @DarkGraySun, try implementing the Equals and GetHashCode() methods from the IEqualityComparer<T> interfaces as we look more into the issue. In your case from the sample project, this will be: 

using System;
using System.Collections.Generic;

namespace TransferObject
{
    [Microsoft.OData.Client.Key(nameof(Id))]
    public class ExampleObject : IEqualityComparer<ExampleObject>
    {
        public int Id { get; set; }
        public bool Equals(ExampleObject x, ExampleObject y)
        {
            return x.Id == y.Id;
        }
        public int GetHashCode(ExampleObject obj)
        {
            return obj.Id.GetHashCode();
        }
    }
}

**Comment by ElizabethOkerio** [comment]
Hey @DarkGraySun , you can reopen this issue if the workaround I provided you did not solve the issue. Thanks.

**Comment by hennyjoh** [comment]
Hi, I would very much like to reopen this issue.
Not being able to implement GetHashCode() on my entity objects is not a good solution.
The EntityTracker is supposed to track object instances, as I understand, so being dependent on a GetHashCode() implementation which change value when properties on an object change is not good.

Can't you please use an object instance equality comparer in the EntityTracker?
Source: https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Client/EntityTracker.cs    Line 31/34

This is an Object instance equality comparer that seems to work nicely for me:

    public class ReferenceEqualityComparer<TObject> : IEqualityComparer<TObject> where TObject : class
    {
        public static ReferenceEqualityComparer<TObject> Instance = new ReferenceEqualityComparer<TObject>();

        private ReferenceEqualityComparer() { }

        public bool Equals(TObject x, TObject y) => ReferenceEquals(x, y);

        public int GetHashCode(TObject obj) => System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(obj);
    }
