### ISSUE TITLE
ToTypeReference error when validating a resource for a resource set

### ISSUE THREAD

**Issue by KanishManuja-MS** [OData/odata.net#1566]
If the scope does not have an expected type, an attempt to call an extension method on a null object may result. (TBV) 

https://github.com/OData/odata.net/blob/fb0fb18332edfe2d6f4372287984bdc0ff7402ec/src/Microsoft.OData.Core/TypeNameOracle.cs#L94

### Assemblies affected

ODL 7.6.1

### Reproduce steps
Try to serialize a resource that does not exist in the schema. 

### Expected result

A better error message should be written out. 

### Actual result

  "error": {
    "code": "BadRequest",
    "message": "An internal error 'EdmLibraryExtensions_ToTypeReference' occurred.",
    "innerError": {
      "request-id": "76fe1a15-6bfa-42fd-865a-49ea8cda4a88",
      "date": "2019-10-10T12:57:29"
    }

   at Microsoft.OData.Metadata.EdmLibraryExtensions.ToTypeReference(IEdmType type, Boolean nullable)
   at Microsoft.OData.TypeNameOracle.ResolveAndValidateTypeFromTypeName(IEdmModel model, IEdmStructuredType expectedType, String typeName, IWriterValidator writerValidator)
   at Microsoft.OData.ODataWriterCore.ValidateResourceForResourceSet(ODataResourceBase resource, ResourceBaseScope resourceScope)
   at Microsoft.OData.ODataWriterCore.<>c__DisplayClass121_0.<WriteStartResourceImplementation>b__0()
   at Microsoft.OData.ODataWriterCore.InterceptException(Action action)
   at Microsoft.OData.ODataWriterCore.WriteStartResourceImplementation(ODataResource resource)

**Comment by p6345uk** [comment]
You manage to get anywhere with this?
