### ISSUE TITLE
IN operator fails on strings with commas in them

### ISSUE THREAD

**Issue by kenneth-hansen** [OData/odata.net#1623]
ODataUriParser.ParseFilter throws if any of the IN operator's string parameters contains commas.

### Assemblies affected

7.6.2 (but probably all versions)

### Reproduce steps

Just create a filter ala: "?$filter=propertyName in ('a','x,y,z')"

### Expected result

Should parse normally.

### Actual result

ODataUriParser.ParseFilter throws an exception.

Microsoft.OData.ODataException
  HResult=0x80131509
  Message=String item should be single/double quoted: ''x'.
  Source=Microsoft.OData.Core
  StackTrace:
   at Microsoft.OData.UriParser.InBinder.NormalizeStringItem(String str)
   at Microsoft.OData.UriParser.InBinder.NormalizeCollectionItems(String bracketLiteralText, NormalizeFunction normalizeFunc)
   at Microsoft.OData.UriParser.InBinder.GetCollectionOperandFromToken(QueryToken queryToken, IEdmTypeReference expectedType, IEdmModel model)
   at Microsoft.OData.UriParser.InBinder.BindInOperator(InToken inToken, BindingState state)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()

### Additional detail

Problem seems to be in: https://github.com/OData/odata.net/blob/2cf5247da1fde1bfde63d3daf8acdd56ec8a156e/src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs#L142
It splits on comma with no regard to whether it is inside a string or not

The line that throws:
https://github.com/OData/odata.net/blob/2cf5247da1fde1bfde63d3daf8acdd56ec8a156e/src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs#L178

**Comment by xuzhg** [comment]
Fixed and merged. Thanks.
