### ISSUE TITLE
Failure when parsing OData function with $expand AND $filter

### ISSUE THREAD

**Issue by ksikorsk** [OData/odata.net#1667]
Exception thrown when parsing a URI for a OData `Function` with `$expand` and `$filter` statemenets.
I.E. `~/messages/delta?$expand=singleValueExtendedProperties($filter=id eq 'value')`

where delta is a function that returns a collection:
```xml
<EntityType Name="mailFolder" BaseType="graph.entity">
  <NavigationProperty Name="messages" Type="Collection(graph.message)" ContainsTarget="true"/>
</EntityType>
<EntityType Name="message" BaseType="graph.outlookItem" OpenType="true">
  <NavigationProperty Name="singleValueExtendedProperties" Type="Collection(graph.singleValueLegacyExtendedProperty)" ContainsTarget="true"/>
  <NavigationProperty Name="multiValueExtendedProperties" Type="Collection(graph.multiValueLegacyExtendedProperty)" ContainsTarget="true"/>
</EntityType>
<EntityType Name="singleValueLegacyExtendedProperty" BaseType="graph.entity">
  <Property Name="value" Type="Edm.String"/>
</EntityType>
<Function Name="delta" IsBound="true">
  <Parameter Name="bindingparameter" Type="Collection(Microsoft.OutlookServices.message)" />
  <ReturnType Type="Collection(Microsoft.OutlookServices.message)" Nullable="false" />
</Function>
```

### Assemblies affected

OData .Net lib 7.6.3

### Reproduce steps

GET [https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/delta?$expand=singleValueExtendedProperties($filter=id eq 'value')](https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/delta?$expand=singleValueExtendedProperties($filter=id%20eq%20%27value%27))

### Expected result

The URI to be parsed and sent over to workload.

### Actual result

AGS fails when parsing the URI, and the workload is never reached.

Exception:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: initialState
   at Microsoft.OData.ExceptionUtils.CheckArgumentNotNull[T](T value, String parameterName)
   at Microsoft.OData.UriParser.MetadataBinder..ctor(BindingState initialState)
   at Microsoft.OData.UriParser.SelectExpandBinder.BindFilter(QueryToken filterToken, IEdmNavigationSource navigationSource, IEdmTypeReference elementType, HashSet`1 generatedProperties, Boolean collapsed)
   at Microsoft.OData.UriParser.SelectExpandBinder.GenerateExpandItem(ExpandTermToken tokenIn)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.OData.UriParser.SelectExpandBinder.Bind(ExpandToken expandToken, SelectToken selectToken)
   at Microsoft.OData.UriParser.SelectExpandSemanticBinder.Bind(ODataPathInfo odataPathInfo, ExpandToken expandToken, SelectToken selectToken, ODataUriParserConfiguration configuration, BindingState state)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpandImplementation(String select, String expand, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpand()
   at Microsoft.Online.AggregatorService.Controller.ParserEngine.ParseAndExpand(RequestContext context, ODataUriParser parser, ParsedRequestState state) in C:\Dev\AGS-AggregatorService\src\dev\Controller\Parser\ParserEngine.cs:line 1294
```

### Additional info

**Note:** that this works when being applied directly on the entity collection or without the `$filter` clause.  I.E. the following requests work (forward the request to the exchange workload):
- GET https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$expand=singleValueExtendedProperties
- GET [https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$expand=singleValueExtendedProperties($filter=id eq 'value')](https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$expand=singleValueExtendedProperties($filter=id%20eq%20%27value%27))
- GET https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/delta?$expand=singleValueExtendedProperties

**Comment by odero** [comment]
Related https://github.com/OData/odata.net/issues/1324

**Comment by iriszhou320** [comment]
@gathogojr hey we have encountered the same issue, where expanding singleExtendedProperties is not supported using delta, but this is a key feature for our implementation. any progress on it?

**Comment by ksikorsk** [comment]
There is a suggested mitigation here: https://github.com/OData/odata.net/issues/1162

**Comment by iriszhou320** [comment]
@ksikorsk yes thanks for the ping! still a bit confused how we can add the entitySetPath to the step of just simply calling the url? like GET https://graph.microsoft.com/v1.0/me/drive/root/delta?$expand=microsoft.graph.driveItem/children($filter=id eq ‘x’)
