### ISSUE TITLE
Parsing OData case() functions

### ISSUE THREAD

**Issue by erdomke** [OData/odata.net#1673]
I am trying to parse a [case function](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_case) using the Microsoft.OData.Core library (v7.6.3.0). However, I keep getting an exception as outlined below. Based on the exception, it appears that parsing such functions is not supported. However, I cannot find documentation confirming this. In general, is there documentation anywhere regarding which portions of the spec are/aren't currently supported? Is there a roadmap describing when unsupported features will be implemented?

### Assemblies affected

- Microsoft.OData.Core (v7.6.3.0)

### Reproduce steps

```csharp
var modelXml = @"<edmx:Edmx Version='4.0' xmlns:edmx='http://docs.oasis-open.org/odata/ns/edmx'>
  <edmx:DataServices>
    <Schema Namespace='ns' xmlns='http://docs.oasis-open.org/odata/ns/edm'>
      <EntityType Name='app'>
        <Key>
          <PropertyRef Name='id' />
        </Key>
        <Property Name='generation' Type='Edm.Int32' />
        <Property Name='id' Type='Edm.String' Nullable='false' />
      </EntityType>
      <EntityContainer Name='Container'>
        <EntitySet Name='app' EntityType='ns.app' />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";

var model = default(IEdmModel);
using (var reader = new StringReader(modelXml))
using (var xml = XmlReader.Create(reader))
{
    model = CsdlReader.Parse(xml);
}

var baseUri = new Uri("http://example.com/odata/");
var fullUri = new Uri(baseUri, $"app?$compute={Uri.EscapeDataString("case(generation gt 0:1,generation lt 0:-1,true:0)")} as col");
var parser = new ODataUriParser(model, baseUri, fullUri)
{
    Resolver = new ODataUriResolver { EnableCaseInsensitive = true }
};
var compute = parser.ParseCompute();
```

### Expected result

A valid parse tree stored in the `compute` variable

### Actual result

```
Microsoft.OData.ODataException: ')' or ',' expected at position 38 in 'case(generation gt 0:1,generation lt 0:-1,true:0) as col'.
   at Microsoft.OData.UriParser.FunctionCallParser.ParseArgumentListOrEntityKeyList(Action restoreAction)
   at Microsoft.OData.UriParser.FunctionCallParser.TryParseIdentifierAsFunction(QueryToken parent, QueryToken& result)
   at Microsoft.OData.UriParser.IdentifierTokenizer.ParseIdentifier(QueryToken parent)
   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParsePrimaryStart()
   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParsePrimary()
   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseUnary()
   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseMultiplicative()
   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseAdditive()
   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseComparison()
   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseLogicalAnd()
   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseLogicalOr()
   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseExpression()
   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseComputeExpression()
   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseCompute(String compute)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseComputeImplementation(String compute, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseCompute()
   at Microsoft.OData.UriParser.ODataUriParser.ParseCompute()
```

**Comment by habbes** [comment]
Hi @erdomike. Thanks for reporting this.

Here is [a roadmap](https://docs.microsoft.com/en-us/odata/resources/roadmap) that shows which features of the spec are supported in the OData core library as well as the WebApi library. However, the `case` function is not currently mentioned on that list.

**Comment by erdomke** [comment]
@habbes Thanks for the update and the link to the roadmap.

**Comment by GennadyGS** [comment]
It is really very useful function. Do not event see the alternative way to implement conditional logic for general case.

**Comment by Jollarvia** [comment]
It's 2024 and I still want this.

**Comment by RomanSlesarev** [comment]
How's it even possible that such usefull function is not supported yet? It's been 4 years!

**Comment by Xriuk** [comment]
After 4 years no updates or plans on this?

**Comment by xuzhg** [comment]
It's enabled in 9.x

**Comment by xuzhg** [comment]
See: https://github.com/OData/odata.net/pull/3496
