### ISSUE TITLE
Expand does not work with an instance contining lore than 1 item to expand

### ISSUE THREAD

**Issue by brice-fromentin** [OData/odata.net#1716]
I have a application that loads an instance of a object with its children using expand and the selection via key.

I am running 7.4.0 beta on .NET 5.0 preview

When there is is one child, ex : 

Request URL: http://localhost:7121/api/odata/Utilisateurs(6ab447ba-bfb8-4c4f-a60b-66fdb3ea9bb2)?$expand=Service

Controller :

        [EnableQuery]
        [ODataRoute("utilisateurs")]
        public IQueryable<Utilisateur> Get()
        {
            return dbContext.Utilisateur;
        }

        [EnableQuery]
        [ODataRoute("utilisateurs({key})")]
        public SingleResult<Utilisateur> Get([FromODataUri] Guid key)
        {
            var result = dbContext.Utilisateur.Where(p => p.Id == key);
            return SingleResult.Create(result);
        }

Response

@odata.context: "http://localhost:7121/api/odata/$metadata#Utilisateurs(Service())/$entity",…}
@odata.context: "http://localhost:7121/api/odata/$metadata#Utilisateurs(Service())/$entity"
Id: "6ab447ba-bfb8-4c4f-a60b-66fdb3ea9bb2"
DateCreation: "2020-03-24T09:49:30+01:00"
UtilisateurCreation: null
Modification: null
UtilisateurModification: null
Login: "admin"
MotDePasse: "xxx="
EstBloque: false
DoitReinitialiser: false
DateDebutMotDePasse: null
DureeMotDePasse: null
Prenom: "Brice"
Prenom2: "Cyrille"
Prenom3: null
Nom: "FROMENTIN"
Mel: "brice.fromentin@xxx.com"
Telephone: null
Fax: null
DateDebutValidite: null
DureeValidite: null
IdService: "436d6dc0-18c3-4ac1-bb3f-4d26f3c0bb31"
Service: {Id: "436d6dc0-18c3-4ac1-bb3f-4d26f3c0bb31", DateCreation: "2020-03-24T11:43:26.793+01:00",…}
Id: "436d6dc0-18c3-4ac1-bb3f-4d26f3c0bb31"
DateCreation: "2020-03-24T11:43:26.793+01:00"
UtilisateurCreation: null
Modification: null
UtilisateurModification: null
Nom: "JOHN"

----------------------------------------------------------------------------------------------Case 2

Request URL: http://localhost:7121/api/odata/Collectivites(975252f9-fce6-443d-91f9-77c697e71f05)?$expand=CollectiviteTypeOperations

Controller ::

        [EnableQuery]
        [ODataRoute("collectivites")]
        public IQueryable<Collectivite> Get()
        {
            return dbContext.Collectivite;
        }

        [EnableQuery]
        [ODataRoute("collectivites({key})")]
        public SingleResult<Collectivite> Get([FromODataUri] Guid key)
        {
            var result = dbContext.Collectivite.Where(p => p.Id == key);
            return SingleResult.Create(result);
        }

Response ::

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.CreatePropertyAccessExpression(Expression target, IProperty property)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.RewriteNullEquality(Boolean equality, IEntityType entityType, Expression nonNullExpression, INavigation lastNavigation)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.RewriteNullEquality(Boolean equality, IEntityType entityType, Expression nonNullExpression, INavigation lastNavigation)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.RewriteEquality(Boolean equality, Expression left, Expression right)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitConditional(ConditionalExpression conditionalExpression)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.<VisitMemberInit>g__VisitMemberBindings|9_0(ReadOnlyCollection`1 bindings)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.<VisitMemberInit>g__VisitMemberBindings|9_0(ReadOnlyCollection`1 bindings)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.RewriteAndVisitLambda(LambdaExpression lambda, EntityReferenceExpression source)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitSelectMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.Rewrite(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.IEnumerable.GetEnumerator()
   at Microsoft.AspNet.OData.EnableQueryAttribute.SingleOrDefault(IQueryable queryable, IWebApiActionDescriptor actionDescriptor)
   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)
   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)
   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json, application/xml, application/text
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Host: localhost:7121
Referer: http://localhost:7120/administration/collectivites
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
prefer: return=representation
Sec-Fetch-Dest: empty
Origin: http://localhost:7120
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors

**Comment by brice-fromentin** [comment]
I include also the datamodel ::

// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Kairos.Models.Entities
{
    public partial class Collectivite
    {
        public Collectivite()
        {
            CollectiviteTypeOperations = new HashSet<CollectiviteTypeOperation>();
        }

        [Key]
        public Guid Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreation { get; set; }
        public Guid UtilisateurCreation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Modification { get; set; }
        public Guid? UtilisateurModification { get; set; }
        [Required]
        [StringLength(64)]
        public string Nom { get; set; }
        [StringLength(64)]
        public string Designation { get; set; }
        [Required]
        [StringLength(6)]
        public string Code { get; set; }
        [Required]
        [StringLength(3)]
        public string CodeTresorie { get; set; }
        [Required]
        [StringLength(3)]
        public string Departement { get; set; }
        public Guid? IdAdresse { get; set; }
        public bool TiersMultiCollectivite { get; set; }
        public bool ExistenceCodeAnalytique { get; set; }
        public bool ExistenceCodeGeographique { get; set; }
        [Required]
        [Column("ControlePES")]
        public bool? ControlePes { get; set; }
        public short ControleDoublonTiers { get; set; }

        [InverseProperty(nameof(CollectiviteTypeOperation.Collectivite))]
        public virtual ICollection<CollectiviteTypeOperation> CollectiviteTypeOperations { get; set; }
    }
}
------------------------------------------------------------------------------------
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Kairos.Models.Entities
{
    public partial class Collectivite
    {
        public Collectivite()
        {
            CollectiviteTypeOperations = new HashSet<CollectiviteTypeOperation>();
        }

        [Key]
        public Guid Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreation { get; set; }
        public Guid UtilisateurCreation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Modification { get; set; }
        public Guid? UtilisateurModification { get; set; }
        [Required]
        [StringLength(64)]
        public string Nom { get; set; }
        [StringLength(64)]
        public string Designation { get; set; }
        [Required]
        [StringLength(6)]
        public string Code { get; set; }
        [Required]
        [StringLength(3)]
        public string CodeTresorie { get; set; }
        [Required]
        [StringLength(3)]
        public string Departement { get; set; }
        public Guid? IdAdresse { get; set; }
        public bool TiersMultiCollectivite { get; set; }
        public bool ExistenceCodeAnalytique { get; set; }
        public bool ExistenceCodeGeographique { get; set; }
        [Required]
        [Column("ControlePES")]
        public bool? ControlePes { get; set; }
        public short ControleDoublonTiers { get; set; }

        [InverseProperty(nameof(CollectiviteTypeOperation.Collectivite))]
        public virtual ICollection<CollectiviteTypeOperation> CollectiviteTypeOperations { get; set; }
    }
}
-------------------------------------------------------------------------------------------------
    public partial class Utilisateur
    {
        public Utilisateur()
        {
            UtilisateurGroupes = new HashSet<UtilisateurGroupe>();
        }

        [Key]
        public Guid Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreation { get; set; }
        public Guid? UtilisateurCreation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Modification { get; set; }
        public Guid? UtilisateurModification { get; set; }
        [Required]
        [StringLength(256)]
        public string Login { get; set; }
        [Required]
        [MaxLength(32)]
        public byte[] MotDePasse { get; set; }
        public bool EstBloque { get; set; }
        public bool DoitReinitialiser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateDebutMotDePasse { get; set; }
        public short? DureeMotDePasse { get; set; }
        [Required]
        [StringLength(32)]
        public string Prenom { get; set; }
        [StringLength(32)]
        public string Prenom2 { get; set; }
        [StringLength(32)]
        public string Prenom3 { get; set; }
        [Required]
        [StringLength(64)]
        public string Nom { get; set; }
        [Required]
        [StringLength(256)]
        public string Mel { get; set; }
        [StringLength(20)]
        public string Telephone { get; set; }
        [StringLength(20)]
        public string Fax { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateDebutValidite { get; set; }
        public short? DureeValidite { get; set; }
        public Guid? IdService { get; set; }

        [ForeignKey(nameof(IdService))]
        [InverseProperty("Utilisateurs")]
        public virtual Service Service { get; set; }
        [InverseProperty(nameof(UtilisateurGroupe.Utilisateur))]
        public virtual ICollection<UtilisateurGroupe> UtilisateurGroupes { get; set; }
    }
}
-------------------------------------------------------------------------------------------
  public partial class Service
    {
        public Service()
        {
            Utilisateurs = new HashSet<Utilisateur>();
        }

        [Key]
        public Guid Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreation { get; set; }
        public Guid? UtilisateurCreation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Modification { get; set; }
        public Guid? UtilisateurModification { get; set; }
        [Required]
        [StringLength(64)]
        public string Nom { get; set; }

        [InverseProperty(nameof(Utilisateur.Service))]
        public virtual ICollection<Utilisateur> Utilisateurs { get; set; }
    }

**Comment by brice-fromentin** [comment]
Another difference if the direction of the Navigation property to expand.
