### ISSUE TITLE
Exception when serializing open type with undeclared property

### ISSUE THREAD

**Issue by gathogojr** [OData/odata.net#1726]
A bug exists in OData client library where open types `IsOpen` property get initialized `false` specifically **in a Post scenario where no query operation to the service has been done prior**. This later causes an exception to be thrown during serialization since the owning type isn't recognized as open and the undeclared property won't also be interpreted as an open property. This bug had been dissected by a user back in 2017 but the [issue](https://github.com/OData/odata.net/issues/272#issuecomment-284971690) had been closed with a **not-fixed** label.

### Assemblies affected
Microsoft.OData.Client 7.6.4

### Reproduce steps

1. Create an OData V4 service with an open type and a controller

**Product** class
```
public class Product
{
    [Key]
    public int Id { get; set; }
    public string Name { get; set; }
    public IDictionary<string, object> DynamicProperties { get; set; }
}
```

**ProductsController**
```
[ApiController]
[Route("[controller]")]
public class ProductsController : ControllerBase
{
    [EnableQuery]
    public IQueryable<Product> Get()
    {
        return new[] { new Product { Id = 1, Name = "Product 1" } }.AsQueryable();
    }

    [EnableQuery]
    public SingleResult<Product> Get([FromODataUri]int key)
    {
        return SingleResult.Create(new[] { new Product { Id = key, Name = "Product " + key } }.AsQueryable());
    }

    public async Task<IActionResult> Post([FromBody]Product product)
    {
        await Task.Run(() =>
        {
            // ...            
        });

        return Created(new Uri($"{Request.Scheme}://{Request.Host}{Request.Path}/{product.Id}", UriKind.Absolute), product);
    }
}
```

2. Create an OData client
3. Add a Connected Service to the client using OData Connected Service extension, making use of service endpoint for the OData service created in step 1
4. Add code to perform a post operation, making sure NOT to include any code that does any query operation to the service. Also add an undeclared property to the post payload - one way to achieve this is by riding on the `OnEntryStarting` hook supported by client, as shown below:

```
static void Main(string[] args)
{
    var serviceUri = new Uri("<ServiceEndpoint>");
    var context = new Default.Container(serviceUri);

    var product = new Product
    {
        Id = 99,
        Name = "Product 99"
    };

    context.Configurations.RequestPipeline.OnEntryStarting(args =>
    {
        if (product.GetType().IsAssignableFrom(args.Entity.GetType()))
        {
            List<ODataProperty> entryProperties = args.Entry.Properties as List<ODataProperty>;
            entryProperties.Add(new ODataProperty
            {
                Name = "SalesDescription",
                Value = new ODataPrimitiveValue("Product 99 sales description")
            });
        }
    });

    context.AddToProducts(product);
    context.SaveChangesAsync(SaveChangesOptions.None).Wait();
}
```
Repro https://github.com/gathogojr/ODataNetIssue1726Repro01

### Expected result
The undeclared property should be properly serialized an open property and interpreted as a dynamic property

### Actual result
An exception is thrown:
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (An error occurred while processing this request.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Ex016.Client.Program.Main(String[] args) in C:\Users\jogathog\Projects\Ex016\Ex016.Client\Program.cs:line 38

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
DataServiceRequestException: An error occurred while processing this request.

Inner Exception 2:
DataServiceClientException: The property 'SalesDescription' does not exist on type 'Ex016.Models.Product'. Make sure to only use property names that are defined by the type or mark the type as open type.

Inner Exception 3:
ODataException: The property 'SalesDescription' does not exist on type 'Ex016.Models.Product'. Make sure to only use property names that are defined by the type or mark the type as open type.
```
The 3rd inner exception makes it obvious that the type is not being identified as an open type. Digging deeper, the exception is traced to this [line](https://github.com/OData/odata.net/blob/3e02e30fcfde6bcf2694bfa8d8e52acf8e58b68c/src/Microsoft.OData.Core/WriterValidationUtils.cs#L117) in ODL where validation that a property is defined is done.

### Additional detail
This bug seems to have been introduced in a [contribution or bug fix](https://github.com/OData/odata.net/pull/161/files) back in 2015 where a user added logic in `TypeResolver` class to [populate](https://github.com/OData/odata.net/blob/3e02e30fcfde6bcf2694bfa8d8e52acf8e58b68c/src/Microsoft.OData.Client/TypeResolver.cs#L64) `ClientEdmModel`'s `EdmStructuredSchemaElements` dictionary property from the service model. The issue is that for a Post scenario, the `EdmStructuredSchemaElements` property is [made use of](https://github.com/OData/odata.net/blob/3e02e30fcfde6bcf2694bfa8d8e52acf8e58b68c/src/Microsoft.OData.Client/ClientEdmModel.cs#L420) before the dictionary populated and all types end up being assigned a default `IsOpen` property value of `false`

**Comment by gathogojr** [comment]
Issue fixed by #1727
