### ISSUE TITLE
OData V4 client doesn't work with function collection return types

### ISSUE THREAD

**Issue by Kalonjelen** [OData/odata.net#174]
Good day.

I'm attempting to create a function on my service that returns a collection - specifically, a dictionary. This itself has been problematic but I've managed to get it to work using OdataConventionModelBuilder.Function.Returns<Dictionary<string,string>>(), essentially.

I'm able to generate a client using OData V4, 6.11. When I call my function, I get the following error:

Object reference not set to an instance of an object.

   at Microsoft.OData.Client.Materialization.ODataItemExtensions.GetMaterializedValueCore(ODataAnnotatable annotatableObject)
   at Microsoft.OData.Client.Materialization.ODataItemExtensions.GetMaterializedValue(ODataComplexValue complexValue)
   at Microsoft.OData.Client.Materialization.ODataPropertyMaterializer.ReadWithExpectedType(IEdmTypeReference expectedClientType, IEdmTypeReference expectedReaderType)
   at Microsoft.OData.Client.Materialization.ODataMessageReaderMaterializer.ReadImplementation()
   at Microsoft.OData.Client.Materialization.ODataMaterializer.Read()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__b1`1.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.OData.Client.DataServiceQuerySingle`1.GetValue()

There are other issues with the client generating code that I"d like to address some other time, but this is the main one that's blocking us.

**Comment by karataliu** [comment]
@Kalonjelen  Can you parse the payload captured by some tool such as Fiddler here? We'd like to see what does the payload looks that thus determine whether it is a client issue.

**Comment by habbes** [comment]
Closing this issue due to inactivity. If it still affects latest versions of the library, kindly open a new issue.
