### ISSUE TITLE
ComplexType which contains property "ID" might be considered as EntityType on client side

### ISSUE THREAD

**Issue by LaylaLiu** [OData/odata.net#177]
Repro:
Define a function which returns a collection of complex type. This complex type contains a property named "ID".

On client side, it will fail to call this function. Error info is like "The context URI  references the type 'Collection(complextype)'; however the expected type is 'complextype'."

**Comment by fazzamar** [comment]
This issue also presents when an EntityType has a property of a complex type that has a property with the name "ID" or <complextypename> + "ID".

Rather than searching for a property that might be a key based on the property's name to determine if a class is an entity type, why not check if the class inherits from BaseEntityType. If it's possible for a class to be an 'entity' without inheriting from BaseEntityType, then perhaps change ClientTypeUtil.TypeOrElementTypeIsEntity to check for the KeyKind of the keys and only say it's an entity if it's an AttributedKey key. To facilitate this check, perhaps changed the return of GetKeyPropertiesOnType to return a Dictionary<PropertyInfo, KeyKind> or maybe a Tuple<PropertyInfo, KeyKind>[].

**Comment by GWigWam** [comment]
I have a similar issue. In my code there is a function which returns an object (**OParent**) which has a collection of **OChild** objects. Neither of these objects is of 'entity type', they are only used by this procedure.

Function definition: `myODataConventionModelBuilder.Function("TestFunc").Returns<OParent>();`

Object model:

    public class OParent
    {
        public OChild[] ItemList { get; set; }

        public OParent()
        {
            ItemList = new OChild[0];
        }
    }

    public class OChild
    {
        // the culprit
        public Guid ID { get; set; }
    }

When I call the function on my client (using a T4-generated client):

    var res = await Container.TestFunc().GetValueAsync();

 the service sends a response after which the ODataClient code throws an `InvalidOperationException`:

    The property 'ItemList' is of entity type and it cannot be a property of the type 'Test.OParent', which is not of entity type.  Only entity types can contain navigation properties.
    at Microsoft.OData.Client.ClientEdmModel.CreateEdmProperty(IEdmStructuredType declaringType, PropertyInfo propertyInfo)
    at Microsoft.OData.Client.ClientEdmModel.<>c__DisplayClass19.<GetOrCreateEdmTypeInternal>b__13(EdmComplexTypeWithDelayLoadedProperties complexType)
    at Microsoft.OData.Client.Providers.EdmComplexTypeWithDelayLoadedProperties.EnsurePropertyLoaded()

When I rename the `ID` property to anything else and re-generate my client code everything runs fine. It would be great if you could fix this because it is seriously strange behavior and also a nightmare to debug if you get this error.

**Comment by pharophy** [comment]
I found that this is relevant even if a properties name is "UniqueID" it still considers the class to be of entity type.  Very frustrating.  Thank you for this answer!

**Comment by ElizabethOkerio** [comment]
If a type has a property called <code> ID </code> or <code>TypeName+ID</code> it is automatically considered an entity type. I think this is by design. @gathogojr.

**Comment by habbes** [comment]
> If a type has a property called ` ID ` or `TypeName+ID` it is automatically considered an entity type. I think this is by design. @gathogojr.

In the case where the name is `UniqueID`, this sounds like a bug. This also doesn't seem very robust since a key might have a name other than `ID`. I think we should look into this.

**Comment by habbes** [comment]
Added to backlog: 1848274
