### ISSUE TITLE
OData Client and OData Core Lib doesn't fully support Enum as Key.

### ISSUE THREAD

**Issue by LaylaLiu** [OData/odata.net#180]
Repro: Auto-computed Id Link in ODL doesn't support Enum as Key.

Stack Trace:
[Exception] Microsoft.OData.Core.ODataException: The property 'CorrespondenceAction' on type 'Microsoft.Dynamics.DataEntities.ApplicationBookmark' is a non-primitive value. All key and etag properties must be of primitive types.
   at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.GetPrimitivePropertyClrValue(String entityTypeName, ODataProperty property, Boolean isKeyProperty)
   at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.GetPrimitivePropertyClrValue(ODataEntry entry, String propertyName, String entityTypeName, Boolean isKeyProperty)
   at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.ODataEntryMetadataContextWithModel.<get_KeyProperties>b__d(IEdmStructuralProperty p)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.ODataEntryMetadataContextWithModel.get_KeyProperties()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.get_ComputedKeyProperties()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeId()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeAndCacheId()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeEditLink()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.GetEditLink()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.GetReadLink()

**Comment by karataliu** [comment]
Current issues:
1. Auto-computed id doesn't support enum as key.
2. Client doesn't support enum as key.

**Comment by LaylaLiu** [comment]
Auto-computed id part has been fixed by https://github.com/OData/odata.net/commit/a40ff41efa0dd0a18fdda40ee256fc18913ece53

**Comment by ss-bjohnson** [comment]
Our team is having problems with this issue as well.  The client cannot successfully materialize entities that have enums as keys.  Currently the only workaround we have for this issue is to declare the types as int32 in the data model and then do type conversion code on the client.  Is there any plan to add support for enum keys on the client in version 6?

**Comment by rmava** [comment]
Our team is having problems with this as well.
We have a large system with many many tables and enum fields.
Currently having to custom build the mappings to avoid the issue but it is adding significant overhead to development.

**Comment by abhijitChodankar** [comment]
Our team is also having the problem for the enum fields. We have large number of entities which has enum values.

**Comment by Oleg-Tamarintsev** [comment]
+1 Problem still exists

**Comment by mpgalli** [comment]
+1 Problem still exists have you any suggestion to solve?

**Comment by ijensen808** [comment]
+1 This is going to be an ongoing issue for many customer integrations with Microsoft Dynamics 365 for Finance and Operations; I anticipate the visibility and traffic on this will only increase as customers start running into this issue with their OData endpoints.  Please resolve.

**Comment by jwinkeler74** [comment]
+1 Trying to query the LogisticsAddressState entity in D365FO using OData and get the following, due to their link to each other:  
Exception - The key property 'GarnishmentTaxLevyType' on for type 'ODataUtility.  Microsoft.Dynamics.DataEntities.WorkerGarnishmentRule' is of type 'System.Nullable`1[[ODataUtility.Microsoft.Dynamics.DataEntities.PayrollGarnishmentTaxLevyType, ODataUtility, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]', which is not a simple type. Only properties of simple type can be key properties.

**Comment by gathogojr** [comment]
Fixed by https://github.com/OData/odata.net/pull/3013
