### ISSUE TITLE
Support IEnumerable<> as Collection type

### ISSUE THREAD

**Issue by Kation** [OData/odata.net#1805]
For now, The property type that implements ICollection<> can use Any or All method only.
See https://github.com/OData/odata.net/blob/5464035e4cc28913eb143b0007150b56701ea42c/src/Microsoft.OData.Client/ALinq/ResourceBinder.cs#L2748-L2753

But sometimes we will use IEnumerable<> as a property type in a model.
See `Device` class in https://github.com/dotnet/efcore/issues/21171

EF Core only support map IEnumerable in `Select` if there maybe a `Where` uses this IEnumerable property after `Select`. 
Specially in odata client.
`dataServiceContext.CreateQuery<Device>().Where(t => t.Tags.Any(x => x == "something")).ToArrayAsync();`

### Assemblies affected

Microsoft.OData.Client 7.6.4

### Expected result

Build request uri successfully.

### Actual result

Throw a exception.

```
System.NotSupportedException: The source parameter for the 'Any' method has to be either a navigation or a collection property.
   at Microsoft.OData.Client.ResourceBinder.ValidationRules.WhereAndOrderByChecker.VisitMethodCall(MethodCallExpression mce)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.DataServiceALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ALinqExpressionVisitor.VisitBinary(BinaryExpression b)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.DataServiceALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ResourceBinder.AnalyzePredicate(MethodCallExpression mce, ClientEdmModel model)
   at Microsoft.OData.Client.ResourceBinder.VisitMethodCall(MethodCallExpression mce)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.DataServiceALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ResourceBinder.Bind(Expression e, DataServiceContext context)
   at Microsoft.OData.Client.DataServiceQueryProvider.Translate(Expression e)
   at Microsoft.OData.Client.DataServiceQuery`1.Translate()
   at Microsoft.OData.Client.DataServiceQuery`1.QueryComponents(ClientEdmModel model)
   at Microsoft.OData.Client.DataServiceRequest.CreateExecuteResult(Object source, DataServiceContext context, AsyncCallback callback, Object state, String method)
   at Microsoft.OData.Client.DataServiceRequest.BeginExecute(Object source, DataServiceContext context, AsyncCallback callback, Object state, String method)
   at Microsoft.OData.Client.DataServiceQuery`1.BeginExecute(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync(Func`3 beginMethod, Func`2 endMethod, Object state)
   at Microsoft.OData.Client.DataServiceQuery`1.ExecuteAsync()
   at Qssy.PushNotificationService.OData.ODataExtensions.ToArrayAsync[T](IQueryable`1 source) in D:\TFS\CQ.RDD\P015.QPNS\01.Solutions\Qssy.PushNotificationService\src\Qssy.PushNotificationService.Core\ODataExtensions.cs:line 16
   at Qssy.PushNotificationService.ApiService.Controllers.AccountController.ClearDevices(String account) in D:\TFS\CQ.RDD\P015.QPNS\01.Solutions\Qssy.PushNotificationService\src\Qssy.PushNotificationService.ApiService\Controllers\AccountController.cs:line 46
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
@mumbi-o Please priority it, thanks.
