### ISSUE TITLE
PlatformNotSupportedException thrown when DataServiceTransportException is about to be raised

### ISSUE THREAD

**Issue by ddosfd** [OData/odata.net#1833]
Using:
Microsoft.OData.Client v7.7.0
dotnetcore 2.1

While using batch operation to unauthorized OData service instead of DataServiceTransportException I get PlatformNotSupportedException with no details of an exception

**Comment by ElizabethOkerio** [comment]
@ddosfd  please provide more info on this issue for us to dig more

**Comment by AdamCaviness** [comment]
@ElizabethOkerio I believe I hit the same issue as @ddosfd did but in a different class, `DataServiceClientException`. I am on netcore3.1 but the same exception is raised. Here's the portion of the StackTrace as it transitions from my code to the OData Client code:

> System.PlatformNotSupportedException
  HResult=0x80131539
  Message=Secure binary serialization is not supported on this platform.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Exception.add_SerializeObjectState(EventHandler \`1 value)
   at Microsoft.OData.Client.DataServiceClientException..ctor(String message, Exception innerException, Int32 statusCode) in C:\Users\acaviness\source\repos\ssp\Source\Microsoft.OData.Client\DataServiceClientException.cs:line 72
   at Microsoft.OData.Client.DataServiceClientException..ctor(String message, Int32 statusCode) in C:\Users\acaviness\source\repos\ssp\Source\Microsoft.OData.Client\DataServiceClientException.cs:line 58
   at Microsoft.OData.Client.BaseSaveResult.GetResponseText(Func \`1 getResponseStream, HttpStatusCode statusCode) in C:\Users\acaviness\source\repos\ssp\Source\Microsoft.OData.Client\BaseSaveResult.cs:line 252
   at Microsoft.OData.Client.BaseSaveResult.HandleResponse(RequestInfo requestInfo, HttpStatusCode statusCode, String responseVersion, Func`1 getResponseStream, Boolean throwOnFailure, Version& parsedResponseVersion) in C:\Users\acaviness\source\repos\ssp\Source\Microsoft.OData.Client\BaseSaveResult.cs:line 217
   at Microsoft.OData.Client.BatchSaveResult.ProcessCurrentOperationResponse(ODataBatchReader batchReader, Boolean isChangesetOperation) in C:\Users\acaviness\source\repos\ssp\Source\Microsoft.OData.Client\BatchSaveResult.cs:line 841
   at Microsoft.OData.Client.BatchSaveResult.<HandleBatchResponse>d__26.MoveNext() in C:\Users\acaviness\source\repos\ssp\Source\Microsoft.OData.Client\BatchSaveResult.cs:line 632
   at Microsoft.OData.Client.BatchSaveResult.HandleBatchResponseInternal(ODataBatchReader batchReader) in C:\Users\acaviness\source\repos\ssp\Source\Microsoft.OData.Client\BatchSaveResult.cs:line 551
   at Microsoft.OData.Client.BatchSaveResult.HandleBatchResponse() in C:\Users\acaviness\source\repos\ssp\Source\Microsoft.OData.Client\BatchSaveResult.cs:line 484
   at Microsoft.OData.Client.BatchSaveResult.HandleResponse() in C:\Users\acaviness\source\repos\ssp\Source\Microsoft.OData.Client\BatchSaveResult.cs:line 216
   at Microsoft.OData.Client.BaseSaveResult.EndRequest() in C:\Users\acaviness\source\repos\ssp\Source\Microsoft.OData.Client\BaseSaveResult.cs:line 265
   at Microsoft.OData.Client.DataServiceContext.SaveChanges(SaveChangesOptions options) in C:\Users\acaviness\source\repos\ssp\Source\Microsoft.OData.Client\DataServiceContext.cs:line 1923
   at SS.Core.Client.Models.Data.SouthernSoftwareEntities.SaveChanges(SaveChangesOptions options) in C:\Users\acaviness\source\repos\ssp\Source\SS.Core.Client.Models\Common\SouthernSoftwareEntities.cs:line 143

Both `DataServiceClientException` and `DataServiceTransportException` have a constructor that hooks the base Exception's `SerializeObjectState` event. I searched all of the client codebase and these two derived exception classes are the only subscribers to that event.

**Comment by AdamCaviness** [comment]
@ElizabethOkerio I found that [Microsoft documents](https://docs.microsoft.com/en-us/dotnet/core/compatibility/unsupported-apis) that `Exception.SerializeObjectState` is an unsupported API.

**Comment by ChrisSchaller** [comment]
Therefore this process should either check for platform support first or be wrapped so as not to raise additional exceptions. It is a common requirement to specifically handle Unauthorized exceptions so this is a blocking issue to production apps. Rolling back to v7.6.4 generally resolves the issue.

**Comment by shayansadullah** [comment]
Hi does anyone know what the latest situation is with this unsupported 'Exception.SerializeObjectState' issue?

**Comment by ChrisSchaller** [comment]
Note this is not just for batch operations, this is ANY operation that results in an Unauthorized result from the API.

**Comment by ElizabethOkerio** [comment]
sorry for the late response, we are looking into this.

**Comment by shayansadullah** [comment]
Hi, has this issue been resolved as its been closed?

**Comment by ElizabethOkerio** [comment]
@shayansadullah yes this issue has been resolved.

**Comment by ddosfd** [comment]
@ElizabethOkerio do you know when the newest version with this fix will be released?

**Comment by ElizabethOkerio** [comment]
@ddosfd a new release was already made. Check it out.
