### ISSUE TITLE
System.NullReferenceException in Data.Services.Client.EntityTracker.InternalAttachEntityDescriptor 

### ISSUE THREAD

**Issue by AtulBhartia** [OData/odata.net#1851]
*Short summary (3-5 sentences) describing the issue.*
Asp .net Core service is calling OdataV3 service. We intermittently get following errors. Any suggestion how to root cause NullReferenceException in EntityTracker.InternalAttachEntityDescriptor

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Data.Services.Client.EntityTracker.InternalAttachEntityDescriptor(EntityDescriptor entityDescriptorFromMaterializer, Boolean failIfDuplicated)
   at System.Data.Services.Client.AtomMaterializerLog.ApplyToContext()
   at System.Data.Services.Client.Materialization.ODataEntityMaterializer.ApplyLogToContext()
   at System.Data.Services.Client.MaterializeAtom.MoveNextInternal()
   at System.Data.Services.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)

Let us know if you have any question.

### Assemblies affected
Microsoft.OData.Client 7.6.1

### Reproduce steps
Happening in our production services intermittently 

### Expected result
Get should return the entity without excetion

### Actual result
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by marabooy** [comment]
@AtulBhartia could you share the csdl for the service if possible so as to make reproducing this easier.

**Comment by marabooy** [comment]
Hi @AtulBhartia would it be possible to migrate to OData v4? We have an [extension ](https://devblogs.microsoft.com/odata/migrating-odata-v3-services-to-odata-v4-without-disrupting-existing-clients/)that allows for seamless migration. OData v3 library is currently in maintenance mode and mainly receives hotfixes.

**Comment by AtulBhartia** [comment]
We have multiple legacy services and we cannot move to odataV4 at this time.
Our client was re using DataServiceContext across calls. We fixed that. I will update in few days if that fixes the issue

**Comment by AtulBhartia** [comment]
After fixing our client, we have not seen this issue repo in last one week. Therefore I am closing this thread
