### ISSUE TITLE
Operations that change non-concurrent collections must have exclusive access

### ISSUE THREAD

**Issue by AtulBhartia** [OData/odata.net#1852]
Asp .net Core service is calling OdataV3 service. We intermittently get following errors. Any suggestion how to fix this.

System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at System.Data.Services.Client.EntityTracker.TryGetEntity(String resourceUri, EntityStates& state)
   at System.Data.Services.Client.Materialization.EntityTrackingAdapter.TryResolveFromContext(MaterializerEntry entry, Type expectedEntryType)
   at System.Data.Services.Client.Materialization.EntityTrackingAdapter.TryResolveExistingEntity(MaterializerEntry entry, Type expectedEntryType)
   at System.Data.Services.Client.Materialization.EntryValueMaterializationPolicy.Materialize(MaterializerEntry entry, Type expectedEntryType, Boolean includeLinks)
   at System.Data.Services.Client.Materialization.ODataEntityMaterializerInvoker.DirectMaterializePlan(Object materializer, Object entry, Type expectedEntryType)
   at System.Data.Services.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
   at System.Data.Services.Client.MaterializeAtom.MoveNextInternal()
   at System.Data.Services.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)

Let us know if you have any question.

### Assemblies affected
Microsoft.OData.Client 7.6.1

### Reproduce steps

Happening in our production services intermittently

### Expected result

no exception

### Actual result

exception is thrown

**Comment by marabooy** [comment]
Hi @AtulBhartia would it be possible to migrate to OData v4? We have an [extension ](https://devblogs.microsoft.com/odata/migrating-odata-v3-services-to-odata-v4-without-disrupting-existing-clients/)that allows for seamless migration. OData v3 library is currently in maintenance mode and mainly receives hotfixes.

**Comment by AtulBhartia** [comment]
We have multiple legacy services and we cannot move to odataV4 at this time.
Our client was re using DataServiceContext across calls. We fixed that. I will update in few days if that fixes the issue

**Comment by AtulBhartia** [comment]
After fixing our client, we have not seen this issue repo in last one week. Therefore I am closing this thread
