### ISSUE TITLE
Improve Deserialization Errors

### ISSUE THREAD

**Issue by ethanshea-ms** [OData/odata.net#1899]
When deserializing a malformed (not syntactically valid) payload, or an invalid (not schematically valid) payload it is useful to generate an exception that provides fields like LineNumber, LinePosition, and Path. These fields can be used to construct errors which are given to customers. Currently, an ODataException is created with only a message.

Similar libraries like [System.Text.Json](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonexception?view=netcore-3.1#properties) and [Newtonsoft](https://www.newtonsoft.com/json/help/html/Properties_T_Newtonsoft_Json_JsonSerializationException.htm) provide this information in their exceptions.

### Assemblies affected

Microsoft.AspNet.OData.dll, Microsoft.AspNetCore.OData.dll 7.4.1

### Reproduce steps

Construct a malformed/invalid JSON payload, deserialize it, and observe the ODataException thrown. Something like below will be thrown.

<details>
  <summary>Stack Trace</summary>

```
Microsoft.OData.ODataException: The property 'value' does not exist on type 'Microsoft.Media.MediaGraphImageFormatEncoding'. Make sure to only use property names that are defined by the type or mark the type as open type.
   at Microsoft.OData.ReaderValidationUtils.ValidatePropertyDefined(String propertyName, IEdmStructuredType owningStructuredType, Boolean throwOnUndeclaredPropertyForNonOpenType)
   at Microsoft.OData.ReaderValidator.ValidatePropertyDefined(String propertyName, IEdmStructuredType owningStructuredType)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithValue(IODataJsonLightReaderResourceState resourceState, String propertyName, Boolean isDeltaResourceSet)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.<>c__DisplayClass9_0.<ReadResourceContent>b__0(PropertyParsingResult propertyParsingResult, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.StartReadingResource()
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceSetItemStart(PropertyAndAnnotationCollector propertyAndAnnotationCollector, SelectedPropertiesNode selectedProperties)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadNextResourceSetItem()
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtResourceSetStartImplementationSynchronously()
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtResourceSetStartImplementation()
   at Microsoft.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.ODataReaderCore.ReadSynchronously()
   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at Microsoft.OData.ODataReaderCore.Read()
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)
   at Microsoft.AspNet.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
<omitted application code>
```
</details>

### Expected result

This exception has properties, or entries in the [Exception.Data](https://docs.microsoft.com/en-us/dotnet/api/system.exception.data?view=netcore-3.1) field for line number, line position, and path as applicable. Line number/position is most useful for malformed json, and path is most useful for invalid json.

**Comment by marabooy** [comment]
@ethanshea-ms Thank you for reporting this. This would be a great feature to have and if you would would like to make a contribution we would be happy to consult with you on how to do this.
