### ISSUE TITLE
'System.Uri' not supported in OData payloads? 'ODataException' thrown when attempting to POST

### ISSUE THREAD

**Issue by julealgon** [OData/odata.net#1929]
I have a property in one of my models of type `Uri`. When attempting to post this to the server, I'm getting an `ODataException` like this:

> A 'PrimitiveValue' node with non-null value was found when trying to read the value of the property 'NotificationUrl'; however, a 'StartArray' node, a 'StartObject' node, or a 'PrimitiveValue' node with null value was expected.

>    at Microsoft.AspNet.OData.Formatter.ODataInputFormatter.<>c__DisplayClass7_0.<ReadRequestBodyAsync>b__1(Exception ex)
   at Microsoft.AspNet.OData.Formatter.ODataInputFormatterHelper.ReadFromStream(Type type, Object defaultValue, IEdmModel model, Uri baseAddress, IWebApiRequestMessage internalRequest, Func`1 getODataRequestMessage, Func`2 getEdmTypeDeserializer, Func`2 getODataPayloadDeserializer, Func`1 getODataDeserializerContext, Action`1 registerForDisposeAction, Action`1 logErrorAction)
   at Microsoft.AspNet.OData.Formatter.ODataInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)

### Assemblies affected

Microsoft.OData.Core 7.7.1.0

### Reproduce steps

1. Add a `Uri` property to a model mapped as an entitySet
2. Attempt to post a valid URI value on this property
3. Observe the "Input is not valid" error and inner `ODataException` exception

### Expected result

The value should be parsed normally like other common types (e.g. `DateTime`).

### Actual result

An exception is thrown, and weird metadata is generated:

```xml
...
                <Property Name="NotificationUrl" Type="System.Uri" />
...
        <Schema Namespace="System" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <ComplexType Name="Uri">
                <Property Name="Segments" Type="Collection(Edm.String)" />
            </ComplexType>
        </Schema>
...
```

**Comment by gathogojr** [comment]
@julealgon I'm not sure why you think that the metadata is weird. While `DateTime`, `decimal` and `string` are really not primitive types, the OData library is specifically build to handle them as primitive known types. Not so for `Uri`, which is why its being interpreted as a complex type.
As an illustration, for a property of type `Uri` on your model, here's how it appears when you query the entity set:

```json
{
    "@odata.context": "http://ServiceRoot/$metadata#Books",
    "value": [
        {
            "Id": 1,
            "Title": "Introducing Machine Learning",
            "PublisherWebsite": {
                "Segments": [
                    "/"
                ]
            }
        }
    ]
}
```
where the CLR type looks as follows:
```csharp
    public class Book
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public Uri PublisherWebsite { get; set; }
    }
```
To my knowledge, there's no supported conversion from `Uri` to `string`, which is why this is not valid C#
```csharp
Uri uri = "http://tempuri.org";
```

I expect that in your POST request, you're supplying the value for the `Uri` property as a `string`. Maybe:
```
POST: http://ServiceRoot/Books
Body:
{
    "Id": 2,
    "Title": "Programming ASP.NET Core",
    "PublisherWebsite": "https://www.microsoftpressstore.com/"
}

```
Other than visually being able to interpret the value as a `Uri`, how would we differentiate it from a  normal `string` during deserialization?

If this was to be supported, we'd need to design a way to communicate that the value should be deserialized as a `Uri` - maybe introduce a type like `Edm.Uri` in the **Edm** library and apply that to the payload to indicate that the value should be read as a `Uri`.

Before considering that kind of effort, is there a specific reason why you can't use `string` as the property type?

**Comment by mikepizzo** [comment]
Uri is not a built-in Edm type for the protocol, and adding new built-in Edm type is expensive.

The wire format of this type should be string.  The protocol does define a [Core.IsURL](https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Core.V1.xml#L384) annotation that can be used to annotate the string property to say that it represents a Uri.

**Comment by julealgon** [comment]
@gathogojr 
> Other than visually being able to interpret the value as a Uri, how would we differentiate it from a normal string during deserialization?

The same way the library deals with `DateTime` today. Those are also represented "as strings" on the input and it works just fine. `Uri` has a few parsing methods and you can specify that the URI might be either relative or absolute.

> Before considering that kind of effort, is there a specific reason why you can't use string as the property type?

I can definitely use a `string` (that's what I ended up doing after finding out about this issue). However, representing URLs as `string`s is a known bad practice in .Net since there is a stronger type to do that, `Uri`. It is the same reasoning as with dates: even though one can represent them as `string` just fine, it is not the recommended approach as there are strong types available to do it (`DateTime` and `DateTimeOffset`).

Adding native support for `Uri` would make a lot of sense to me and would allow people to have stronger models when dealing with OData.

---

@mikepizzo 
> Uri is not a built-in Edm type for the protocol, and adding new built-in Edm type is expensive.

Fair enough. I did not consider "how expensive it might be" when proposing this, just how unintuitive it seemed to me when attempting to use it.

> The wire format of this type should be string. The protocol does define a Core.IsURL annotation that can be used to annotate the string property to say that it represents a Uri.

Oh this is interesting... I've never heard of these annotations before. Could you please provide some documentation on how they work, and how I could annotate my model to have that reflected in the generated metadata?

**Comment by julealgon** [comment]
Also @mikepizzo , you mentioned adding a new "built-in" type was expensive. How about adding the type on my end? What would I need to do to support posting `Uri` instances as string? Is there documentation somewhere describing how to create new types and serialize to and from them in OData?
