### ISSUE TITLE
'in' operator can't be used with open property

### ISSUE THREAD

**Issue by cppcraze** [OData/odata.net#1958]
'in' operator can't be used with open property

### Assemblies affected

Microsoft.OData.Core 7.7.3

### Reproduce steps

Request with below $filter will fail
$filter=extension_2782bd535fad492abfcc5ac40ae3a14b_teststring in ('a', 'b')

### Expected result

This $filter expression should be correctly parsed with open property as left operand and an array of string as right operand.

### Actual result

It hit NullReferenceException at

   at Microsoft.OData.Edm.EdmUtil.CheckArgumentNull[T](T value, String parameterName)
   at Microsoft.OData.Edm.EdmCollectionType..ctor(IEdmTypeReference elementType)
   at Microsoft.OData.UriParser.InBinder.BindInOperator(InToken inToken, BindingState state)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()

### Additional detail

It is because of below **_left.TypeReference_** is null if left is SingleValueOpenPropertyAccessNode.

```csharp
SingleValueNode left = this.GetSingleValueOperandFromToken(inToken.Left);
CollectionNode right = this.GetCollectionOperandFromToken(
    inToken.Right, new EdmCollectionTypeReference(new EdmCollectionType(left.TypeReference)), state.Model);
```

File: https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/UriParser/Binders/InBinder.cs
Line: 48

**Comment by mikepizzo** [comment]
We can look at supporting this better (at least not returning a nullref exception), but in the meantime you should be able to do an explicit cast of the open property to make this work:

$filter=cast(extension_2782bd535fad492abfcc5ac40ae3a14b_teststring, Edm.String) in ('a', 'b')

**Comment by gathogojr** [comment]
Fixed by https://github.com/OData/odata.net/pull/3190
