### ISSUE TITLE
Query crashes on client

### ISSUE THREAD

**Issue by fededim** [OData/odata.net#1968]
Hi,

I am using the OData 7.5.2 packages on server. The client code using ODataConnectedService 0.11.1 generated class is this:

```
            var DEVICE_SN = "1910017250";
            var ctx = new Default.Container(new Uri("http://localhost/SincroADR_Api/odata"));
            var tuns = ctx.Tunnels.Where(e => e.Id<3).ToList();
            var cam = ctx.Cameras.Where(c => !String.IsNullOrEmpty(DEVICE_SN) && c.SerialNumber == DEVICE_SN && c.Active);
            var c = cam.SingleOrDefault();  // crashes here with InvalidOperationException
```

The ODATA query "http://localhost/SincroADR_Api/odata/Cameras?$filter=true and SerialNumber eq '1910017250' and Active" actually works on browser returning this result:

```
{"@odata.context":"http://localhost/SincroADR_Api/odata/$metadata#Cameras","value":[{"Id":13,"ExternalId":"15","Name":"Del Monte Imbocco (Dir. IT)","Model":"Tattile Vega Smart 2HD","SerialNumber":"1910017250","CameraTypeId":"ADR","IpAddress":"10.144.177.156","TunnelId":null,"CarriagewayId":19,"OppositePositioning":true,"Distance":152.218,"Active":true,"Location":{"X":43.799165,"Y":7.590005}}]}
```

The $metadata model is this:

```
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="SincroADR_Models.Models.DB" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="Transit">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int64" Nullable="false" />
                <Property Name="Timestamp" Type="Edm.DateTimeOffset" Nullable="false" />
                <Property Name="CameraId" Type="Edm.Int64" />
                <Property Name="Plate" Type="Edm.String" MaxLength="20" />
                <Property Name="PlateNationCode" Type="Edm.String" MaxLength="5" />
                <Property Name="OnuCode" Type="Edm.Int32" />
                <Property Name="KemlerCode" Type="Edm.Int32" />
                <Property Name="X" Type="Edm.Boolean" />
                <Property Name="KemlerCategoryId" Type="SincroADR_Models.Models.DB.KemlerCategoryEnum" Nullable="false" />
                <Property Name="WrongDirection" Type="Edm.Boolean" Nullable="false" />
                <Property Name="Speed" Type="Edm.Single" />
                <NavigationProperty Name="Camera" Type="SincroADR_Models.Models.DB.Camera">
                    <ReferentialConstraint Property="CameraId" ReferencedProperty="Id" />
                </NavigationProperty>
            </EntityType>
            <EntityType Name="Camera">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int64" Nullable="false" />
                <Property Name="ExternalId" Type="Edm.String" MaxLength="50" />
                <Property Name="Name" Type="Edm.String" MaxLength="50" />
                <Property Name="Model" Type="Edm.String" MaxLength="100" />
                <Property Name="SerialNumber" Type="Edm.String" MaxLength="50" />
                <Property Name="CameraTypeId" Type="SincroADR_Models.Models.DB.CameraTypeEnum" Nullable="false" />
                <Property Name="IpAddress" Type="Edm.String" MaxLength="50" />
                <Property Name="TunnelId" Type="Edm.Int64" />
                <Property Name="CarriagewayId" Type="Edm.Int64" />
                <Property Name="OppositePositioning" Type="Edm.Boolean" Nullable="false" />
                <Property Name="Distance" Type="Edm.Single" Nullable="false" />
                <Property Name="Location" Type="NetTopologySuite.Geometries.Point" />
                <Property Name="Active" Type="Edm.Boolean" Nullable="false" />
                <NavigationProperty Name="Tunnel" Type="SincroADR_Models.Models.DB.Tunnel">
                    <ReferentialConstraint Property="TunnelId" ReferencedProperty="Id" />
                </NavigationProperty>
                <NavigationProperty Name="Carriageway" Type="SincroADR_Models.Models.DB.Carriageway">
                    <ReferentialConstraint Property="CarriagewayId" ReferencedProperty="Id" />
                </NavigationProperty>
                <NavigationProperty Name="CameraType" Type="SincroADR_Models.Models.DB.CameraType" />
                <NavigationProperty Name="CountSessions" Type="Collection(SincroADR_Models.Models.DB.CountSessionToCamera)" />
                <NavigationProperty Name="Transits" Type="Collection(SincroADR_Models.Models.DB.Transit)" />
            </EntityType>
            <EntityType Name="Authority">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int64" Nullable="false" />
                <Property Name="ExternalId" Type="Edm.String" MaxLength="50" />
                <Property Name="ImportEndpointId" Type="Edm.Int64" />
                <Property Name="Name" Type="Edm.String" MaxLength="50" />
                <Property Name="Description" Type="Edm.String" MaxLength="200" />
                <Property Name="Active" Type="Edm.Boolean" Nullable="false" />
                <NavigationProperty Name="ImportEndpoint" Type="SincroADR_Models.Models.DB.ImportEndpoint">
                    <ReferentialConstraint Property="ImportEndpointId" ReferencedProperty="Id" />
                </NavigationProperty>
            </EntityType>
            <EntityType Name="Carriageway">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int64" Nullable="false" />
                <Property Name="ExternalId" Type="Edm.String" MaxLength="50" />
                <Property Name="Name" Type="Edm.String" Nullable="false" MaxLength="50" />
                <Property Name="Description" Type="Edm.String" MaxLength="200" />
                <Property Name="SectionId" Type="Edm.Int64" />
                <Property Name="CarriagewayDirectionId" Type="SincroADR_Models.Models.DB.CarriagewayDirectionEnum" Nullable="false" />
                <Property Name="Active" Type="Edm.Boolean" Nullable="false" />
                <NavigationProperty Name="Section" Type="SincroADR_Models.Models.DB.Section">
                    <ReferentialConstraint Property="SectionId" ReferencedProperty="Id" />
                </NavigationProperty>
                <NavigationProperty Name="CarriagewayDirection" Type="SincroADR_Models.Models.DB.CarriagewayDirection" />
            </EntityType>
            <EntityType Name="CarriagewayDirection">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="SincroADR_Models.Models.DB.CarriagewayDirectionEnum" Nullable="false" />
                <Property Name="Description" Type="Edm.String" MaxLength="50" />
            </EntityType>
            <EntityType Name="Section">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int64" Nullable="false" />
                <Property Name="ExternalId" Type="Edm.String" MaxLength="50" />
                <Property Name="AuthorityId" Type="Edm.Int64" />
                <Property Name="Name" Type="Edm.String" Nullable="false" MaxLength="50" />
                <Property Name="Description" Type="Edm.String" MaxLength="200" />
                <Property Name="ShortDescription" Type="Edm.String" MaxLength="100" />
                <Property Name="StartDistance" Type="Edm.Single" Nullable="false" />
                <Property Name="EndDistance" Type="Edm.Single" Nullable="false" />
                <Property Name="Active" Type="Edm.Boolean" Nullable="false" />
                <NavigationProperty Name="Authority" Type="SincroADR_Models.Models.DB.Authority">
                    <ReferentialConstraint Property="AuthorityId" ReferencedProperty="Id" />
                </NavigationProperty>
            </EntityType>
            <EntityType Name="Tunnel">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int64" Nullable="false" />
                <Property Name="ExternalId" Type="Edm.String" MaxLength="50" />
                <Property Name="Name" Type="Edm.String" Nullable="false" MaxLength="50" />
                <Property Name="Description" Type="Edm.String" MaxLength="100" />
                <Property Name="CarriagewayId" Type="Edm.Int64" />
                <Property Name="StartDistance" Type="Edm.Single" Nullable="false" />
                <Property Name="EndDistance" Type="Edm.Single" Nullable="false" />
                <Property Name="Length" Type="Edm.Single" Nullable="false" />
                <Property Name="EnterCountSessionId" Type="Edm.Int64" />
                <Property Name="ExitCountSessionId" Type="Edm.Int64" />
                <Property Name="AverageAdrTransitTime" Type="Edm.Int32" />
                <Property Name="StartLocation" Type="NetTopologySuite.Geometries.Point" />
                <Property Name="EndLocation" Type="NetTopologySuite.Geometries.Point" />
                <Property Name="Active" Type="Edm.Boolean" Nullable="false" />
                <NavigationProperty Name="EnterCountSession" Type="SincroADR_Models.Models.DB.CountSession" />
                <NavigationProperty Name="ExitCountSession" Type="SincroADR_Models.Models.DB.CountSession" />
                <NavigationProperty Name="Carriageway" Type="SincroADR_Models.Models.DB.Carriageway">
                    <ReferentialConstraint Property="CarriagewayId" ReferencedProperty="Id" />
                </NavigationProperty>
            </EntityType>
            <EntityType Name="ImportEndpoint">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int64" Nullable="false" />
                <Property Name="EndpointType" Type="SincroADR_Models.Models.DB.EndpointTypeEnum" Nullable="false" />
                <Property Name="ExternalServiceUrl" Type="Edm.String" Nullable="false" MaxLength="100" />
                <Property Name="ExternalServiceLogin" Type="Edm.String" MaxLength="50" />
                <Property Name="ExternalServicePassword" Type="Edm.String" MaxLength="50" />
            </EntityType>
            <EntityType Name="CountSession">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int64" Nullable="false" />
                <Property Name="AuthorityId" Type="Edm.Int64" />
                <Property Name="Name" Type="Edm.String" Nullable="false" MaxLength="50" />
                <Property Name="ReliabilityReferenceCountSessions" Type="Edm.String" MaxLength="2048" />
                <Property Name="Active" Type="Edm.Boolean" Nullable="false" />
                <NavigationProperty Name="Cameras" Type="Collection(SincroADR_Models.Models.DB.CountSessionToCamera)" />
                <NavigationProperty Name="CountPaths" Type="Collection(SincroADR_Models.Models.DB.CountPathToCountSession)" />
                <NavigationProperty Name="Authority" Type="SincroADR_Models.Models.DB.Authority">
                    <ReferentialConstraint Property="AuthorityId" ReferencedProperty="Id" />
                </NavigationProperty>
            </EntityType>
            <EntityType Name="CountSessionToCamera">
                <Key>
                    <PropertyRef Name="CameraId" />
                    <PropertyRef Name="CountSessionId" />
                </Key>
                <Property Name="CountSessionId" Type="Edm.Int64" />
                <Property Name="CameraId" Type="Edm.Int64" />
                <NavigationProperty Name="CountSession" Type="SincroADR_Models.Models.DB.CountSession">
                    <ReferentialConstraint Property="CountSessionId" ReferencedProperty="Id" />
                </NavigationProperty>
                <NavigationProperty Name="Camera" Type="SincroADR_Models.Models.DB.Camera">
                    <ReferentialConstraint Property="CameraId" ReferencedProperty="Id" />
                </NavigationProperty>
            </EntityType>
            <EntityType Name="CountPath">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="Edm.Int64" Nullable="false" />
                <Property Name="AuthorityId" Type="Edm.Int64" />
                <Property Name="Name" Type="Edm.String" Nullable="false" MaxLength="50" />
                <Property Name="Active" Type="Edm.Boolean" Nullable="false" />
                <NavigationProperty Name="CountSessions" Type="Collection(SincroADR_Models.Models.DB.CountPathToCountSession)" />
                <NavigationProperty Name="Authority" Type="SincroADR_Models.Models.DB.Authority">
                    <ReferentialConstraint Property="AuthorityId" ReferencedProperty="Id" />
                </NavigationProperty>
            </EntityType>
            <EntityType Name="CountPathToCountSession">
                <Key>
                    <PropertyRef Name="CountPathId" />
                    <PropertyRef Name="CountSessionId" />
                </Key>
                <Property Name="CountPathId" Type="Edm.Int64" />
                <Property Name="CountSessionId" Type="Edm.Int64" />
                <NavigationProperty Name="CountPath" Type="SincroADR_Models.Models.DB.CountPath">
                    <ReferentialConstraint Property="CountPathId" ReferencedProperty="Id" />
                </NavigationProperty>
                <NavigationProperty Name="CountSession" Type="SincroADR_Models.Models.DB.CountSession">
                    <ReferentialConstraint Property="CountSessionId" ReferencedProperty="Id" />
                </NavigationProperty>
            </EntityType>
            <EntityType Name="Configuration">
                <Key>
                    <PropertyRef Name="Key" />
                </Key>
                <Property Name="Key" Type="Edm.String" Nullable="false" MaxLength="50" />
                <Property Name="Description" Type="Edm.String" MaxLength="256" />
                <Property Name="Value" Type="Edm.String" Nullable="false" MaxLength="100" />
            </EntityType>
            <EntityType Name="CameraType">
                <Key>
                    <PropertyRef Name="Id" />
                </Key>
                <Property Name="Id" Type="SincroADR_Models.Models.DB.CameraTypeEnum" Nullable="false" />
                <Property Name="Description" Type="Edm.String" MaxLength="50" />
            </EntityType>
            <EnumType Name="KemlerCategoryEnum" UnderlyingType="Edm.Byte">
                <Member Name="Empty" Value="0" />
                <Member Name="Gas" Value="2" />
                <Member Name="FlammableLiquid" Value="3" />
                <Member Name="FlammableSolid" Value="4" />
                <Member Name="ComburentMaterial" Value="5" />
                <Member Name="ToxicMaterial" Value="6" />
                <Member Name="RadioactiveMaterial" Value="7" />
                <Member Name="CorrosiveMaterial" Value="8" />
                <Member Name="OtherDangeroursMateria" Value="9" />
            </EnumType>
            <EnumType Name="CameraTypeEnum" UnderlyingType="Edm.Int16">
                <Member Name="Standard" Value="1" />
                <Member Name="ADR" Value="2" />
            </EnumType>
            <EnumType Name="EndpointTypeEnum" UnderlyingType="Edm.Int16">
                <Member Name="SincroRest" Value="1" />
            </EnumType>
            <EnumType Name="CarriagewayDirectionEnum" UnderlyingType="Edm.Byte">
                <Member Name="Ascending" Value="0" />
                <Member Name="Descending" Value="1" />
            </EnumType>
        </Schema>
        <Schema Namespace="NetTopologySuite.Geometries" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <ComplexType Name="Point">
                <Property Name="X" Type="Edm.Double" Nullable="false" />
                <Property Name="Y" Type="Edm.Double" Nullable="false" />
            </ComplexType>
        </Schema>
        <Schema Namespace="SincroADR_Models.Models.DB.StoredProcedures" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="CameraOverviewResult" BaseType="SincroADR_Models.Models.DB.Camera">
                <Property Name="TotalTransits" Type="Edm.Int64" Nullable="false" />
            </EntityType>
            <EntityType Name="NestedTransitDataReasons" BaseType="SincroADR_Models.Models.DB.Transit">
                <Property Name="CameraName" Type="Edm.String" />
                <Property Name="CarriagewayName" Type="Edm.String" />
                <Property Name="TransitPresentAlsoInCountSession" Type="Edm.Boolean" Nullable="false" />
                <Property Name="CountSessionTransitTimestamp" Type="Edm.DateTimeOffset" />
                <NavigationProperty Name="SimilarTransits" Type="Collection(SincroADR_Models.Models.DB.Transit)" />
            </EntityType>
        </Schema>
        <Schema Namespace="SincroADR_Models.Models.DB.ExtendedEntities" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="ExtendedTransit" BaseType="SincroADR_Models.Models.DB.Transit">
                <Property Name="OnuCodeDescription" Type="Edm.String" />
                <Property Name="KemlerCodeDescription" Type="Edm.String" />
            </EntityType>
        </Schema>
        <Schema Namespace="SincroADR_Models.Models.API.Responses" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityType Name="NestedTransits" BaseType="SincroADR_Models.Models.DB.ExtendedEntities.ExtendedTransit" />
        </Schema>
        <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <EntityContainer Name="Container">
                <EntitySet Name="Transits" EntityType="SincroADR_Models.Models.DB.Transit">
                    <NavigationPropertyBinding Path="Camera" Target="Cameras" />
                    <NavigationPropertyBinding Path="SincroADR_Models.Models.DB.StoredProcedures.NestedTransitDataReasons/SimilarTransits" Target="Transits" />
                </EntitySet>
                <EntitySet Name="Cameras" EntityType="SincroADR_Models.Models.DB.Camera">
                    <NavigationPropertyBinding Path="Carriageway" Target="Carriageways" />
                    <NavigationPropertyBinding Path="CountSessions" Target="CountSessionToCameras" />
                    <NavigationPropertyBinding Path="Transits" Target="Transits" />
                    <NavigationPropertyBinding Path="Tunnel" Target="Tunnels" />
                </EntitySet>
                <EntitySet Name="Authorities" EntityType="SincroADR_Models.Models.DB.Authority">
                    <NavigationPropertyBinding Path="ImportEndpoint" Target="ImportEndpoints" />
                </EntitySet>
                <EntitySet Name="Carriageways" EntityType="SincroADR_Models.Models.DB.Carriageway">
                    <NavigationPropertyBinding Path="CarriagewayDirection" Target="CarriagewayDirections" />
                    <NavigationPropertyBinding Path="Section" Target="Sections" />
                </EntitySet>
                <EntitySet Name="CarriagewayDirections" EntityType="SincroADR_Models.Models.DB.CarriagewayDirection" />
                <EntitySet Name="Sections" EntityType="SincroADR_Models.Models.DB.Section">
                    <NavigationPropertyBinding Path="Authority" Target="Authorities" />
                </EntitySet>
                <EntitySet Name="Tunnels" EntityType="SincroADR_Models.Models.DB.Tunnel">
                    <NavigationPropertyBinding Path="Carriageway" Target="Carriageways" />
                    <NavigationPropertyBinding Path="EnterCountSession" Target="CountSessions" />
                    <NavigationPropertyBinding Path="ExitCountSession" Target="CountSessions" />
                </EntitySet>
                <EntitySet Name="ImportEndpoints" EntityType="SincroADR_Models.Models.DB.ImportEndpoint" />
                <EntitySet Name="CountSessions" EntityType="SincroADR_Models.Models.DB.CountSession">
                    <NavigationPropertyBinding Path="Authority" Target="Authorities" />
                    <NavigationPropertyBinding Path="Cameras" Target="CountSessionToCameras" />
                    <NavigationPropertyBinding Path="CountPaths" Target="CountPathToCountSessions" />
                </EntitySet>
                <EntitySet Name="CountSessionToCameras" EntityType="SincroADR_Models.Models.DB.CountSessionToCamera">
                    <NavigationPropertyBinding Path="Camera" Target="Cameras" />
                    <NavigationPropertyBinding Path="CountSession" Target="CountSessions" />
                </EntitySet>
                <EntitySet Name="CountPaths" EntityType="SincroADR_Models.Models.DB.CountPath">
                    <NavigationPropertyBinding Path="Authority" Target="Authorities" />
                    <NavigationPropertyBinding Path="CountSessions" Target="CountPathToCountSessions" />
                </EntitySet>
                <EntitySet Name="CountPathToCountSessions" EntityType="SincroADR_Models.Models.DB.CountPathToCountSession">
                    <NavigationPropertyBinding Path="CountPath" Target="CountPaths" />
                    <NavigationPropertyBinding Path="CountSession" Target="CountSessions" />
                </EntitySet>
                <EntitySet Name="Configurations" EntityType="SincroADR_Models.Models.DB.Configuration" />
            </EntityContainer>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>

```

The exception thrown is this:
```
System.InvalidOperationException: This operation is only valid on generic types.
   at System.RuntimeType.GetGenericTypeDefinition()
   at Microsoft.OData.Client.Metadata.ClientTypeUtil.GetKeyPropertiesOnType(Type type, Boolean& hasProperties)
   at Microsoft.OData.Client.ClientEdmModel.GetTypeHierarchy(Type type, PropertyInfo[]& keyProperties, Boolean& hasProperties)
   at Microsoft.OData.Client.ClientEdmModel.GetOrCreateEdmType(Type type)
   at Microsoft.OData.Client.ClientEdmModel.CreateEdmProperty(IEdmStructuredType declaringType, PropertyInfo propertyInfo)
   at Microsoft.OData.Client.ClientEdmModel.<>c__DisplayClass37_0.<GetOrCreateEdmTypeInternal>b__0(EdmEntityTypeWithDelayLoadedProperties entityType)
   at Microsoft.OData.Client.Providers.EdmEntityTypeWithDelayLoadedProperties.EnsurePropertyLoaded()
   at Microsoft.OData.Client.Providers.EdmEntityTypeWithDelayLoadedProperties.get_DeclaredProperties()
   at Microsoft.OData.Client.Metadata.ClientTypeAnnotation.DiscoverEdmProperties()+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.OData.Client.Metadata.ClientTypeAnnotation.EdmProperties()
   at Microsoft.OData.Client.Metadata.ClientTypeAnnotation.BuildPropertyCache()
   at Microsoft.OData.Client.Metadata.ClientTypeAnnotation.GetProperty(String propertyName, UndeclaredPropertyBehavior undeclaredPropertyBehavior)
   at Microsoft.OData.Client.Materialization.StructuralValueMaterializationPolicy.MaterializeDataValues(ClientTypeAnnotation actualType, IEnumerable`1 values, UndeclaredPropertyBehavior undeclaredPropertyBehavior)
   at Microsoft.OData.Client.Materialization.EntryValueMaterializationPolicy.MaterializeResolvedEntry(MaterializerEntry entry, Boolean includeLinks)
   at Microsoft.OData.Client.Materialization.EntryValueMaterializationPolicy.Materialize(MaterializerEntry entry, Type expectedEntryType, Boolean includeLinks)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.DirectMaterializePlan(ODataEntityMaterializer materializer, MaterializerEntry entry, Type expectedEntryType)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializerInvoker.DirectMaterializePlan(Object materializer, Object entry, Type expectedEntryType)
   at Microsoft.OData.Client.ProjectionPlan.Run(ODataEntityMaterializer materializer, ODataResource entry, Type expectedType)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.OData.Client.DataServiceQueryProvider.ReturnSingleton[TElement](Expression expression)
   at Microsoft.OData.Client.DataServiceQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   at SincroADR_TattileTCPTransitReceiver.Worker.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\dimarco\source\repos\SincroADR\SincroADR_TattileTCPTransitReceiver\Worker.cs:line 42
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at SincroADR_TattileTCPTransitReceiver.Program.Main(String[] args) in C:\Users\dimarco\source\repos\SincroADR\SincroADR_TattileTCPTransitReceiver\Program.cs:line 25
```

The entity class being queried is this:

```
    public class Camera:IId64
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Int64 Id { get; set; }

        [MaxLength(50)]
        public String ExternalId { get; set; }

        [MaxLength(50)]
        public String Name { get; set; }


        [MaxLength(100)]
        public String Model { get; set; }


        [MaxLength(50)]
        public String SerialNumber { get; set; }

        [Required]
        public CameraTypeEnum CameraTypeId { get; set; }
        
        [MaxLength(50)]
        public String IpAddress { get; set; }

        public Int64? TunnelId { get; set; }

        [Required]
        public Int64 CarriagewayId { get; set; }

        [Required]
        public bool OppositePositioning { get; set; }

        public float Distance { get; set; }

        [System.Text.Json.Serialization.JsonConverter(typeof(SystemTextPointJsonConverter))]
        [Newtonsoft.Json.JsonConverter(typeof(NewtonsoftPointJsonConverter))]
        public Point Location { get; set; }

        public bool Active { get; set; }

        public virtual Tunnel Tunnel { get; set; }

        public virtual Carriageway Carriageway { get; set; }

        public virtual CameraType CameraType { get; set; }

        public virtual List<CountSessionToCamera> CountSessions { get; set; }

        public virtual List<Transit> Transits { get; set; }

        [NotMapped]
        [JsonIgnore]
        public String LocationDescription => Location.ToGeoString();

        [NotMapped]
        [JsonIgnore]
        public String CarriagewayName => Carriageway?.Name;

        [NotMapped]
        [JsonIgnore]
        public String SectionName => Carriageway?.Section?.Name;

        [NotMapped]
        [JsonIgnore]
        public String AuthorityName => Carriageway?.Section?.Authority?.Name;
    }

```

Could you please do a check and let me know ? If you need further infos just ask me.

Thank you in advance for any help.

Federico.

**Comment by fededim** [comment]
@rgudkov-uss No, the workaround was to ignore the foreign key property on the edm model, e.g.

```
        private IEdmModel GetEdmModel()
        {
            var builder = new ODataConventionModelBuilder();

            ...

            builder.EntityType<Camera>().Ignore(c => c.CameraType);

            ...
        }
```

I have just noticed that the code of ClientTypeUtil.cs has changed a lot meanwhile ([here at the time when the bug was opened](https://github.com/OData/odata.net/blob/16a8907b995c458fd7fcb1dc414ffee7dfaaf98a/src/Microsoft.OData.Client/Metadata/ClientTypeUtil.cs#L486) and [now](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Client/Metadata/ClientTypeUtil.cs#L398)) has this issue been addressed somehow ? I would like to try to update the OData packages and test it again but I can't since I have just changed my job :-( However the bug was there at least in the specified version of the OData packages.

**Comment by rgudkov-uss** [comment]
Still the same problem with Microsoft.OData.Client 7.17.0. 
My way to fix it was to change Enum property to string in generated class
