### ISSUE TITLE
 System.ArgumentNullException in Microsoft.OData.Client when using $skiptoken QueryOption

### ISSUE THREAD

**Issue by mviswan** [OData/odata.net#2007]
*System.ArgumentNullException in Microsoft.OData.Client when using $skiptoken QueryOption*

### Assemblies affected

* *Microsoft.OData.Client 7.8.2*

### Reproduce steps
* Followed  [using-blazor-wasm-with-odata-client](https://docs.microsoft.com/en-us/odata/client/using-blazor-wasm-with-odata-client#using-plain-old-clr-objects-pocos) msdn guide 
```
//POCO
public class MyModel
{
        public string Name { get; set; }
        public string Key { get; set; }
        public int Id { get; set; }
}
//ODataServiceContext
    public partial class ODataServiceContext : DataServiceContext
    {
        public ODataServiceContext(Uri serviceRoot) : base(serviceRoot)
        {
            //Add this to override the default HttpWebRequest for making requests in OData Client. 
            HttpRequestTransportMode = HttpRequestTransportMode.HttpClient;

            RetailerProducts = base.CreateQuery<MyModel>("MyModels");
            Format.LoadServiceModel = () => GetEdmModel();
            Format.UseJson();

        }

        private IEdmModel GetEdmModel()
        {
            var builder = new ODataConventionModelBuilder();
            builder
                .EntitySet<MyModel>("MyModels")
                .EntityType
                .HasKey(p => p.Id); // cant invoke any of extn methods  .Count(), .Select(), .Page(null, 100), .Expand(), .Filter() like below
            // builder.EntitySet<Book>("Books").EntityType.HasKey(p => p.Id).Count().Select().Page(null, 100).Expand().Filter();
            return builder.GetEdmModel();
        }

        public DataServiceQuery<MyModel> MyModels{ get; }
    }
```

* in a test class 
```
var dataServiceContext = new ODataServiceContext(new Uri("https://localhost:44353/odata"));
var result = await dataServiceContext.MyModels.AddQueryOption("$skiptoken", "Id-126").ExecuteAsync(); // exception here

```

### Expected result

* skiptoken query parameter is applied and appropriate values are retrieved

### Actual result

* System.ArgumentNullException is thrown

### Stack Trace

```
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.OData.Client.Strings.ALinq_QueryOptionNotSupported(Object p0)
   at Microsoft.OData.Client.ResourceBinder.ValidationRules.RequireLegalCustomQueryOption(Expression e, ResourceExpression target)
   at Microsoft.OData.Client.ResourceBinder.AnalyzeAddCustomQueryOption(MethodCallExpression mce)
   at Microsoft.OData.Client.ResourceBinder.VisitMethodCall(MethodCallExpression mce)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.DataServiceALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ResourceBinder.Bind(Expression e, DataServiceContext context)
   at Microsoft.OData.Client.DataServiceQueryProvider.Translate(Expression e)
   at Microsoft.OData.Client.DataServiceQuery`1.Translate()
   at Microsoft.OData.Client.DataServiceQuery`1.QueryComponents(ClientEdmModel model)
   at Microsoft.OData.Client.DataServiceRequest.CreateExecuteResult(Object source, DataServiceContext context, AsyncCallback callback, Object state, String method)
   at Microsoft.OData.Client.DataServiceRequest.BeginExecute(Object source, DataServiceContext context, AsyncCallback callback, Object state, String method)
   at Microsoft.OData.Client.DataServiceQuery`1.BeginExecute(AsyncCallback callback, Object state)
   at Microsoft.OData.Client.DataServiceContext.<>c__DisplayClass268_0`1.<FromAsync>b__0(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync(Func`3 beginMethod, Func`2 endMethod, Object state)
   at Microsoft.OData.Client.DataServiceContext.FromAsync[TResult](Func`3 beginMethod, Func`2 endMethod, CancellationToken cancellationToken)
   at Microsoft.OData.Client.DataServiceQuery`1.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.OData.Client.DataServiceQuery`1.ExecuteAsync()
```
### Note
* Postman tests with $skiptoken passed and I got expected result

**Comment by KenitoInc** [comment]
Hey @mviswan 
`$skiptoken` is used in server-driven paging where the server sends back partial results as well as a `nextlink` to use to retrieve more results. The `nextlink` may use `$skiptoken` to store state about the request, such as the last read entity.
We don't allow $skiptoken as a query option on OData client. Your request is failing on this line
https://github.com/OData/odata.net/blob/e70f4081ebd6d9b13087503bf2d68290bd0ca43b/src/Microsoft.OData.Client/ALinq/ResourceBinder.cs#L2773

For client side paging, use `skip` and `top` query options. See docs https://docs.microsoft.com/en-us/odata/concepts/queryoptions-overview

**Comment by mviswan** [comment]
Thank you.
