### ISSUE TITLE
Blazor (wasm): Cannot wait on monitors on this runtime.

### ISSUE THREAD

**Issue by Molinware** [OData/odata.net#2044]
I get **Cannot wait on monitors on this runtime.** when calling **FirstOrDefault()**, **ToList()** and so on...

``` C#
// Program.cs

// Add ODataServiceContext Service
builder.Services.AddScoped(sp => new ODataServiceContext(new Uri(builder.HostEnvironment.BaseAddress), model));

// ODataServiceContext Class -> Constructor
public ODataServiceContext(Uri serviceRoot, IEdmModel model) : base(serviceRoot)
{
    this.HttpRequestTransportMode = HttpRequestTransportMode.HttpClient;
    this.Format.LoadServiceModel = () => model;
    this.Format.UseJson();
}
```

```C#
// Calling Odata
this.ODataContext.CreateQuery<TituloReceberPsqDto>("TituloReceberPsqBo").FirstOrDefault();
```

**Comment by gathogojr** [comment]
@Molinware Seems that this error is observed when making synchronous calls.
As a workaround, the alternative is to call ExecuteAsync as opposed to calling the LINQ methods like `FirstOrDefault()` and `ToList()`

**Comment by chrisspre** [comment]
@gathogojr, @ElizabethOkerio  I suspect that in the implementation of the IEnumerable<> returned by CreateQuery there is a blocking call that WASM blocks.

If there was a CreateQueryAsync that returns an `IAsyncEnumerable<>` and uses the async methods on HttpClient
```
public async IAsyncEnumerable<T> CreateQueryAsync<T>(string query);
```
this could work by calling
```
var first = await this.ODataContext.CreateQueryAsync<UserDto>("Users").FirstOrDefault();
```

Just a side note: I was not able to find a `FirstOrDefault` or `ToList` extension method on `IAsyncEnumerable<T>`
But this would be straightforward to implement together with `CreateQueryAsync`
```
public static async Task<List<T>> ToList<T>(this IAsyncEnumerable<T> items)
{
    var result = new List<T>();
    await foreach (var item in items)
    {
        result.Add(item);
    }
    return result;
}
```

**Comment by Molinware** [comment]
> Seems that this error is observed when making synchronous calls.
> As a workaround, the alternative is to call ExecuteAsync as opposed to calling the LINQ methods like FirstOrDefault() and ToList()

@gathogojr Unfortunally I cannot use **ExecuteAsync**, I need to bind an **IQueryable** to the grid, then everything is automated and I have no control over calls, all I do is this:

```C#
private IQueryable<UserDto> ODataIQueryable {get; set; } = this.ODataContext.CreateQueryAsync<UserDto>("Users");

// https://demos.devexpress.com/blazor/BindGridtoData#LargeData
<DxDataGrid DataAsync="@ODataIQueryable">
</DxDataGrid>
```
I have no control over **DxDataGrid** and internally it applies whats needed for the call.

**Example:** If I filter the name in the grid it automatically would do this:

```C#
// I don't call it, the DxDataGrid does this internally
ODataIQueryable.Where(x => x.Name == "ExampleName").ToList()
```

**Comment by Molinware** [comment]
Just complementing the stacktrace for the code above.

```
System.PlatformNotSupportedException: Cannot wait on monitors on this runtime.
    at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
    at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout, Boolean exitContext)
    at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
    at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Task.Wait()
    at Microsoft.OData.Client.HttpClientRequestMessage.<GetResponse>b__41_0()
    at Microsoft.OData.Client.HttpClientRequestMessage.UnwrapAggregateException[HttpWebResponseMessage](Func`1 action)
    at Microsoft.OData.Client.HttpClientRequestMessage.GetResponse()
    at Microsoft.OData.Client.ODataRequestMessageWrapper.GetResponse()
    at Microsoft.OData.Client.DataServiceContext.GetResponseHelper(ODataRequestMessageWrapper request, IAsyncResult asyncResult, Boolean handleWebException)
    at Microsoft.OData.Client.DataServiceContext.GetSynchronousResponse(ODataRequestMessageWrapper request, Boolean handleWebException)
    at Microsoft.OData.Client.RequestInfo.GetSynchronousResponse(ODataRequestMessageWrapper request, Boolean handleWebException)
    at Microsoft.OData.Client.QueryResult.ExecuteQuery()
    at Microsoft.OData.Client.DataServiceRequest.Execute[Object](DataServiceContext context, QueryComponents queryComponents)
    at Microsoft.OData.Client.DataServiceQuery`1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute()
    at Microsoft.OData.Client.DataServiceQuery`1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetEnumerator()
    at System.Linq.Enumerable.SelectEnumerableIterator`2[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DevExtreme.AspNet.Data.Types.AnonType, DevExtreme.AspNet.Data, Version=2.8.0.0, Culture=neutral, PublicKeyToken=982f5dab1439d0f7]].MoveNext()
    at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1[[Genesis.OR.Temp.Pesquisa.ObjetosDto.TituloReceberPsqDto, Genesis.OR.Temp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FilterFromKeys(IEnumerable`1 keyTuples)
    at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.<LoadAsync>d__5[[Genesis.OR.Temp.Pesquisa.ObjetosDto.TituloReceberPsqDto, Genesis.OR.Temp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
    at GenesisWeb.Pages.Login.LoadCustomData(DataSourceLoadOptionsBase options, CancellationToken cancellationToken) in D:\Fontes\Genesis.NET\GenesisWeb\Pages\Login.razor.cs:line 70
```

**Comment by davidyee** [comment]
I also ran into this issue using the latest OData.Client 7.9.0 in a Blazor WASM 6.0.0-preview.3 app. There are two workarounds that appear to work:

## Option 1: Force cast the query after applying the `Where` and then call `ExecuteAsync`:

```csharp
var items = await ((DataServiceQuery<Message>)DataServiceContext.Message.Where(e => e.Id == Message.Id)).ExecuteAsync();
var dsc = new DataServiceCollection<Message>(items);
```

## Option 2: Use a `$filter` on the OData collection instead of on the get by key:

```csharp
// The below line fails with the same exception as reported by the OP
// var items = DataServiceContext.Message.Where(e => e.Id == Message.Id);

// This workaround queries the collection and applies OData $filter
var items = await DataServiceContext.Message.AddQueryOption("$filter", $"id eq {Message.Id}").ExecuteAsync();
var dsc = new DataServiceCollection<Message>(items);
```
