### ISSUE TITLE
Problem with making Connected Services client work.

### ISSUE THREAD

**Issue by hubuk** [OData/odata.net#2047]
Client generated using OData Connected Services 0.12.1 throws exception:
```
Microsoft.OData.ODataException: 'When writing a JSON response, a user model must be specified and the entity set and entity type must be passed to the ODataMessageWriter.CreateODataResourceWriter method or the ODataResourceSerializationInfo must be set on the ODataResource or ODataResourceSet that is being written.'

   at Microsoft.OData.ODataResourceTypeContext.ValidateAndReturn[T](T value
   at Microsoft.OData.ODataResourceTypeContext.get_NavigationSourceName()
   at Microsoft.OData.Evaluation.ODataConventionalIdMetadataBuilder.ComputeId()
   at Microsoft.OData.Evaluation.ODataConventionalIdMetadataBuilder.ComputeAndCacheId()
   at Microsoft.OData.Evaluation.ODataConventionalIdMetadataBuilder.get_ComputedId()
   at Microsoft.OData.Evaluation.ODataConventionalIdMetadataBuilder.GetId()
   at Microsoft.OData.ODataResourceBase.get_Id()
   at Microsoft.OData.Client.Materialization.MaterializerEntry.UpdateEntityDescriptor()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.ReadEntryCore()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryReadEntry(MaterializerEntry& entry)
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.<LazyReadEntries>d__22.MoveNext()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.Read()
   at Microsoft.OData.Client.Materialization.ODataReaderEntityMaterializer.ReadNextFeedOrEntry()
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
   at Microsoft.OData.Client.Materialization.ODataMaterializer.Read()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Program.Main(String[] args)
```

Program code looks like this:
``` C#
MyDataServiceContext context = new MyDataServiceContext(this.ODataV4Uri);
context.Credentials = this.Credentials;
var array = context.Company.ByKey("My Company").Customers.ToArray();
```

Client code was generated using NAV 2017 ODataV4 endpoint.

### Assemblies affected
OData .Net lib 7.8.3 (including source code - 4e263ca4b94d01f2d105d8282c62ec272cfcd1bb)

### Reproduce steps
The issue is probably related to the way I am using the library or generate the client code. I just need information what I am doing wrong and how to fix it.

### Expected result
An information or hint what should I do to make things work.

### Actual result
Exception with message that does not tell me much.

### Additional detail
Exception is being thrown by `Customers.ToArray()` part. `Company.ByKey()` returns correct data. Also `.../Company("My Company")/Customers` responds with correct data in browser.

**Comment by hubuk** [comment]
I found the cause of the error:

Exception is thrown when context metadata is specified as Collection of EntityType
```
{"@odata.context":"https://localhost/Data/ODataV4/$metadata#Collection(Customer)", ...
```

When the context is EntitySet as in 
```
{"@odata.context":"https://services.odata.org/TripPinRESTierService/(S(k2mk43p1teqymtbpbm5q3grc))/$metadata#People", ...
```
everything works as expected.

Is `Collection` in odata.context not supported by the client or is it an invalid odata construct?

**Comment by hubuk** [comment]
I observe the same behaviour when trying to use code generated for TripPinRESTierService.
https://services.odata.org/TripPinRESTierService/(S(k2mk43p1teqymtbpbm5q3grc))/People('russellwhyte')/Trips

``` C#
Trippin.Container container = new Trippin.Container(new Uri("https://services.odata.org/TripPinRESTierService/"));
container.People.ByKey("russellwhyte").Trips.ToArray();
```

Is there anyway to access `Trips` property using odata.net client?

**Comment by hubuk** [comment]
@KenitoInc I saw you provided this example as an explanation here: https://github.com/OData/odata.net/issues/1549#issuecomment-585221252
Is there anything I can do to access this property.

**Comment by marabooy** [comment]
@hubuk could you kindly share your model, from the above post tripin restier service seems to be treating trips as a complex type hence giving the error you are observing. 
[TripinRW service ](https://services.odata.org/v4/(S(1hthk2rtxtoaogoaucumcdia))/trippinservicerw/People('russellwhyte')/Trips) linked here responds with the correct context url.

**Comment by hubuk** [comment]
@marabooy Thanks for your response. You are right TripinRW service is responding with metadata that allows accessing Trips property. Unfortunately the service that I am using in production behaves exactly the same as the (old one I presume) service located at: https://services.odata.org/TripPinRESTierService/$metadata
Here is the model:
``` xml
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="Trippin" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="Person">
        <Key>
          <PropertyRef Name="UserName"/>
        </Key>
        <Property Name="UserName" Type="Edm.String" Nullable="false"/>
        <Property Name="FirstName" Type="Edm.String" Nullable="false"/>
        <Property Name="LastName" Type="Edm.String" MaxLength="26"/>
        <Property Name="MiddleName" Type="Edm.String"/>
        <Property Name="Gender" Type="Trippin.PersonGender" Nullable="false"/>
        <Property Name="Age" Type="Edm.Int64"/>
        <Property Name="Emails" Type="Collection(Edm.String)"/>
        <Property Name="AddressInfo" Type="Collection(Trippin.Location)"/>
        <Property Name="HomeAddress" Type="Trippin.Location"/>
        <Property Name="FavoriteFeature" Type="Trippin.Feature" Nullable="false"/>
        <Property Name="Features" Type="Collection(Trippin.Feature)" Nullable="false"/>
        <NavigationProperty Name="Friends" Type="Collection(Trippin.Person)"/>
        <NavigationProperty Name="BestFriend" Type="Trippin.Person"/>
        <NavigationProperty Name="Trips" Type="Collection(Trippin.Trip)"/>
      </EntityType>
      <EntityType Name="Airline">
        <Key>
          <PropertyRef Name="AirlineCode"/>
        </Key>
        <Property Name="AirlineCode" Type="Edm.String" Nullable="false"/>
        <Property Name="Name" Type="Edm.String"/>
      </EntityType>
      <EntityType Name="Airport">
        <Key>
          <PropertyRef Name="IcaoCode"/>
        </Key>
        <Property Name="Name" Type="Edm.String"/>
        <Property Name="IcaoCode" Type="Edm.String" Nullable="false"/>
        <Property Name="IataCode" Type="Edm.String"/>
        <Property Name="Location" Type="Trippin.AirportLocation"/>
      </EntityType>
      <ComplexType Name="Location">
        <Property Name="Address" Type="Edm.String"/>
        <Property Name="City" Type="Trippin.City"/>
      </ComplexType>
      <ComplexType Name="City">
        <Property Name="Name" Type="Edm.String"/>
        <Property Name="CountryRegion" Type="Edm.String"/>
        <Property Name="Region" Type="Edm.String"/>
      </ComplexType>
      <ComplexType Name="AirportLocation" BaseType="Trippin.Location">
        <Property Name="Loc" Type="Edm.GeographyPoint"/>
      </ComplexType>
      <ComplexType Name="EventLocation" BaseType="Trippin.Location">
        <Property Name="BuildingInfo" Type="Edm.String"/>
      </ComplexType>
      <EntityType Name="Trip">
        <Key>
          <PropertyRef Name="TripId"/>
        </Key>
        <Property Name="TripId" Type="Edm.Int32" Nullable="false"/>
        <Property Name="ShareId" Type="Edm.Guid" Nullable="false"/>
        <Property Name="Name" Type="Edm.String"/>
        <Property Name="Budget" Type="Edm.Single" Nullable="false"/>
        <Property Name="Description" Type="Edm.String"/>
        <Property Name="Tags" Type="Collection(Edm.String)"/>
        <Property Name="StartsAt" Type="Edm.DateTimeOffset" Nullable="false"/>
        <Property Name="EndsAt" Type="Edm.DateTimeOffset" Nullable="false"/>
        <NavigationProperty Name="PlanItems" Type="Collection(Trippin.PlanItem)"/>
      </EntityType>
      <EntityType Name="PlanItem">
        <Key>
          <PropertyRef Name="PlanItemId"/>
        </Key>
        <Property Name="PlanItemId" Type="Edm.Int32" Nullable="false"/>
        <Property Name="ConfirmationCode" Type="Edm.String"/>
        <Property Name="StartsAt" Type="Edm.DateTimeOffset" Nullable="false"/>
        <Property Name="EndsAt" Type="Edm.DateTimeOffset" Nullable="false"/>
        <Property Name="Duration" Type="Edm.Duration" Nullable="false"/>
      </EntityType>
      <EntityType Name="Event" BaseType="Trippin.PlanItem">
        <Property Name="OccursAt" Type="Trippin.EventLocation"/>
        <Property Name="Description" Type="Edm.String"/>
      </EntityType>
      <EntityType Name="PublicTransportation" BaseType="Trippin.PlanItem">
        <Property Name="SeatNumber" Type="Edm.String"/>
      </EntityType>
      <EntityType Name="Flight" BaseType="Trippin.PublicTransportation">
        <Property Name="FlightNumber" Type="Edm.String"/>
        <NavigationProperty Name="Airline" Type="Trippin.Airline"/>
        <NavigationProperty Name="From" Type="Trippin.Airport"/>
        <NavigationProperty Name="To" Type="Trippin.Airport"/>
      </EntityType>
      <EntityType Name="Employee" BaseType="Trippin.Person">
        <Property Name="Cost" Type="Edm.Int64" Nullable="false"/>
        <NavigationProperty Name="Peers" Type="Collection(Trippin.Person)"/>
      </EntityType>
      <EntityType Name="Manager" BaseType="Trippin.Person">
        <Property Name="Budget" Type="Edm.Int64" Nullable="false"/>
        <Property Name="BossOffice" Type="Trippin.Location"/>
        <NavigationProperty Name="DirectReports" Type="Collection(Trippin.Person)"/>
      </EntityType>
      <EnumType Name="PersonGender">
        <Member Name="Male" Value="0"/>
        <Member Name="Female" Value="1"/>
        <Member Name="Unknown" Value="2"/>
      </EnumType>
      <EnumType Name="Feature">
        <Member Name="Feature1" Value="0"/>
        <Member Name="Feature2" Value="1"/>
        <Member Name="Feature3" Value="2"/>
        <Member Name="Feature4" Value="3"/>
      </EnumType>
      <Function Name="GetPersonWithMostFriends">
        <ReturnType Type="Trippin.Person"/>
      </Function>
      <Function Name="GetNearestAirport">
        <Parameter Name="lat" Type="Edm.Double" Nullable="false"/>
        <Parameter Name="lon" Type="Edm.Double" Nullable="false"/>
        <ReturnType Type="Trippin.Airport"/>
      </Function>
      <Function Name="GetFavoriteAirline" IsBound="true" EntitySetPath="person">
        <Parameter Name="person" Type="Trippin.Person"/>
        <ReturnType Type="Trippin.Airline"/>
      </Function>
      <Function Name="GetFriendsTrips" IsBound="true">
        <Parameter Name="person" Type="Trippin.Person"/>
        <Parameter Name="userName" Type="Edm.String" Nullable="false" Unicode="false"/>
        <ReturnType Type="Collection(Trippin.Trip)"/>
      </Function>
      <Function Name="GetInvolvedPeople" IsBound="true">
        <Parameter Name="trip" Type="Trippin.Trip"/>
        <ReturnType Type="Collection(Trippin.Person)"/>
      </Function>
      <Action Name="ResetDataSource"/>
      <Action Name="UpdateLastName" IsBound="true">
        <Parameter Name="person" Type="Trippin.Person"/>
        <Parameter Name="lastName" Type="Edm.String" Nullable="false" Unicode="false"/>
        <ReturnType Type="Edm.Boolean" Nullable="false"/>
      </Action>
      <Action Name="ShareTrip" IsBound="true">
        <Parameter Name="personInstance" Type="Trippin.Person"/>
        <Parameter Name="userName" Type="Edm.String" Nullable="false" Unicode="false"/>
        <Parameter Name="tripId" Type="Edm.Int32" Nullable="false"/>
      </Action>
      <EntityContainer Name="Container">
        <EntitySet Name="People" EntityType="Trippin.Person">
          <NavigationPropertyBinding Path="BestFriend" Target="People"/>
          <NavigationPropertyBinding Path="Friends" Target="People"/>
          <NavigationPropertyBinding Path="Trippin.Employee/Peers" Target="People"/>
          <NavigationPropertyBinding Path="Trippin.Manager/DirectReports" Target="People"/>
        </EntitySet>
        <EntitySet Name="Airlines" EntityType="Trippin.Airline">
          <Annotation Term="Org.OData.Core.V1.OptimisticConcurrency">
            <Collection>
              <PropertyPath>Name</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
        <EntitySet Name="Airports" EntityType="Trippin.Airport"/>
        <Singleton Name="Me" Type="Trippin.Person">
          <NavigationPropertyBinding Path="BestFriend" Target="People"/>
          <NavigationPropertyBinding Path="Friends" Target="People"/>
          <NavigationPropertyBinding Path="Trippin.Employee/Peers" Target="People"/>
          <NavigationPropertyBinding Path="Trippin.Manager/DirectReports" Target="People"/>
        </Singleton>
        <FunctionImport Name="GetPersonWithMostFriends" Function="Trippin.GetPersonWithMostFriends" EntitySet="People"/>
        <FunctionImport Name="GetNearestAirport" Function="Trippin.GetNearestAirport" EntitySet="Airports"/>
        <ActionImport Name="ResetDataSource" Action="Trippin.ResetDataSource"/>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
```

**Comment by marabooy** [comment]
@hubuk from my observation the line [here](https://github.com/OData/odata.net/blob/59bfcdfe1ffb3db11e6173fdc5693380630087ff/src/Microsoft.OData.Core/JsonLight/ODataJsonLightReader.cs#L2346) the reader depends on this context url to understand what it is reading. In this case it tries to check if there is a navigation source for trips as trip is an entity type and since there is none it is unable to consume it.

The only workaround I can think of in this case would be to use something similar to [this](https://docs.microsoft.com/en-us/odata/client/using-httpclient) to customise the returned response context before it is processed while the service is fixing the issue with the context url. Since we introduced [HttpClientrRequestMessage](https://github.com/OData/odata.net/blob/59bfcdfe1ffb3db11e6173fdc5693380630087ff/src/Microsoft.OData.Client/Serialization/HttpClientRequestMessage.cs#L23) the changes you need to do won't be too drastic as you can override the get response and use the transport mode which utilizes [HttpClient](https://docs.microsoft.com/en-us/odata/client/using-blazor-wasm-with-odata-client#using-microsoft-odata-connected-service)  
```csharp
  dataServiceContext.HttpRequestTransportMode = HttpRequestTransportMode.HttpClient; 
```

**Comment by hubuk** [comment]
@marabooy My knowledge about OData internals is very limited, so sorry for my probably lame questions. Please confirm if my understanding is correct. You suggest to use custom implementation of GetStream method to substitute `{"@odata.context":"https://services.odata.org/TripPinRESTierService/(S(k2mk43p1teqymtbpbm5q3grc))/$metadata#Collection(Trippin.Trip)"` element returned in response to something else that OData client understands?

**Comment by marabooy** [comment]
@hubuk yes this is a workaround you could use until the upstream service is patched to return the correct context.
