### ISSUE TITLE
Microsoft.OData.ODataException: Cannot convert the literal ‘2026-06-08T13:06:24’ to the expected type 'Edm.DateTimeOffset'

### ISSUE THREAD

**Issue by akshukla25** [OData/odata.net#2113]
When a POST request has DateTime in the request body, the request fails with this exception. There should be a way to set the default time zone when DateTime param is passed so as to not break the clients.

### Assemblies affected

OData.Core 7.7.3

### Reproduce steps

POST ~/oauth2PermissionGrants
{
  "clientId": "client-id",
  "consentType": "AllPrincipals",
 "resourceId":"resource-id",
 "expiryTime": "2026-06-08T13:06:24"
}

### Additional detail
ODataMessageReader messageReader =
                new ODataMessageReader(odataRequestMessage, GetReaderSettings(), edmModel))
entryReader = messageReader.CreateODataResourceReader(entitySet, entityType);
entryReader .Read() 

reader.Read() is throwing this exception. 

Using HttpRequestBase Class (System.Web) | Microsoft Docs. (.NET Framework 4.6.2). 

https://docs.microsoft.com/en-us/odata/webapi/datetime-support mentions HttpConfiguration but we don't use this.

StackTrace:
Microsoft.OData.ODataException: Cannot convert the literal ‘2026-06-08T13:06:24’ to the expected type 'Edm.DateTimeOffset'.;
   at Microsoft.OData.ODataPayloadValueConverter.ConvertFromPayloadValue(Object value, IEdmTypeReference edmTypeReference)
   at Microsoft.OData.JsonLight.ODataJsonLightReaderUtils.ConvertValue(Object value, IEdmPrimitiveTypeReference primitiveTypeReference, ODataMessageReaderSettings messageReaderSettings, Boolean validateNullValue, String propertyName, ODataPayloadValueConverter converter)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadPrimitiveValue(Boolean insideJsonObjectValue, IEdmPrimitiveTypeReference expectedValueTypeReference, Boolean validateNullValue, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String payloadTypeName, IEdmTypeReference expectedTypeReference, PropertyAndAnnotationCollector propertyAndAnnotationCollector, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideResourceValue, String propertyName, Nullable`1 isDynamicProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadEntryDataProperty(IODataJsonLightReaderResourceState resourceState, IEdmProperty edmProperty, String propertyTypeName)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithValue(IODataJsonLightReaderResourceState resourceState, String propertyName, Boolean isDeltaResourceSet)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.<>c__DisplayClass9_0.<ReadResourceContent>b__0(PropertyParsingResult propertyParsingResult, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.StartReadingResource()
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceSetItemStart(PropertyAndAnnotationCollector propertyAndAnnotationCollector, SelectedPropertiesNode selectedProperties)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(PropertyAndAnnotationCollector propertyAndAnnotationCollector)
   at Microsoft.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)

**Comment by akshukla25** [comment]
### csdl

```
<EntityType Name="OAuth2PermissionGrant">
<Key><PropertyRef Name="id" /></Key>
<Property Name="clientId" Type="Edm.String" Nullable="false" />
<Property Name="consentType" Type="Edm.String" />
<Property Name="expiryTime" Type="Edm.DateTimeOffset" />
<Property Name="id" Type="Edm.String" />
<Property Name="principalId" Type="Edm.String" />
<Property Name="resourceId" Type="Edm.String" Nullable="false" />
<Property Name="scope" Type="Edm.String" />
<Property Name="startTime" Type="Edm.DateTimeOffset" />
</EntityType>
```

**Comment by The-Futurist** [comment]
Is there any workaround for this? I'm dealing with a vendor that is omitting time zone from their datetime fields and I get the same exception. Of course their response data is at fault, it does not conform to OData v4 in which time zone is not optional, it must always be present.

But I need workaround this somehow, this simple call crashes:

```cs
var students = ctr.Students.Where(s => s.LastName.Contains("son")).ToList();
```

With

`
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryRead()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryStartReadFeedOrEntry()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryReadEntry(MaterializerEntry& entry)
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.<LazyReadEntries>d__31.MoveNext()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.Read()
   at Microsoft.OData.Client.Materialization.ODataReaderEntityMaterializer.ReadNextFeedOrEntry()
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
   at Microsoft.OData.Client.Materialization.ODataMaterializer.Read()
   at Microsoft.OData.Client.ObjectMaterializer.MoveNextInternal()
   at Microsoft.OData.Client.ObjectMaterializer.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__36`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ODataClientTest1.Program.Main(String[] args) in D:\Git\GitHub\NcuGit\applications\sandbox\Hugh\ODataClientTest1\NCU.Anthology.Console\Program.cs:line 19
`

I'm using .net 9, no idea if there's a survival option in .Net 10.

Is there any workaround at all?
