### ISSUE TITLE
An OData URI provided by Kestrel may fail to parse

### ISSUE THREAD

**Issue by gklittlejohn** [OData/odata.net#2117]
I'm attempt to process an OData URL using ODataUriParser. This URL is passed through from ASP.NET Core running on Kestrel.
The path may contain keys with encoded values i.e. Entity('key%2F'). Kestrel decodes the path prior to creating the http context, I'm not sure it is possible to get the raw path ([issue](https://github.com/dotnet/aspnetcore/issues/30655#issuecomment-792941076)). So the path at the point I can pass it to the URI parser would contain Entity('key/'). The OData parser throws an exception when used.

### Assemblies affected

I can see this in 7.9.0 libraries.

### Reproduce steps

Use ODataUriParser with a url containing a path with special characters that have already be decoded.

### Expected result

ODataUriParser to be able to handle URLs where the path has been decoded already.

### Actual result

Exceptions may be thrown.

### Additional detail
The parser appears to decode the path. This means in the case of using with Kestrel the path will be decoded twice.

Microsoft.OData.ODataException
  HResult=0x80131509
  Message=Bad Request - Error in query syntax.
  Source=Microsoft.OData.Core
  StackTrace:
   at Microsoft.OData.UriParser.ODataPathParser.ExtractSegmentIdentifierAndParenthesisExpression(String segmentText, String& identifier, String& parenthesisExpression)
   at Microsoft.OData.UriParser.ODataPathParser.CreateFirstSegment(String segmentText)
   at Microsoft.OData.UriParser.ODataPathParser.ParsePath(ICollection`1 segments)
   at Microsoft.OData.UriParser.ODataPathFactory.BindPath(ICollection`1 segments, ODataUriParserConfiguration configuration)
   at Microsoft.OData.UriParser.ODataUriParser.ParsePathImplementation()
   at Microsoft.OData.UriParser.ODataUriParser.Initialize()
   at Microsoft.OData.UriParser.ODataUriParser.ParsePath()

**Comment by gklittlejohn** [comment]
I was able to get the raw path and query using [HttpRequestFeature.RawTarget](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.ihttprequestfeature.rawtarget). This could be parsed successfully using the ODataUriParser.
