### ISSUE TITLE
ArgumentOutOfRangeException for MinDate with UTC+2

### ISSUE THREAD

**Issue by AntiGuide** [OData/odata.net#2195]
I tried to retrieve a Microsoft.OData.Edm.Date and use it directly as a .NET DateTime. The Edm.Date is the MinDate (01.01.0001).
It throws an exception when convertig the date to my local timezone (UTC+2).

### Assemblies affected

Microsoft.OData.Client, Version=7.8.3.0

### Reproduce steps

Set system to UTC+2 (presumably all positive values) and try to request a date set to min value.

### Expected result

I would expect to have the value clamped or have a setting to enable this behaviour.

### Actual result

This error gets thrown:
```
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at System.DateTimeOffset..ctor(DateTime dateTime, TimeSpan offset)
   at System.Xml.Schema.XsdDateTime.op_Implicit(XsdDateTime xdt)
   at System.Xml.XmlConvert.ToDateTimeOffset(String s)
   at Microsoft.OData.Client.PlatformHelper.ConvertStringToDateTimeOffset(String text)
   at Microsoft.OData.Client.PlatformHelper.ConvertStringToDateTime(String text)
   at Microsoft.OData.Client.DateTimeTypeConverter.Parse(String text)
   at Microsoft.OData.Client.ClientConvert.ChangeType(String propertyValue, Type propertyType)
   at Microsoft.OData.Client.Materialization.PrimitivePropertyConverter.ConvertNonSpatialValue(Object value, Type targetType)
   at Microsoft.OData.Client.Materialization.PrimitivePropertyConverter.ConvertValueIfNeeded(Object value, Type targetType)
   at Microsoft.OData.Client.Materialization.PrimitivePropertyConverter.ConvertPrimitiveValue(Object value, Type propertyType)
   at Microsoft.OData.Client.Materialization.StructuralValueMaterializationPolicy.MaterializePrimitiveDataValue(Type type, ODataProperty property)
   at Microsoft.OData.Client.Materialization.StructuralValueMaterializationPolicy.MaterializeDataValues(ClientTypeAnnotation actualType, IEnumerable`1 values, UndeclaredPropertyBehavior undeclaredPropertyBehavior)
   at Microsoft.OData.Client.Materialization.EntryValueMaterializationPolicy.MaterializeResolvedEntry(MaterializerEntry entry, Boolean includeLinks)
   at Microsoft.OData.Client.Materialization.EntryValueMaterializationPolicy.Materialize(MaterializerEntry entry, Type expectedEntryType, Boolean includeLinks)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.DirectMaterializePlan(ODataEntityMaterializer materializer, MaterializerEntry entry, Type expectedEntryType)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializerInvoker.DirectMaterializePlan(Object materializer, Object entry, Type expectedEntryType)
   at Microsoft.OData.Client.ProjectionPlan.Run(ODataEntityMaterializer materializer, ODataResource entry, Type expectedType)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
   at Microsoft.OData.Client.Materialization.ODataMaterializer.Read()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
```

**Comment by KenitoInc** [comment]
Hey @AntiGuide 
Kindly share the metadata and also the response payload from the service.

**Comment by chrisspre** [comment]
Just for the record, the two lines
```csharp
var x = XmlConvert.ToDateTimeOffset("0001-01-01T00:00:00+02:00");
System.Console.WriteLine("{0:O}", x);
```
throws the same exception. I assume it is because there is just no underlying representation for this time, `x.UtcTicks` is 0 for "0001-01-01T00:00:00+00:00"

**Comment by AntiGuide** [comment]
Hi @KenitoInc 
I can't give you a complete copy of everything as this happened in a corporate environment but I can give you samples of the relevant parts.
This is the date from the response:
`GeburtsDatum: "0001-01-01"`
And this is the metadata property:
`<Property Name="GeburtsDatum" Type="Edm.Date">`

What @chrisspre said is also true. This seems to be a general issue when using `ToDateTimeOffset`. What I am hoping for is an option to disable timezone conversion in the OData library as in our case every date is already in my timezone.

**Comment by xuzhg** [comment]
Close it. ODL 9.x is moved to System.DateOnly and System.TimeOnly. Please file new issue if it's still concerned.
