### ISSUE TITLE
OData Core throws exception causing the process to crash

### ISSUE THREAD

**Issue by sky0311** [OData/odata.net#2206]
OData Core throws exception causing the process to crash

### Assemblies affected

OData .Net lib 7.x*

### Expected result

The process will not be crashed

### Actual result

Process crashed giving watson dump

### Additional detail

WATSON Dump Stack Trace :

-- Exception Object BEGIN ----------------------
System.ExecutionEngineException
at GCFrame
at GCFrame
at GCFrame
at HelperMethodFrame_2OBJ
at System.Reflection.Assembly.GetTypes()
at Microsoft.AspNet.OData.TypeHelper.GetLoadedTypes(Microsoft.AspNet.OData.Interfaces.IWebApiAssembliesResolver)
at Microsoft.AspNet.OData.Builder.ODataConventionModelBuilder.BuildDerivedTypesMapping(Microsoft.AspNet.OData.Interfaces.IWebApiAssembliesResolver)
at System.Lazy`1[[System.__Canon, mscorlib]].CreateValue()
at System.Lazy`1[[System.__Canon, mscorlib]].LazyInitValue()
at Microsoft.AspNet.OData.Builder.ODataConventionModelBuilder.InferEdmTypeFromDerivedTypes(System.Type, Microsoft.AspNet.OData.Builder.PropertyKind ByRef)
at Microsoft.AspNet.OData.Builder.ODataConventionModelBuilder.TryGetPropertyTypeKind(System.Type, Microsoft.AspNet.OData.Builder.IEdmTypeConfiguration ByRef, Microsoft.AspNet.OData.Builder.PropertyKind ByRef)
at Microsoft.AspNet.OData.Builder.ODataConventionModelBuilder.GetPropertyType(System.Reflection.PropertyInfo, Boolean ByRef, Microsoft.AspNet.OData.Builder.IEdmTypeConfiguration ByRef)
at Microsoft.AspNet.OData.Builder.ODataConventionModelBuilder.MapStructuralType(Microsoft.AspNet.OData.Builder.StructuralTypeConfiguration)
at Microsoft.AspNet.OData.Builder.ODataConventionModelBuilder.MapTypes()
at Microsoft.AspNet.OData.Builder.ODataConventionModelBuilder.GetEdmModel()
at Microsoft.Exchange.Admin.Library.RestApi.ServiceConfig.GetEdmModel()
at Microsoft.Exchange.Admin.Library.RestApi.ServiceConfig.SetupRoutes(System.Web.Http.HttpConfiguration)
at System.Web.Http.GlobalConfiguration.Configure(System.Action`1〈System.Web.Http.HttpConfiguration〉)
at Microsoft.Exchange.Admin.Library.Global.RegisterRestCmdlet()
at Microsoft.Exchange.Admin.Library.Global.Application_Start(System.Object, System.EventArgs)
at DebuggerU2MCatchHandlerFrame
at HelperMethodFrame_PROTECTOBJ
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
at System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
at System.Web.HttpApplication.InvokeMethodWithAssert(System.Reflection.MethodInfo, Int32, System.Object, System.EventArgs)
at System.Web.HttpApplication.ProcessSpecialRequest(System.Web.HttpContext, System.Reflection.MethodInfo, Int32, System.Object, System.EventArgs, System.Web.SessionState.HttpSessionState)
at System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(System.Web.HttpContext, System.Web.HttpApplication)
at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr, System.Web.HttpContext, System.Reflection.MethodInfo[])
at System.Web.HttpApplication.InitSpecial(System.Web.HttpApplicationState, System.Reflection.MethodInfo[], IntPtr, System.Web.HttpContext)
at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr, System.Web.HttpContext)
at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr)
at DomainNeutralILStubClass.IL_STUB_COMtoCLR(Int64)
at ContextTransitionFrame
at ComMethodFrame

-- Exception Object END ------------------------

**Comment by chrisspre** [comment]
https://stackoverflow.com/a/4104845

**Comment by xuzhg** [comment]
@sky0311 Can you ignore some certain types to avoid getting the exception?

or can you use 'IWebApiAssembliesResolver' to exclude the failing assembly?

**Comment by KenitoInc** [comment]
Closing this issue due to inactivity. If this issue still persists, feel free to create a new issue.
