### ISSUE TITLE
How to do nested $expand?

### ISSUE THREAD

**Issue by danleydmello** [OData/odata.net#2211]
I am trying to query an entity using nested expand to get the related entities.
`e.g  queryContainer.Persons.Expand("Address($expand=Location)").ExecuteAsync();`
These are cardinality one relationships.

I get the results as expected from the Odata service but the Odata client gives error:

> Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
>       Unhandled exception rendering component: The Id cannot be computed, since the navigation source 'Location' cannot be resolved to a known entity set from model.
> Microsoft.OData.ODataException: The Id cannot be computed, since the navigation source 'Asset' cannot be resolved to a known entity set from model.
>    at Microsoft.OData.Evaluation.ODataConventionalIdMetadataBuilder.ComputeAndCacheId()
>    at Microsoft.OData.Evaluation.ODataConventionalIdMetadataBuilder.get_ComputedId()
>    at Microsoft.OData.Evaluation.ODataConventionalIdMetadataBuilder.GetId()
>    at Microsoft.OData.ODataResourceBase.get_Id()
>    at Microsoft.OData.Client.Materialization.MaterializerEntry.UpdateEntityDescriptor()
>    at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.ReadEntryCore()

I know the Location is in the model because if I try this query, odata client works:
`e.g  queryContainer.Address.Expand("Location").ExecuteAsync();`

**Comment by danleydmello** [comment]
It works when this.MergeOption = MergeOption.NoTracking; 
This is okay for me as my application is Readonly and I don't need tracking on.

**Comment by habex-ch** [comment]
Any news on this issue?
I really don't like adding `MergeOption.NoTracking;`

**Comment by TCSmith05** [comment]
@habex-ch 
I've posted a solution to this in StackOverflow previously:
https://stackoverflow.com/questions/60188656/the-id-cannot-be-computed-since-the-navigation-source-values-cannot-be-resolv/66592953#66592953

The problem (in the 3 cases I have had) was that the OData service didn't have a key defined for the entity in the error.
If you can update the OData service, you can specify the key in the implementation of the IModelConfiguring

So for an EntityType named "Foo" with an Id field "id":

`
namespace MyProject.Api.Configuration.Model_Configurations
{
    public class ValueModelConfiguration : IModelConfiguration
    {
        public void Apply(ODataModelBuilder builder, ApiVersion apiVersion)
        {
            builder.EntitySet<Foo>(nameof(Foo)).EntityType.HasKey(v => v.id);
            // other configurations for your entity may be here
        }
    }
}
`

So for OP's original exception where "Location" is the EntityType, you would replace "Foo" with "Location".

Build the OData service, update your Connected Service in your project to use this new version, and the problem should be resolved for that particular EntityType. Hope that helps.

**Comment by gathogojr** [comment]
Solution provided in the comments
