### ISSUE TITLE
Identifier cannot start with a digit / number in $select clause

### ISSUE THREAD

**Issue by lf-novelt** [OData/odata.net#2219]
The Odata `ParseSelectAndExpand` method will fail if the `$select` clause contains a **property name starting with a digit**, like `$select=NEW_CASES,TOTAL_CASES,2_COL_NAME` even though the underlying field exists in the EdmModel and is serialized properly when no `$select` clause is set.

![image](https://user-images.githubusercontent.com/46479127/137163278-34f0f5d0-8039-49a3-bd93-e0125bf4d36d.png)

![image](https://user-images.githubusercontent.com/46479127/137163357-2205c45d-c8f6-4891-b7c7-986be56477e8.png)

### Assemblies affected
https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/UriParser/ExpressionLexer.cs#L194-L204

### Reproduce steps

Generate a dynamic ODATA model like in  https://github.com/OData/ODataSamples/tree/master/WebApiCore/DynamicEdmModelCreation.
Create a `new EdmEntityType` with a property like `entityType.AddStructuralProperty("2_COL_NAME", EdmPrimitiveTypeKind.Int16` .
Try to query this property in the $select clause.

### Expected result

Parse the $select clause as expected

### Actual result

`{"error":{"code":"Microsoft.OData.ODataException","message":"An identifier was expected at position 5."}}`

### Additional detail

<details>
  <summary>Error stacktrace</summary>

```
 at Microsoft.OData.UriParser.ExpressionToken.GetIdentifier()
  at Microsoft.OData.UriParser.SelectExpandTermParser.ParseSegment(PathSegmentToken previousSegment, Boolean allowRef)
  at Microsoft.OData.UriParser.SelectExpandTermParser.ParseTerm(Boolean allowRef)
  at Microsoft.OData.UriParser.SelectExpandParser.ParseSingleSelectTerm()
  at Microsoft.OData.UriParser.SelectExpandParser.ParseCommaSeparatedSelectList(Func`2 ctor, Func`1 termParsingFunc)
  at Microsoft.OData.UriParser.SelectExpandSyntacticParser.Parse(String selectClause, String expandClause, IEdmStructuredType parentStructuredType, ODataUriParserConfiguration configuration, ExpandToken& expandTree, SelectToken& selectTree)
  at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpandImplementation(String select, String expand, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
  at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpand()
  at Microsoft.AspNet.OData.Query.Validators.SelectExpandQueryValidator.Validate(SelectExpandQueryOption selectExpandQueryOption, ODataValidationSettings validationSettings)
  at Microsoft.AspNet.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)
```
</details>

The `IsValidStartingCharForIdentifier` whose code is below does not allow for a digit. I guess it's related to the same rule in C# not allowing to have property member starting with a number. But not only C# can be serialized to Odata. 

Can we be more tolerant in the `IsValidStartingCharForIdentifier` rule to **support digits as well as valid starting char** for Identifiers?

https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/UriParser/ExpressionLexer.cs#L194-L204

https://github.com/OData/odata.net/blob/64bed784177b9202b73c4510d2461bebf5ad03b7/src/Microsoft.OData.Core/UriParser/ExpressionLexer.cs#L194-L204

Note the `IsValidNonStartingCharForIdentifier` just below supports digits correctly

https://github.com/OData/odata.net/blob/64bed784177b9202b73c4510d2461bebf5ad03b7/src/Microsoft.OData.Core/UriParser/ExpressionLexer.cs#L212-L220

**Comment by habbes** [comment]
@lf-novelt Based on OData syntax rules, an identifier cannot start with a digit. With respect to that, the validator is behaving correctly. How was the `EdmModel` generated? Was it built manually? The model is not validated automatically when being constructed.

**Comment by lf-novelt** [comment]
hello @habbes, my model is generated dynamically from a database structure, SQL rules being different (a column name can start by a digit), it seems it would need some mapping rules to be properly mapped to an OData endpoint.

Thanks for the answer anyway, would you have any insight on why the OData syntax rules prevent a leading digit and how I can easily map a SQL name to valid OData?

**Comment by habbes** [comment]
@lf-novelt Yes, I think doing some mapping from the DB column to the OData property would be necessary.

I don't have the reason on the top of my head, but this in line with identifier rules in many programming languages. I'm not sure if that is the reason though. For many programming languages, you can have numerical literals like `0.2f`, `10m`, etc. which would be ambiguous if identifiers could also start with digits. But this isn't really an issue with OData. So I'm not sure what the reason behind it was. But nevertheless, the syntax rules are defined in the spec.
