### ISSUE TITLE
Client materialization of IEnumerable

### ISSUE THREAD

**Issue by Robelind** [OData/odata.net#2262]
When the entity contains an IEnumerable, the client fails to materialize it when the request is for a function.

### Assemblies affected
Microsoft.OData.Client 7.9.4
Microsoft.AspNetCore.OData 8.0.4

### Reproduce steps
API:

```
services.AddControllers().AddOData(opt => opt.AddRouteComponents("api", GetEdmModel()).EnableQueryFeatures());
private static IEdmModel GetEdmModel()
{
    ODataConventionModelBuilder builder = new ODataConventionModelBuilder();

    builder.EntitySet<TestA>("TestAs");
    builder.Function("Func").ReturnsFromEntitySet<TestA>("TestAs");

    return builder.GetEdmModel();
}

public class TestAsController : ODataController
{
    [HttpGet]
    [EnableQuery]
    public IActionResult Get()
    {
        return(Ok(new[] { new TestA {Id = 1}, new TestA { Id = 2 } }));
    }

    [HttpGet("/api/Func()")]
    public IActionResult Func()
    {
        return(Ok(new TestA { Id = 1 }));
    }
}

public class TestA
{
    public int Id { get; set; }
    public int Prop { get; set; }
    public IEnumerable<string> Props { get; set; }
}

```
Client:
```
public class ODataServiceContext : DataServiceContext
{
    public ODataServiceContext(Uri serviceRoot) : base(serviceRoot)
    {
        HttpRequestTransportMode = HttpRequestTransportMode.HttpClient;
        TestAs = base.CreateQuery<TestA>("TestAs");
        Test = base.CreateFunctionQuerySingle<TestA>("", "Func", false);
        Format.LoadServiceModel = GetEdmModel;
        Format.UseJson();
    }
    
    private IEdmModel GetEdmModel()
    {
        ODataConventionModelBuilder builder = new ODataConventionModelBuilder();

        builder.EntitySet<TestA>("TestAs");
        builder.Function("Func").ReturnsFromEntitySet<TestA>("TestAs");

        return builder.GetEdmModel();
    }

    public DataServiceQuery<TestA> TestAs { get; }
    public DataServiceQuerySingle<TestA> Test { get; }
}

ODataServiceContext context = new(new("https://localhost:44383/api"));
var request1 = await context.TestAs.ExecuteAsync();
TestA request2 = await context.Test.GetValueAsync();

```
Returned data for `request1`:
`{"@odata.context":"https://localhost:44383/api/$metadata#TestAs","value":[{"Id":1,"Prop":0,"Props":[]},{"Id":2,"Prop":0,"Props":[]}]}`

Returned data for `request2`:
`{"@odata.context":"https://localhost:44383/api/$metadata#TestAs/$entity","Id":1,"Prop":0,"Props":[]}`

### Expected result
The client should be able to materialize TestA-objects from the data returned from request1 and request2.

### Actual result
Objects are correctly materialized for request1.
request2 fails with:
```
Unhandled exception rendering component: The complex type 'System.Collections.Generic.IEnumerable`1[System.String]' has no settable properties.
System.InvalidOperationException: The complex type 'System.Collections.Generic.IEnumerable`1[System.String]' has no settable properties.
   at Microsoft.OData.Client.ClientEdmModel.ValidateComplexType(Type type, EdmTypeCacheValue cachedEdmType)
   at Microsoft.OData.Client.ClientEdmModel.GetOrCreateEdmType(Type type)
   at Microsoft.OData.Client.ClientEdmModel.CreateEdmProperty(IEdmStructuredType declaringType, PropertyInfo propertyInfo)
   at Microsoft.OData.Client.ClientEdmModel.<>c__DisplayClass37_0.<GetOrCreateEdmTypeInternal>b__5(EdmComplexTypeWithDelayLoadedProperties complexType)
   at Microsoft.OData.Client.Providers.EdmComplexTypeWithDelayLoadedProperties.EnsurePropertyLoaded()
   at Microsoft.OData.Client.Providers.EdmComplexTypeWithDelayLoadedProperties.get_DeclaredProperties()
   at Microsoft.OData.Client.Metadata.ClientTypeAnnotation.DiscoverEdmProperties()+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1[[Microsoft.OData.Edm.IEdmProperty, Microsoft.OData.Edm, Version=7.9.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[IEdmProperty](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[IEdmProperty](IEnumerable`1 source)
   at Microsoft.OData.Client.Metadata.ClientTypeAnnotation.EdmProperties()
   at Microsoft.OData.Client.Metadata.ClientTypeAnnotation.BuildPropertyCache()
   at Microsoft.OData.Client.Metadata.ClientTypeAnnotation.GetProperty(String propertyName, UndeclaredPropertyBehavior undeclaredPropertyBehavior)
   at Microsoft.OData.Client.Materialization.StructuralValueMaterializationPolicy.MaterializeDataValues(ClientTypeAnnotation actualType, IEnumerable`1 values, UndeclaredPropertyBehavior undeclaredPropertyBehavior)
   at Microsoft.OData.Client.Materialization.EntryValueMaterializationPolicy.MaterializeResolvedEntry(MaterializerEntry entry, Boolean includeLinks)
   at Microsoft.OData.Client.Materialization.EntryValueMaterializationPolicy.Materialize(MaterializerEntry entry, Type expectedEntryType, Boolean includeLinks)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.DirectMaterializePlan(ODataEntityMaterializer materializer, MaterializerEntry entry, Type expectedEntryType)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializerInvoker.DirectMaterializePlan(Object materializer, Object entry, Type expectedEntryType)
   at Microsoft.OData.Client.ProjectionPlan.Run(ODataEntityMaterializer materializer, ODataResource entry, Type expectedType)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
   at Microsoft.OData.Client.Materialization.ODataMaterializer.Read()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__38`1[[CompactStore.DTO.TestA, CompactStore.DTO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TestA](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TestA](IEnumerable`1 source)
   at Microsoft.OData.Client.DataServiceQuerySingle`1[[CompactStore.DTO.TestA, CompactStore.DTO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].EndGetValue(IAsyncResult asyncResult)

```

Changing `public IEnumerable<string> Props { get; set; }` to `public List<string> Props { get; set; }`
makes request2 also work.

**Comment by KenitoInc** [comment]
@Robelind 
This is my repro, and it works well. I can't recreate the issue.
Note: I am using OData client with OData connected service to generate the proxy classes.

OData Client
```csharp
    class Program
    {
        static void Main(string[] args)
        {
            Container context = new Container(new Uri("http://localhost:5000/odata"));            
            HandleFunctions(context).Wait();
        }

        private static async Task HandleFunctions(Container context)
        {
            var request1 = await context.TestAs.ExecuteAsync();

            foreach(TestA testA in request1)
            {
                Console.WriteLine($"Id: {testA.Id}, Prop: {testA.Prop}");
            }

            // Option 1
            DataServiceQuerySingle<TestA> Test = context.CreateFunctionQuerySingle<TestA>("", "Func", false);
            TestA request2a = await Test.GetValueAsync();
            Console.WriteLine($"Id: {request2a.Id}, Prop: {request2a.Prop}");

            // Option 2
            TestA request2b = await context.Func().GetValueAsync();
            Console.WriteLine($"Id: {request2b.Id}, Prop: {request2b.Prop}");
        }
    }
```

Model
```csharp
    public class TestA
    {
        public int Id { get; set; }
        public int Prop { get; set; }
        public IEnumerable<string> Props { get; set; }
        //public List<string> Props { get; set; }
    }
```
Controller
```csharp
    [HttpGet("/odata/Func()")]
    public IActionResult Func()
    {
        return (Ok(new TestA { Id = 1 }));
    }
```

Model builder
```csharp
ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
builder.EntitySet<TestA>("TestAs");
builder.Function("Func").ReturnsFromEntitySet<TestA>("TestAs");
return builder.GetEdmModel();
```

**Comment by ElizabethOkerio** [comment]
It seems the issue could not be reproduced and the client didn't respond. Closing the issue and feel free to reopen if you continue experiencing the issue.
