### ISSUE TITLE
Count in Blazor wasm

### ISSUE THREAD

**Issue by Robelind** [OData/odata.net#2265]
How to do count in Blazor wasm?

### Assemblies affected

Microsoft.OData.Client 7.9.4

### Reproduce steps
Case 1:
```
DataServiceQuery<Test> Tests { get; set; }
int count = Tests.Count();
```
Case 2:
`OperationResponse result = context.ExecuteAsync(".../Tests/$count"), "GET");`
### Expected result
Being able to retrieve the count.

### Actual result
Case 1:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot wait on monitors on this runtime.
System.PlatformNotSupportedException: Cannot wait on monitors on this runtime.
   at System.Threading.Monitor.ObjWait(Int32 millisecondsTimeout, Object obj)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.OData.Client.HttpClientRequestMessage.<GetResponse>b__41_0()
   at Microsoft.OData.Client.HttpClientRequestMessage.UnwrapAggregateException[HttpWebResponseMessage](Func`1 action)
   at Microsoft.OData.Client.HttpClientRequestMessage.GetResponse()
   at Microsoft.OData.Client.ODataRequestMessageWrapper.GetResponse()
   at Microsoft.OData.Client.DataServiceContext.GetResponseHelper(ODataRequestMessageWrapper request, IAsyncResult asyncResult, Boolean handleWebException)
   at Microsoft.OData.Client.DataServiceContext.GetSynchronousResponse(ODataRequestMessageWrapper request, Boolean handleWebException)
   at Microsoft.OData.Client.RequestInfo.GetSynchronousResponse(ODataRequestMessageWrapper request, Boolean handleWebException)
   at Microsoft.OData.Client.QueryResult.ExecuteQuery()
   at Microsoft.OData.Client.DataServiceRequest.GetValue[Int32](DataServiceContext context, Func`2 parseQueryResultFunc)
   at Microsoft.OData.Client.DataServiceQueryProvider.ReturnSingleton[Int32](Expression expression)
   at Microsoft.OData.Client.DataServiceQueryProvider.Execute[Int32](Expression expression)
   at System.Linq.Queryable.Count[Test](IQueryable`1 source)

```
Case 2:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The complex type 'System.Object' has no settable properties.
System.InvalidOperationException: The complex type 'System.Object' has no settable properties.
   at Microsoft.OData.Client.ClientEdmModel.ValidateComplexType(Type type, EdmTypeCacheValue cachedEdmType)
   at Microsoft.OData.Client.ClientEdmModel.GetOrCreateEdmType(Type type)
   at Microsoft.OData.Client.Materialization.ODataMessageReaderMaterializer.ReadImplementation()
   at Microsoft.OData.Client.Materialization.ODataMaterializer.Read()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__38`1[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Linq.Enumerable.Any[Object](IEnumerable`1 source)
   at Microsoft.OData.Client.DataServiceContext.EndExecute(IAsyncResult asyncResult)

```

**Comment by chrisspre** [comment]
https://github.com/OData/odata.net/issues/1970

**Comment by gathogojr** [comment]
https://github.com/OData/odata.net/issues/1970 provides useful information to unblock the reporter
