### ISSUE TITLE
ArgumentNullException for $filter IN operator on dynamic property

### ISSUE THREAD

**Issue by syprieur** [OData/odata.net#2270]
Use of the `in` operator in a `$filter` on a **dynamic property** results in an unhandled ODL exception (`ArgumentNullException`).

### Assemblies affected

All up to 7.9.4.

### Reproduce steps

``` cs
// Setup basic model
var model = new EdmModel();
var user = model.AddEntityType("graph", "user", baseType: null, isAbstract: false, isOpen: true, hasStream: false);
var container = model.AddEntityContainer("graph", "service");
container.AddEntitySet("users", user);

// Setup URI parser
var parser = new ODataUriParser(model, new System.Uri("/users?$filter=openPropertyFoo in ('bar')", System.UriKind.Relative));
parser.ParsePath();

// This throws an ArgumentNullException:
var filter = parser.ParseFilter();
```

### Expected result

Either:
 - a valid FilterClause.
Or:
 - ODL Exception calling out that $filter on dynamic properties is not supported

### Actual result

Unhandled exception thrown by ODL:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'elementType');
   at Microsoft.OData.Edm.EdmUtil.CheckArgumentNull[T](T value, String parameterName)
   at Microsoft.OData.Edm.EdmCollectionType..ctor(IEdmTypeReference elementType)
   at Microsoft.OData.UriParser.InBinder.BindInOperator(InToken inToken, BindingState state)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()
   at Microsoft.OData.UriParser.ODataUriParser.ParseFilter()   
```

**Comment by chrisspre** [comment]
related ? https://github.com/OData/odata.net/issues/2140

**Comment by syprieur** [comment]
No, #2140 is a previous issue I had flagged through Pankaj, and it's been fixed in the ODL since September.

This one (#2270) is a **distinct** issue, albeit in the same area.
