### ISSUE TITLE
Could not convert constant 12/1/2021 12:00:00 AM expression to string

### ISSUE THREAD

**Issue by desmarest** [OData/odata.net#2286]
I am getting an exception when getting the URI of a DataServiceQuery with a queryExpression using a Datetime constant:
"Could not convert constant 12/1/2021 12:00:00 AM expression to string."

Expression: {[10000].Where(entity => (entity.Col2 >= 12/1/2021 12:00:00 AM)).Select(t => new Anonymous1() {Col1 = t.Col1, Col3 = t.Col3})}

### Assemblies affected

Microsoft.OData.Client latest version.

### Reproduce steps
I will try to get better repro steps but at a high level, I am calling Translate on a DataServiceQuery object with a queryExpression using a DateTimevalue.

### Expected result
"?$filter=Col2%20ge%20'2021-12-01'"

### Actual result
"Could not convert constant 12/1/2021 12:00:00 AM expression to string."

### Additional detail

Full call stack:

{System.NotSupportedException: Could not convert constant 12/1/2021 12:00:00 AM expression to string.
   at Microsoft.OData.Client.ExpressionWriter.VisitConstant(ConstantExpression c)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.DataServiceALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.VisitOperand(Expression e, Nullable`1 parentType, Nullable`1 childDirection)
   at Microsoft.OData.Client.ExpressionWriter.VisitBinary(BinaryExpression b)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.DataServiceALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Translate(Expression e)
   at Microsoft.OData.Client.ExpressionWriter.ExpressionToString(DataServiceContext context, Expression e, Boolean inPath, Version& uriVersion)
   at Microsoft.OData.Client.UriWriter.ExpressionToString(Expression expression, Boolean inPath)
   at Microsoft.OData.Client.UriWriter.VisitQueryOptionExpression(FilterQueryOptionExpression fqoe)
   at Microsoft.OData.Client.UriWriter.VisitQueryOptions(ResourceExpression re)
   at Microsoft.OData.Client.UriWriter.VisitQueryableResourceExpression(QueryableResourceExpression rse)
   at Microsoft.OData.Client.DataServiceALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.UriWriter.Translate(DataServiceContext context, Boolean addTrailingParens, Expression e, Uri& uri, Version& version)
   at Microsoft.OData.Client.DataServiceQueryProvider.Translate(Expression e)
   at Microsoft.OData.Client.DataServiceQuery`1.Translate()
   at Microsoft.OData.Client.DataServiceQuery`1.get_RequestUri()}

It looks like this is because there is no support for DateTime type in FormatLiteralWithTypePrefix method:

The call to this.FormatAndEscapeLiteral throws an exception on an object of type System.DateTime, then there is no case defined for DateTime formatting as defined in OData.

**Comment by desmarest** [comment]
Please find my repro below:

using System;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.OData.Client;
using System.Data;

namespace LinqTest
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var uri = new Uri("https://api.purdue.io/odata/");
            DataServiceContext context = new DataServiceContext(uri, ODataProtocolVersion.V4);

            Expression<Func<Term, DateTime>> columnExpr = x => x.StartDate;
            Expression constantExpr = Expression.Constant(new DateTime(2020, 1, 1));

            var paramExp = Expression.Parameter(typeof(Term));
            var exp = (Expression<Func<Term, bool>>)Expression.Lambda(Expression.GreaterThan(Expression.Invoke(columnExpr, paramExp), constantExpr), paramExp);

            var termsDsq = context.CreateQuery<Term>("Terms").Where(exp);
            var reqUri = ((DataServiceQuery)termsDsq).RequestUri;
        }

        public class Term
        {
            public Guid Id { get; set; }
            public string Code { get; set; }
            public string Name { get; set; }
            public DateTime StartDate { get; set; }
            public DateTime EndDate { get; set; }
        }
    }
}
