### ISSUE TITLE
Key as encoded url creates odata exception, not readable key

### ISSUE THREAD

**Issue by abagaylelb** [OData/odata.net#2292]
When trying to use an encoded url or url as a string as a key, I am getting this exception: 

at Microsoft.OData.UriParser.ODataPathParser.ExtractSegmentIdentifierAndParenthesisExpression(String segmentText, String& identifier, String& parenthesisExpression)
   at Microsoft.OData.UriParser.ODataPathParser.BindSegmentBeforeEscapeFunction(String segmentText)
   at Microsoft.OData.UriParser.ODataPathParser.TryCreateEscapeFunctionSegment(String segmentText)
   at Microsoft.OData.UriParser.ODataPathParser.CreateNextSegment(String text)
   at Microsoft.OData.UriParser.ODataPathParser.ParsePath(ICollection`1 segments)
   at Microsoft.OData.UriParser.ODataPathFactory.BindPath(ICollection`1 segments, ODataUriParserConfiguration configuration)
   at Microsoft.OData.UriParser.ODataUriParser.Initialize()
  ...

### Assemblies affected

TBD

### Reproduce steps

Using a GET to get an entity by key with a url being the key 

(https://sample.com/resources('http%3A%2F%2sample.sample.net%2Fsample%2Fservices%2Ffoo'))

### Expected result

Key would be passed to controller and usable by service. 

### Actual result

Odata exception thrown, failed to parse.

**Comment by ElizabethOkerio** [comment]
@abagaylelb  can you please check whether the encoding is right?

**Comment by ElizabethOkerio** [comment]
https://github.com/OData/WebApi/issues/2309

**Comment by abagaylelb** [comment]
Hi @ElizabethOkerio - I used the value you put above, and I am still getting the same error.
