### ISSUE TITLE
Client incorrectly hits DataServiceClientException: A primitive value was specified; however, a value of the non-primitive type '' was expected

### ISSUE THREAD

**Issue by AtulBhartia** [OData/odata.net#2319]
*After we upgraded Microsoft.Data.Services package to 5.8.5 from 5.8.4 we started seeing above error. Destination service is on OdataV3. We noticed this failure on both .net core and .net standard clients. After we reverted the lib to 5.8.4 the issue was resolved.*

### Assemblies affected

*
Microsoft.Data.Services.Client 5.8.5
Microsoft.Data.OData 5.8.5
Microsoft.Data.Edm 5.8.5
System.Spatial  5.8.5
*

### Reproduce steps

*Post say 100 entities on the server. Then client sends a search request and we have say 10 entities in the response*

### Expected result

*we should not have see the exception*

### Actual result

*exception stack:
System.Data.Services.Client.DataServiceRequestException: An error occurred while processing this request.
 ---> System.Data.Services.Client.DataServiceClientException: A primitive value was specified; however, a value of the non-primitive type '' was expected.
 ---> Microsoft.Data.OData.ODataException: A primitive value was specified; however, a value of the non-primitive type '' was expected.
   at Microsoft.Data.OData.ValidationUtils.ValidateIsExpectedPrimitiveType(Object value, IEdmPrimitiveTypeReference valuePrimitiveTypeReference, IEdmTypeReference expectedTypeReference)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightValueSerializer.WritePrimitiveValue(Object value, IEdmTypeReference expectedTypeReference)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightPropertySerializer.WriteProperty(ODataProperty property, IEdmStructuredType owningType, Boolean isTopLevel, Boolean allowStreamProperty, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, ProjectedPropertiesAnnotation projectedProperties)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightPropertySerializer.WriteProperties(IEdmStructuredType owningType, IEnumerable`1 properties, Boolean isComplexValue, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, ProjectedPropertiesAnnotation projectedProperties)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightWriter.EndEntry(ODataEntry entry)
   at Microsoft.Data.OData.ODataWriterCore.<WriteEndImplementation>b__16()
   at Microsoft.Data.OData.ODataWriterCore.InterceptException(Action action)
   at Microsoft.Data.OData.ODataWriterCore.WriteEnd()
   at System.Data.Services.Client.Serializer.WriteEntry(EntityDescriptor entityDescriptor, IEnumerable`1 relatedLinks, ODataRequestMessageWrapper requestMessage)
   at System.Data.Services.Client.BaseSaveResult.CreateRequestData(EntityDescriptor entityDescriptor, ODataRequestMessageWrapper requestMessage)
   at System.Data.Services.Client.SaveResult.CreateNonBatchChangeData(Int32 index, ODataRequestMessageWrapper requestMessage)
   at System.Data.Services.Client.SaveResult.BeginCreateNextChange()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Data.Services.Client.SaveResult.HandleResponse()
   at System.Data.Services.Client.BaseSaveResult.EndRequest()
   at System.Data.Services.Client.DataServiceContext.EndSaveChanges(IAsyncResult asyncResult)
*

### Additional detail

**

**Comment by habbes** [comment]
Hi @AtulBhartia the 5.x versions of OData libraries are no longer supported or maintained. Is there any particular reason you moved from 5.8.4 to 5.8.5? Like any particular feature or bug fix that you wanted to take advantage of in 5.8.5? If not, maybe you could go back to 5.8.4 or check whether later versions > 5.8.5 or 6.x have fixed the issue you currently face (Note that 6.x versions also no longer receive regular updates).
