### ISSUE TITLE
URI validation error (Uri.IsWellFormedUriString())

### ISSUE THREAD

**Issue by AntiGuideAkquinet** [OData/odata.net#2374]
Because of an issue in the [.NET Framework](https://github.com/dotnet/runtime/issues/21626) this line prevents me from creating a DataServiceContext with a valid URI flagging it as invalid incorrectly.
https://github.com/OData/odata.net/blob/acc2c70810eb9a12ef53bb640a2718d9d4db154e/src/Microsoft.OData.Client/UriResolver.cs#L180

The URI in question is `http://192.168.0.1:1234/Instance/ODataV4/Company('123-Customer Place Süd-Ost')/`
It is perfectly valid. Even the percent encoded version doesn't work. The issue seems to occur only when a space and a non ASCII character like ä is present.

As the issue is planned to be fixed in .NET 7 and not in previous versions I hope that you can provide a workaround as this is the default OData URI scheme for Microsofts Business Central for example. Maybe the check could be optional or done through a developer provided custom function.

**Comment by AntiGuideAkquinet** [comment]
```c#
using Microsoft.OData.Client;

new DataServiceContext(new Uri("http://192.168.0.1:1234/Instance/ODataV4/Company('123-Customer Place Süd-Ost')/"), ODataProtocolVersion.V4);
```

results in

```
Unhandled exception. System.ArgumentException: Expected an absolute, well formed http URL without a query or fragment. (Parameter 'serviceRoot')
   at Microsoft.OData.Client.UriResolver.ConvertToAbsoluteAndValidateBaseUri(Uri& baseUri, String parameterName)
   at Microsoft.OData.Client.UriResolver.CreateFromBaseUri(Uri baseUri, String parameterName)
   at Microsoft.OData.Client.DataServiceContext..ctor(Uri serviceRoot, ODataProtocolVersion maxProtocolVersion, ClientEdmModel model)
   at Microsoft.OData.Client.DataServiceContext..ctor(Uri serviceRoot, ODataProtocolVersion maxProtocolVersion)
   at Program.<Main>$(String[] args) in C:\Users\MyUser\RiderProjects\ODataUri\ODataUri\Program.cs:line 3
```

**Comment by KenitoInc** [comment]
@AntiGuideAkquinet 
We initialize the DataServiceContext with the `ServiceRoot`. You are using a full url with query options. That's what is causing the exception.
See [docs](https://docs.microsoft.com/en-us/odata/client/getting-started)

**Comment by AntiGuideAkquinet** [comment]
@KenitoInc
I don't know if fully understand. My endpoints + filter etc. would follow after the DataServiceContext's URI.
For example `http://192.168.0.1:1234/Instance/ODataV4/Company('123-Customer Place Süd-Ost')/UsersTableEndpoint?$filter=Id eq 1`

For my project it is implemented in a context class derriving from `DataServiceContext` consisting of a few `DataServiceQuery`s that are later queried via LINQ.

Are you suggesting I use `http://192.168.0.1:1234/Instance/ODataV4/` as the serviceRoot and put `Company('123-Customer Place Süd-Ost')/UsersTableEndpoint` in the `DataServiceQuery`? The company part is used as a way to specify a tenant by Business Central.

**Comment by AntiGuideAkquinet** [comment]
I tried to implement a basic workaround that fixes the issue for me [here](https://github.com/AntiGuideAkquinet/odata.net/commit/351d54167105bc59ccff6ca6cc8ff6856b0cbe68).
There are very likely better and more elegant ways to implement this but I believe it shows what a simple fix that would not break compatibility with current integrations could look like.

**Comment by KenitoInc** [comment]
This sample code works for me.

```csharp
Container dsc = new Container(new Uri("http://localhost:5000/odata"));

// GET http://localhost:5000/odata/Customers(1)/MainAddress
DataServiceQuery<Customer> customers = dsc.CreateQuery<Customer>("Customers(1)");

foreach(var customer in customers)
{
    Console.WriteLine(customer.MainAddress);
}
```

**Comment by AntiGuideAkquinet** [comment]
As stated in my first comment:

> The issue seems to occur only when a space and a non ASCII character like ä is present.

To reproduce the issue you'll have to use my URI or another one triggering the same .NET bug

**Comment by chrisspre** [comment]
`Uri.IsWellFormedUriString("http://192.168.0.1:1234/Instance/ODataV4/Company('123-Customer ')", UriKind.Absolute);`
returns false, But
`Uri.IsWellFormedUriString("http://192.168.0.1:1234/Instance/ODataV4/Company('123-Customer%20')", UriKind.Absolute);`
returns true.

**Comment by AntiGuideAkquinet** [comment]
@chrisspre That ist true but misses the point that 

> a space **and** a non ASCII character

must be present.

The problem is that
`Uri.IsWellFormedUriString("http://192.168.0.1:1234/Instance/ODataV4/Company('123-Cust%C3%B6mer%20')", UriKind.Absolute);`
and
`Uri.IsWellFormedUriString("http://192.168.0.1:1234/Instance/ODataV4/Company('123-Custömer ')", UriKind.Absolute);`
both **return false while they are valid**.

@KenitoInc Can a hotfix like [this](https://github.com/AntiGuideAkquinet/odata.net/commit/351d54167105bc59ccff6ca6cc8ff6856b0cbe68) be implemented soon? This issue forces all people interfacing with Business Central/Navision that have spaces and non ASCII characters in their tenant names to not use OData or fork the repo.

**Comment by AntiGuideAkquinet** [comment]
It is already filed [here](https://github.com/dotnet/runtime/issues/21626) and scheduled for .NET 7. My request is for a fix considering .NET versions <7.0 that can be used in the meantime and on older versions.
The possible solutions coming to my mind are:

- A flag to ignore the `IsWellFormedUriString` validation -> I did that [here](https://github.com/AntiGuideAkquinet/odata.net/commit/351d54167105bc59ccff6ca6cc8ff6856b0cbe68)
- A `Func<string,bool> validateUri` that can be passed and overrides the standard check -> .NET does this [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.remotecertificatevalidationcallback?view=net-6.0)
- Just patching out the check by default when non ASCII characters and spaces are detected

**Comment by chrisspre** [comment]
Thanks for the .net 7 bug.
It is not sufficient to fix the IsWellFormed check (or provide a clay to inject code to do the check). The URL parser also needs to be able to parse and identify the various elements of the URL.
________________________________

**Comment by AntiGuideAkquinet** [comment]
It seem to work perfectly for now. My quick fix is in active use. If there are issues with it I have not discovered them yet.

**Comment by AntiGuideAkquinet** [comment]
Is there anything I can do to help you to resolve the issue?

**Comment by MihaZupan** [comment]
See https://github.com/dotnet/runtime/issues/72632#issuecomment-1282347554

> The OData library should consider dropping this check entirely. As-is, it is checking `Uri.IsWellFormedUriString(baseUri.AbsoluteUri, UriKind.Absolute)`
which should just always be true, as Uri.AbsoluteUri is always generating a well-formed string.
That is, this check is doing nothing in this case, except for potentially hitting this false-negative bug.

From what I can tell, `OData` can safely remove the `IsWellFormedUriString` check here entirely.

**Comment by tfaller** [comment]
We can work around this by using Reflection.
Of course this could break with any updates, but it is good enough for now.
Tested with 8.0.2

```c#
using Microsoft.OData.Client;

var baseUri = new Uri("http://192.168.0.1:1234/Instance/ODataV4/Company('123-Customer Place Süd-Ost')/");

// context with a placeholder URI
var context = new DataServiceContext(new Uri("https://127.0.0.1"), ODataProtocolVersion.V4);

// create UriResolver with the correct URI
var urlResolver = Activator.CreateInstance(
   "Microsoft.OData.Client", "Microsoft.OData.Client.UriResolver", false,
   BindingFlags.NonPublic | BindingFlags.Instance, null,
   [baseUri, null], // UriResolver(...)
   null, null).Unwrap();

// inject the correct UriResolver into the context
typeof(DataServiceContext)
   .GetField("baseUriResolver", BindingFlags.Instance | BindingFlags.NonPublic)
   .SetValue(context, urlResolver);
```
