### ISSUE TITLE
Property named "true" in $select throws exception

### ISSUE THREAD

**Issue by giulianob** [OData/odata.net#2410]
Creating a field called "true" then using it in a `$select=true` throws an error.

### Assemblies affected

OData .Net lib 7.10

### Reproduce steps

Create a model with an entity property called "true" then try to use it in a $select

### Expected result

The $select works and does not throw an error.

### Actual result
OData parses the "true" as a boolean and fails because it is not an identifier.
```
ODataException : An identifier was expected at position ..
Stack:
   at Microsoft.OData.UriParser.ExpressionToken.GetIdentifier()
   at Microsoft.OData.UriParser.SelectExpandTermParser.ParseSegment(PathSegmentToken previousSegment, Boolean allowRef)
   at Microsoft.OData.UriParser.SelectExpandTermParser.ParseTerm(Boolean allowRef)
   at Microsoft.OData.UriParser.SelectExpandParser.ParseSingleSelectTerm()
   at Microsoft.OData.UriParser.SelectExpandParser.ParseCommaSeparatedSelectList(Func`2 ctor, Func`1 termParsingFunc)
   at Microsoft.OData.UriParser.SelectExpandSyntacticParser.Parse(String selectClause, String expandClause, IEdmStructuredType parentStructuredType, ODataUriParserConfiguration configuration, ExpandToken& expandTree, SelectToken& selectTree)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpandImplementation(String select, String expand, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpand()
```

**Comment by habbes** [comment]
Hi @giulianob `true` is a boolean literal. Is it possible to give the property a different name?

**Comment by habbes** [comment]
@giulianob thanks for the additional context. We're looking into this. It should be possible to disambiguate the boolean literal and an identifier called `true` in some context, like the `$select`.

**Comment by giulianob** [comment]
@habbes We found another case where a customer named a field `INF` which then makes filters such as `INF eq 'y'` fail due to `INF` being a reserved keyword. Is there any workarounds besides renaming the field? Perhaps a way to disambiguate fields from keywords?

**Comment by habbes** [comment]
@giulianob let's see whether this PR: https://github.com/OData/odata.net/pull/2437 addresses that issue as well.

**Comment by giulianob** [comment]
> @giulianob let's see whether this PR: #2437 addresses that issue as well.

Ok thank you. It looks like the PR was in good shape with minor fixes but hasn't received any updates since 2022. Is it possible to try and get it merged? Thanks!
