### ISSUE TITLE
Batch requests getting "System.InvalidOperationException: Synchronous IO APIs are disabled" error

### ISSUE THREAD

**Issue by fannydengdeng** [OData/odata.net#2441]
I am seeing the following exception for $batch requests

```
System.InvalidOperationException: Synchronous IO APIs are disabled, see AllowSynchronousIO.
   at Microsoft.AspNetCore.Server.HttpSys.ResponseBody.Flush()
   at Microsoft.AspNetCore.Server.HttpSys.ResponseStream.Flush()
   at System.IO.BufferedStream.Flush()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.OData.RawValueWriter.Dispose()
   at Microsoft.OData.ODataRawOutputContext.CloseWriter()
   at Microsoft.AspNet.OData.Batch.ODataBatchResponseItem.WriteMessageAsync(ODataBatchWriter writer, HttpContext context, Boolean asyncWriter)
   at Microsoft.AspNet.OData.Batch.ODataBatchContent.WriteToResponseMessageAsync(IODataResponseMessage responseMessage)
   at Microsoft.OData.MultipartMixed.ODataMultipartMixedBatchWriter.DisposeBatchWriterAndSetContentStreamRequestedState()
   at Microsoft.OData.MultipartMixed.ODataMultipartMixedBatchWriter.StreamRequestedAsync()
```

This reproduces in the following configurations.

- A service targeting net6.0 after upgrading to Microsoft.AspNetCore.OData from 7.5.6 to 7.5.15 and Microsoft.OData.* packages from 7.8.2 to 7.11.0. I needed to use 7.5.15 because of this fix https://github.com/OData/AspNetCoreOData/issues/601
- A service targeting netcoreapp3.1 after upgrading Microsoft.OData.* packages from 7.9.1 to 7.11.0. The version of Microsoft.AspNetCore.OData was still 7.5.6.

This does **not** reproduce when using Micrsoft.AspNetCore.OData 7.5.14 and Microsoft.OData.* 7.10.0.

It seems like the issue is from [RawValueWriter](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/RawValueWriter.cs). Should this have implemented async dispose? 

### Assemblies affected

ODataLib 7.11.0

### Reproduce steps

Startup.cs
```
public void Configure(IApplicationBuilder app, ODataBatchHandler batchHandler)
{
    ...
    app.UseODataBatching();
    app.UseMvc(builder =>
    {
        ...
        builder.MapVersionedODataRoutes("odata0", "", models, () => batchHandler);
    });
}
```

Unit test

```
this.client = ODataClientFactory.CreateClient<MyTestServiceClient>(new Uri("http://localhost/MyTestService/"));

Movie m = new Movie() { ... };
Movie m1 = new Movie() { ... };

this.client.AddToMovies(m);
this.client.AddToMovies(m1);
await this.client.SaveChangesAsync(Microsoft.OData.Client.SaveChangesOptions.BatchWithSingleChangeset);
```

Full exception from service logs
```
Exception caught while accepting request /$batch:    at Microsoft.AspNet.OData.Batch.ODataBatchResponseItem.WriteMessageAsync(ODataBatchWriter writer, HttpContext context, Boolean asyncWriter)
         at Microsoft.AspNet.OData.Batch.ChangeSetResponseItem.WriteResponseAsync(ODataBatchWriter writer, Boolean asyncWriter)
         at Microsoft.AspNet.OData.Batch.ODataBatchContent.WriteToResponseMessageAsync(IODataResponseMessage responseMessage)
         at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ProcessBatchAsync(HttpContext context, RequestDelegate nextHandler)
         at Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
         at ===Internal middleware stack===
      --- End of stack trace from previous location ---
         at ===Internal middleware stack===
      System.AggregateException: One or more errors occurred. (Synchronous IO APIs are disabled, see AllowSynchronousIO.)
       ---> System.InvalidOperationException: Synchronous IO APIs are disabled, see AllowSynchronousIO.
         at Microsoft.AspNetCore.Server.HttpSys.ResponseBody.Flush()
         at Microsoft.AspNetCore.Server.HttpSys.ResponseStream.Flush()
         at System.IO.BufferedStream.Flush()
         at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
         at System.IO.StreamWriter.Dispose(Boolean disposing)
         at System.IO.TextWriter.Dispose()
         at Microsoft.OData.RawValueWriter.Dispose()
         at Microsoft.OData.ODataRawOutputContext.CloseWriter()
         at Microsoft.OData.MultipartMixed.ODataMultipartMixedBatchWriter.DisposeBatchWriterAndSetContentStreamRequestedState()
         at Microsoft.OData.MultipartMixed.ODataMultipartMixedBatchWriter.StreamRequestedAsync()
         --- End of inner exception stack trace ---
         at Microsoft.AspNet.OData.Batch.ODataBatchResponseItem.WriteMessageAsync(ODataBatchWriter writer, HttpContext context, Boolean asyncWriter)
         at Microsoft.AspNet.OData.Batch.ChangeSetResponseItem.WriteResponseAsync(ODataBatchWriter writer, Boolean asyncWriter)
         at Microsoft.AspNet.OData.Batch.ODataBatchContent.WriteToResponseMessageAsync(IODataResponseMessage responseMessage)
         at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ProcessBatchAsync(HttpContext context, RequestDelegate nextHandler)
         at Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
```

### Expected result

The stack should be using async IO throughout.

### Actual result

Synchronous IO is used.

**Comment by habbes** [comment]
Hi @fannydengdeng thanks for reporting this. You mentioned that the issue is not reproduced when using Microsoft.AspNetCore.OData 7.5.14 and ODL 7.10.0. Does it get reproduced when you use ODL 7.10.0 with a different version of Microsoft.AspNetCore.OData?

**Comment by fannydengdeng** [comment]
@habbes I also tried with ODL 7.10.0 and Microsoft.AspNetCore.OData 7.5.6 and it did not reproduce.
