### ISSUE TITLE
Select expressions used with MergeOption.NoTracking result in a failed assert

### ISSUE THREAD

**Issue by letherman255** [OData/odata.net#2518]
Select expressions used with MergeOption.NoTracking result in a failed assert : "Id property should not be used when this.isTracking is false." in MaterializerEntry. 

### Assemblies affected

Microsoft.OData.Client 7.12.3 (no issue in 7.12.2)
net6.0-windows

### Reproduce steps

Create a context without entity tracking :
```C#
var context = new OdataContext(new Uri("https://localhost:7196/v1/"))
{
    MergeOption = MergeOption.NoTracking,
};
```

Query and enumerate entities. (Generically in this example)

```C#
        var query = DataServiceQuery;

        if (_filter != null && _sourceData != null) {
            IQueryable < T > ? filteredQuery = _filter(_sourceData, query);

            if (filteredQuery == null) {
                return;
            }

            query = filteredQuery;
        }

        if (skip is > 0)
            query = query.Skip(skip.Value);
        else
            skip = 0;

        if (top.HasValue) query = query.Take(top.Value);

        if (SelectExpression != null) query = query.Select(SelectExpression);

        if (query is DataServiceQuery < T > dataServiceQuery) {
            var queryResponse =
                (QueryOperationResponse < T > ) await dataServiceQuery.IncludeCount()
                .ExecuteAsync();
            if (queryResponse != null) {
                Items.Clear();
                foreach(var x1 in queryResponse) Items.Add(x1);// Crashes when enumerating
                RecordCount = queryResponse.Count;
            } else {
                return;
            }
        }
```
### Expected result

The entities should be successfully retrieved.

### Actual result

Assertion:
```
Process terminated. Assertion failed.
Id property should not be used when this.isTracking is false.
   at Microsoft.OData.Client.Materialization.MaterializerEntry.get_Id()
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ProjectionEnsureEntryAvailableOfType(ODataEntityMaterializer materializer, MaterializerEntry entry, Type requiredType)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ProjectionInitializeEntity(ODataEntityMaterializer materializer, MaterializerEntry entry, Type expectedType, Type resultType, String[] properties, Func`4[] propertyValues)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializerInvoker.ProjectionInitializeEntity(Object materializer, Object entry, Type expectedType, Type resultType, String[] properties, Func`4[] propertyValues)
   at lambda_method44(Closure , Object , Object , Type )
   at Microsoft.OData.Client.ProjectionPlan.Run(ODataEntityMaterializer materializer, ODataResource entry, Type expectedType)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
   at Microsoft.OData.Client.Materialization.ODataMaterializer.Read()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.OData.Client.DataServiceQueryProvider.ReturnSingleton[TElement](Expression expression)
   at Microsoft.OData.Client.DataServiceQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source)
```

**Comment by gathogojr** [comment]
@letherman255 Kindly share a simple repro to demonstrate the issue since the code above as is won't run. I created a simple repro with a select query option only and it works just fine
