### ISSUE TITLE
Delta context fragment fails in ODL

### ISSUE THREAD

**Issue by abgreg** [OData/odata.net#2606]
Graph requires this exact format for my delta request body context: `"@context": "#$delta"`. But OData isn't handling this properly, so we end up receiving a null delta.

### Assemblies affected

We're using OData .NET 8.0.12.

### Reproduce steps

Example request:
`PATCH https://canary.graph.microsoft.com/testprodbetaeduAsg_local_abgreg-3/education/classes/c4bbb6c4-38c1-4fd5-8f9a-086cf9f6cb1b/assignmentSettings/gradingCategories`
```json
{
    "@context": "#$delta",
    "value": [
        {
            "displayName": "Big cat",
            "percentageWeight": 100
        }
    ]
}
```

Example C# controller code:
```
[HttpPatch(ClassesRoutePath.PatchGradingCategories)]
public async Task<IEnumerable<GradingCategoryModel>> PatchGradingCategories(DeltaSet<GradingCategoryModel> deltaGradingCategories, string classId)
```

### Expected result

The delta would be populated as though I had passed an absolute url on the OData context.

### Actual result

The incoming DeltaSet is null.

I see the below error on the ModelState.
```
ModelError,ModelError.Exception,ModelError.ErrorMessage
Microsoft.AspNetCore.Mvc.ModelBinding.ModelError,"Microsoft.OData.ODataException: The top level context URL '#$delta' should be an absolute Uri.
   at Microsoft.OData.JsonLight.ODataJsonLightContextUriParser.Parse(IEdmModel model, String contextUriFromPayload, ODataPayloadKind payloadKind, Func`3 clientCustomTypeResolver, Boolean needParseFragment, Boolean throwIfMetadataConflict)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStartAsync(ODataPayloadKind payloadKind, PropertyAndAnnotationCollector propertyAndAnnotationCollector, Boolean isReadingNestedPayload, Boolean allowEmptyPayload)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationAsync()
   at Microsoft.OData.ODataReaderCoreAsync.ReadAsynchronously()
   at Microsoft.OData.ODataReaderCore.InterceptExceptionAsync[T](Func`2 action)
   at Microsoft.AspNetCore.OData.Formatter.Wrapper.ODataReaderExtensions.ReadResourceOrResourceSetAsync(ODataReader reader)
   at Microsoft.AspNetCore.OData.Formatter.Deserialization.ODataDeltaResourceSetDeserializer.ReadAsync(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
   at Microsoft.AspNetCore.OData.Formatter.ODataInputFormatter.ReadFromStreamAsync(Type type, Object defaultValue, Uri baseAddress, ODataVersion version, HttpRequest request, IList`1 disposes)
   at Microsoft.AspNetCore.OData.Formatter.ODataInputFormatter.LoggerError(HttpContext context, Exception ex)
   at Microsoft.AspNetCore.OData.Formatter.ODataInputFormatter.ReadFromStreamAsync(Type type, Object defaultValue, Uri baseAddress, ODataVersion version, HttpRequest request, IList`1 disposes)
   at Microsoft.AspNetCore.OData.Formatter.ODataInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)",""
```

**Comment by KenitoInc** [comment]
There is a `TODO` comment to support relative uri in context urls https://github.com/OData/odata.net/blob/8ca4e4364a69d22d9a0d4dad02408eff0bd5ed45/src/Microsoft.OData.Core/JsonLight/ODataJsonLightContextUriParser.cs#L82

**Comment by ElizabethOkerio** [comment]
fixed by: https://github.com/OData/odata.net/pull/2618
