### ISSUE TITLE
Odata Client ClientEdmModel cache does not have ComplexTypes which are not part of any model.

### ISSUE THREAD

**Issue by sammym1982** [OData/odata.net#265]
Thanks to @AdamCaviness fix for open types I am now able to send the custom fields over to server using client side request pipeline. 

The issue occurs for the custom field values which are not defined on any entity. In my scenario I have a complex Type CustomFieldSet which I need to set as open type field value. When I try to set this value I get following error.

There are two issues:

1. After debugging I found that the ClientEdmModel's following function is failing because it does not have that type in cache. It seems like this dictionary only gets populated with the data from the types defined on entities incrementally. If I try to use complex type which is defined on entity it passed. 

2. Other issue I am seeing is If I have NamespacePrefix in client .tt file it send over the type name with prefix to server which is wrong as for server its invalid type name .

```C#
public IEdmSchemaType FindDeclaredType(string qualifiedName)
        {
            ClientTypeAnnotation clientTypeAnnotation = null;
            if (this.typeNameToClientTypeAnnotationCache.TryGetValue(qualifiedName, out clientTypeAnnotation))
            {
                return (IEdmSchemaType)clientTypeAnnotation.EdmType;
            }

            return null;
        }
```

Microsoft.OData.Client.DataServiceClientException: **A type named 'Microsoft.OneIM.ActiveIncident.Contracts.CustomFieldSet' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.** ---> Microsoft.OData.Core.ODataException: A type named 'Microsoft.OneIM.ActiveIncident.Contracts.CustomFieldSet' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.
   at Microsoft.OData.Core.TypeNameOracle.ResolveAndValidateTypeName(IEdmModel model, String typeName, EdmTypeKind expectedTypeKind) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Core\TypeNameOracle.cs:line 59
   at Microsoft.OData.Core.TypeNameOracle.ResolveAndValidateTypeFromNameAndMetadata(IEdmModel model, IEdmTypeReference typeReferenceFromMetadata, String typeName, EdmTypeKind typeKindFromValue, Boolean isOpenPropertyType) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Core\TypeNameOracle.cs:line 180
   at Microsoft.OData.Core.TypeNameOracle.ResolveAndValidateTypeNameForValue(IEdmModel model, IEdmTypeReference typeReferenceFromMetadata, ODataValue value, Boolean isOpenProperty) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Core\TypeNameOracle.cs:line 89
   at Microsoft.OData.Core.JsonLight.ODataJsonLightValueSerializer.WriteComplexValue(ODataComplexValue complexValue, IEdmTypeReference metadataTypeReference, Boolean isTopLevel, Boolean isOpenPropertyType, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Core\JsonLight\ODataJsonLightValueSerializer.cs:line 160
   at Microsoft.OData.Core.JsonLight.ODataJsonLightPropertySerializer.WriteProperty(ODataProperty property, IEdmStructuredType owningType, Boolean isTopLevel, Boolean allowStreamProperty, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, ProjectedPropertiesAnnotation projectedProperties) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Core\JsonLight\ODataJsonLightPropertySerializer.cs:line 245
   at Microsoft.OData.Core.JsonLight.ODataJsonLightPropertySerializer.WriteProperties(IEdmStructuredType owningType, IEnumerable`1 properties, Boolean isComplexValue, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, ProjectedPropertiesAnnotation projectedProperties) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Core\JsonLight\ODataJsonLightPropertySerializer.cs:line 119
   at Microsoft.OData.Core.JsonLight.ODataJsonLightWriter.StartEntry(ODataEntry entry) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Core\JsonLight\ODataJsonLightWriter.cs:line 233
   at Microsoft.OData.Core.ODataWriterCore.<>c__DisplayClass14.<WriteStartEntryImplementation>b__12() in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Core\ODataWriterCore.cs:line 901
   at Microsoft.OData.Core.ODataWriterCore.InterceptException(Action action) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Core\ODataWriterCore.cs:line 1223
   at Microsoft.OData.Core.ODataWriterCore.WriteStartEntryImplementation(ODataEntry entry) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Core\ODataWriterCore.cs:line 874
   at Microsoft.OData.Core.ODataWriterCore.WriteStart(ODataEntry entry) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Core\ODataWriterCore.cs:line 393
   at Microsoft.OData.Client.ODataWriterWrapper.WriteStart(ODataEntry entry, Object entity) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Client\Serialization\ODataWriterWrapper.cs:line 70
   at Microsoft.OData.Client.Serializer.WriteEntry(EntityDescriptor entityDescriptor, IEnumerable`1 relatedLinks, ODataRequestMessageWrapper requestMessage) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Client\Serialization\Serializer.cs:line 334
   at Microsoft.OData.Client.BaseSaveResult.CreateRequestData(EntityDescriptor entityDescriptor, ODataRequestMessageWrapper requestMessage) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Client\BaseSaveResult.cs:line 1103
   at Microsoft.OData.Client.BaseSaveResult.CreateChangeData(Int32 index, ODataRequestMessageWrapper requestMessage) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Client\BaseSaveResult.cs:line 390
   at Microsoft.OData.Client.SaveResult.CreateNonBatchChangeData(Int32 index, ODataRequestMessageWrapper requestMessage) in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Client\SaveResult.cs:line 421
   at Microsoft.OData.Client.SaveResult.CreateNextChange() in e:\Samir\odata.net-6.12.0\odata.net-6.12.0\src\Microsoft.OData.Client\SaveResult.cs:line 230
   --- End of inner exception stack trace ---

**Comment by sammym1982** [comment]
any update?

**Comment by congysu** [comment]
@sammym1982 Do you define `Microsoft.OneIM.ActiveIncident.Contracts.CustomFieldSet` in the model?  Or you can create an open complex type such as `Extension`.

**Comment by sammym1982** [comment]
@congysu

Yes the type is part of model and defined in metadata. As I explained above its not part of any entity. 

Not sure what you meant by following. Can you elaborate.

"you can create an open complex type such as  Extension"

**Comment by mikepizzo** [comment]
It would, indeed, be useful to have types not reached by walking the container still available in the model for open type properties.
