### ISSUE TITLE
No ODataException thrown when writing response Asynchronously even though response writing is failing

### ISSUE THREAD

**Issue by daredevilluna** [OData/odata.net#2651]
*Short summary (3-5 sentences) describing the issue.*
We are using Microsoft.AspNetCore.OData(8.0.4) for our Asp.NetCore application. While writing response asynchronously using ODataWriter, if response is not OData compatible then there is no ODataException thrown we don't see any ODataException in our stack trace. 
### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*
Create an EDM model with property 'Foo' whose type you defined 'int' but when writing response have the value of 'Foo' as 'string'. Then ODataWriter should fail.  There is no explanatory exception thrown why response was not OData compatible.
### Expected result

*What would happen if there wasn't a bug.*
We should see an ODataException in the stack trace indicating why the response is not correct.
### Actual result

*What is actually happening.*
We just see this in our logs, no ODataException
![image](https://user-images.githubusercontent.com/34482946/230040563-9f8d54ca-5ec6-4f8a-a3ac-cad60f0652f5.png)

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by ElizabethOkerio** [comment]
@daredevilluna I've tried something similar and gotten this execption: 

Microsoft.OData.ODataException
  HResult=0x80131509
  Message=An incompatible primitive type 'Edm.Int32[Nullable=False]' was found for an item that was expected to be of type 'Edm.String[Nullable=False]'.
  Source=Microsoft.OData.Core
  StackTrace:
   at Microsoft.OData.ValidationUtils.ValidateMetadataPrimitiveType(IEdmTypeReference expectedTypeReference, IEdmTypeReference typeReferenceFromValue) in C:\readBulkUpdates\odata.net\src\Microsoft.OData.Core\ValidationUtils.cs:line 347
   at Microsoft.OData.ValidationUtils.ValidateIsExpectedPrimitiveType(Object value, IEdmPrimitiveTypeReference valuePrimitiveTypeReference, IEdmTypeReference expectedTypeReference) in C:\readBulkUpdates\odata.net\src\Microsoft.OData.Core\ValidationUtils.cs:line 311
   at Microsoft.OData.WriterValidator.ValidateIsExpectedPrimitiveType(Object value, IEdmPrimitiveTypeReference valuePrimitiveTypeReference, IEdmTypeReference expectedTypeReference) in C:\readBulkUpdates\odata.net\src\Microsoft.OData.Core\WriterValidator.cs:line 139
   at Microsoft.OData.JsonLight.ODataJsonLightValueSerializer.<WritePrimitiveValueAsync>d__19.MoveNext() in C:\readBulkUpdates\odata.net\src\Microsoft.OData.Core\JsonLight\ODataJsonLightValueSerializer.cs:line 679
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.<WritePrimitivePropertyAsync>d__44.MoveNext() in C:\readBulkUpdates\odata.net\src\Microsoft.OData.Core\JsonLight\ODataJsonLightPropertySerializer.cs:line 1220
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.<WritePropertyAsync>d__11.MoveNext() in C:\readBulkUpdates\odata.net\src\Microsoft.OData.Core\JsonLight\ODataJsonLightPropertySerializer.cs:line 393
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.<WritePropertiesAsync>d__10.MoveNext() in C:\readBulkUpdates\odata.net\src\Microsoft.OData.Core\JsonLight\ODataJsonLightPropertySerializer.cs:line 334
   at Microsoft.OData.JsonLight.ODataJsonLightWriter.<StartResourceAsync>d__62.MoveNext() in C:\readBulkUpdates\odata.net\src\Microsoft.OData.Core\JsonLight\ODataJsonLightWriter.cs:line 1407
   at Microsoft.OData.ODataWriterCore.<>c.<<WriteStartResourceImplementationAsync>b__196_0>d.MoveNext() in C:\readBulkUpdates\odata.net\src\Microsoft.OData.Core\ODataWriterCore.cs:line 3330
   at Microsoft.OData.ODataWriterCore.<InterceptExceptionAsync>d__179`1.MoveNext() in C:\readBulkUpdates\odata.net\src\Microsoft.OData.Core\ODataWriterCore.cs:line 2491
   at Microsoft.OData.ODataWriterCore.<WriteStartResourceImplementationAsync>d__196.MoveNext() in C:\readBulkUpdates\odata.net\src\Microsoft.OData.Core\ODataWriterCore.cs:line 3316
   at Program.<<Main>$>d__0.MoveNext() in C:\readBulkUpdates\odata.net\sln\ConsoleApp1\Program.cs:line 44
   at Program.<Main>(String[] args)

**Comment by ElizabethOkerio** [comment]
@daredevilluna  do you get a truncated response?
