### ISSUE TITLE
Dispose calls in constructors can lead to unwanted synchronous I/O.

### ISSUE THREAD

**Issue by habbes** [OData/odata.net#2685]
*Short summary (3-5 sentences) describing the issue.*

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result

*What would happen if there wasn't a bug.*

### Actual result

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by corranrogue9** [comment]
If an exception is thrown in the constructor, there is no object instance to call `DisposeAsync` on. Maybe a factory method would be good, since the factory can be async, and have the calls to `Dispose` methods.

**Comment by vcaraulean** [comment]
>  I don't know of any actual cases where this has blown up in production

@habbes - would this count?
```
System.InvalidOperationException: An asynchronous operation is already in progress.
   at System.Xml.XmlAsyncCheckWriter.CheckAsync()
   at System.Xml.XmlAsyncCheckWriter.Flush()
   at Microsoft.OData.ODataMetadataOutputContext.Dispose(Boolean disposing)
   at Microsoft.OData.ODataOutputContext.Dispose()
   at Microsoft.OData.ODataMessageWriter.Dispose(Boolean disposing)
   at Microsoft.OData.ODataMessageWriter.Dispose()
   at Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatterHelper.WriteToStreamAsync(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, HttpRequest request, IHeaderDictionary requestHeaders, IODataSerializerProvider serializerProvider)
```

Trying to narrow it down, but it's very elusive...
