### ISSUE TITLE
Client(json materializer): Unclosed square brackets inside strings is not supported

### ISSUE THREAD

**Issue by max31000** [OData/odata.net#2737]
If the server response contains any `[` withot `]` inside `""` in the body, an exception `Unbalanced bracketed expression found` will be thrown to the client.

### Assemblies affected

OData .Net lib 7.x*

### Reproduce steps

We found this problem with json like:
```
{
  "obj": "blabla ["
}
```

For reproduce i wrote this simple unit test in a `ODataUriUtilsTests.cs` file:
```
        [Fact]
        public void TestBracketJson()
        {
            var collection = ODataUriUtils.ConvertFromUriLiteral("[{\"obj\": \"bracket[\" }]", ODataVersion.V4);
        }
```

And run this with netcoreapp3.1 config

If i close brackets inside test json, its work:
```
        [Fact]
        public void TestBracketJson()
        {
            var collection = ODataUriUtils.ConvertFromUriLiteral("[{\"obj\": \"bracket[]\" }]", ODataVersion.V4);
        }
```

### Expected result

Do not crash on any brackets inside string

### Actual result

I catch this exception:
```
Microsoft.OData.ODataException: Found an unbalanced bracket expression.

Microsoft.OData.ODataException
Found an unbalanced bracket expression.
   at Microsoft.OData.UriParser.ExpressionLexer.AdvanceThroughBalancedExpression(Char startingCharacter, Char endingCharacter) in C:\odata\odata.net\src\Microsoft.OData.Core\UriParser\ExpressionLexer.cs:line 1265
   at Microsoft.OData.UriParser.ExpressionLexer.NextTokenImplementation(Exception& error) in C:\odata\odata.net\src\Microsoft.OData.Core\UriParser\ExpressionLexer.cs:line 676
   at Microsoft.OData.UriParser.ExpressionLexer.TryPeekNextToken(ExpressionToken& resultToken, Exception& error) in C:\odata\odata.net\src\Microsoft.OData.Core\UriParser\ExpressionLexer.cs:line 238
   at Microsoft.OData.ODataUriUtils.ConvertFromUriLiteral(String value, ODataVersion version, IEdmModel model, IEdmTypeReference typeReference) in C:\odata\odata.net\src\Microsoft.OData.Core\Uri\ODataUriUtils.cs:line 62
// ...
```

### Additional detail

This json (with closed bracked, without open) work normally:
```
{
  "obj": "blabla ]"
}
```

It looks like this is not very normal behavior. I haven't been able to dig deep enough into the problem, but with parentheses and curly brackets it doesn't reproduce. Apparently some important logic is missing for square brackets.

**Comment by xuzhg** [comment]
Fixed for 8 and It's already working in 9 since different balance bracket logic.
