### ISSUE TITLE
System.NotSupportedException: Could not convert constant MyEnumValue expression to string.

### ISSUE THREAD

**Issue by rpallares** [OData/odata.net#2778]
Hello,
I use Microsoft.OData.Client@7.18.0 library to get data from service, generated from Microsoft.OData.Cli@0.2.1.

I have an exception when using In operator on some enumeration values following:
https://learn.microsoft.com/en-us/odata/client/query-options#filter

### Assemblies affected
- Microsoft.OData.Client@7.18.0

### Reproduce steps
```c#
MyEnum[] enumValues = { MyEnum.Value1, MyEnum.Value2 };

var results = client.MyEntitySet
    .Where(entity => enumValues.Contains(entity.EntityEnumValue)
    .ToList();
```

### Expected result
The query is generated and executed correctly using the In operator.

### Actual result
```
System.NotSupportedException: Could not convert constant Value1 expression to string.
   at Microsoft.OData.Client.ExpressionWriter.VisitConstant(ConstantExpression c)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.VisitMethodCall(MethodCallExpression m)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.VisitOperand(Expression e, Nullable`1 parentType, Nullable`1 childDirection)
   at Microsoft.OData.Client.ExpressionWriter.VisitBinary(BinaryExpression b)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.VisitOperand(Expression e, Nullable`1 parentType, Nullable`1 childDirection)
   at Microsoft.OData.Client.ExpressionWriter.VisitBinary(BinaryExpression b)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.VisitOperand(Expression e, Nullable`1 parentType, Nullable`1 childDirection)
   at Microsoft.OData.Client.ExpressionWriter.VisitBinary(BinaryExpression b)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.VisitOperand(Expression e, Nullable`1 parentType, Nullable`1 childDirection)
   at Microsoft.OData.Client.ExpressionWriter.VisitBinary(BinaryExpression b)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.VisitOperand(Expression e, Nullable`1 parentType, Nullable`1 childDirection)
   at Microsoft.OData.Client.ExpressionWriter.VisitBinary(BinaryExpression b)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.ExpressionToString(DataServiceContext context, Expression e, Boolean inPath, Version& uriVersion)
   at Microsoft.OData.Client.UriWriter.VisitQueryOptions(ResourceExpression re)
   at Microsoft.OData.Client.UriWriter.VisitQueryableResourceExpression(QueryableResourceExpression rse)
   at Microsoft.OData.Client.UriWriter.Translate(DataServiceContext context, Boolean addTrailingParens, Expression e, Uri& uri, Version& version)
   at Microsoft.OData.Client.DataServiceQueryProvider.Translate(Expression e)
   at Microsoft.OData.Client.DataServiceQuery`1.QueryComponents(ClientEdmModel model)
   at Microsoft.OData.Client.DataServiceRequest.CreateExecuteResult(Object source, DataServiceContext context, AsyncCallback callback, Object state, String method)
   at Microsoft.OData.Client.DataServiceQuery`1.BeginExecute(AsyncCallback callback, Object state)
   at Microsoft.OData.Client.DataServiceContext.<>c__DisplayClass296_0`1.<FromAsync>b__0(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync(Func`3 beginMethod, Func`2 endMethod, Object state)
   at Microsoft.OData.Client.DataServiceContext.FromAsync[TResult](Func`3 beginMethod, Func`2 endMethod, CancellationToken cancellationToken)
   at Microsoft.OData.Client.DataServiceQuery`1.GetAllPagesAsync(CancellationToken cancellationToken)
```

**Comment by powellr0102** [comment]
Any updates on this issue?

I get the same exception while trying to build a lambda function from `System.Linq.Expressions` (see red arrow below) but it works just fine otherwise (see green arrow below).

![Screenshot 2023-12-14 142236](https://github.com/OData/odata.net/assets/143731821/a6b3e743-72da-478a-8926-127d9582c321)

![Screenshot 2023-12-14 142946](https://github.com/OData/odata.net/assets/143731821/d43b63c4-ff23-41fc-81af-650feec09b8f)


```
 System.NotSupportedException
  HResult=0x80131515
  Message=Could not convert constant Manufactured expression to string.
  Source=Microsoft.OData.Client
  StackTrace:
   at Microsoft.OData.Client.ExpressionWriter.VisitConstant(ConstantExpression c)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.DataServiceALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.VisitOperand(Expression e, Nullable`1 parentType, Nullable`1 childDirection)
   at Microsoft.OData.Client.ExpressionWriter.VisitBinary(BinaryExpression b)
   at Microsoft.OData.Client.ALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.DataServiceALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Visit(Expression exp)
   at Microsoft.OData.Client.ExpressionWriter.Translate(Expression e)
   at Microsoft.OData.Client.ExpressionWriter.ExpressionToString(DataServiceContext context, Expression e, Boolean inPath, Version& uriVersion)
   at Microsoft.OData.Client.UriWriter.ExpressionToString(Expression expression, Boolean inPath)
   at Microsoft.OData.Client.UriWriter.VisitQueryOptionExpression(FilterQueryOptionExpression fqoe)
   at Microsoft.OData.Client.UriWriter.VisitQueryOptions(ResourceExpression re)
   at Microsoft.OData.Client.UriWriter.VisitQueryableResourceExpression(QueryableResourceExpression rse)
   at Microsoft.OData.Client.DataServiceALinqExpressionVisitor.Visit(Expression exp)
   at Microsoft.OData.Client.UriWriter.Translate(DataServiceContext context, Boolean addTrailingParens, Expression e, Uri& uri, Version& version)
   at Microsoft.OData.Client.DataServiceQueryProvider.Translate(Expression e)
   at Microsoft.OData.Client.DataServiceQuery`1.Translate()
   at Microsoft.OData.Client.DataServiceQuery`1.Execute()
   at Microsoft.OData.Client.DataServiceQuery`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at IFS.GlobalInventoryPartViewer.Services.IFSInventoryPartsHandlingService.<GetInventoryParts>d__10.MoveNext() in C:\TFS\Web\IFS.GlobalInventoryPartViewer\Services\IFSInventoryPartsHandlingService.cs:line 87

  This exception was originally thrown at this call stack:
    [External Code]
    IFS.GlobalInventoryPartViewer.Services.IFSInventoryPartsHandlingService.GetInventoryParts(System.Collections.Generic.ICollection<IFS.GlobalInventoryPartViewer.OData.FilterExpressionBuilder.Filters.Filter>) in IFSInventoryPartsHandlingService.cs
```
