### ISSUE TITLE
WritesJsonElementCorrectly() Fails Intermittently on the release pipeline

### ISSUE THREAD

**Issue by ElizabethOkerio** [OData/odata.net#2927]
*Short summary (3-5 sentences) describing the issue.*

This test [ public void WritesJsonElementCorrectly() ](https://github.com/OData/odata.net/blob/8f17bb2e215e9e8c3239ac9953b513c882df1edc/test/FunctionalTests/Microsoft.OData.Core.Tests/Json/JsonWriterBaseTests.cs#L236) fails intermittently on the release pipeline and needs to be investigated to check whether there are bugs that need fixing. 

### Assemblies affected

*Microsoft.OData.Core*
Micr
### Reproduce steps

*Hard to repro since it only fails in the release pipeline.*

### Expected result

*The test to pass in both the build and release pipelines. .*

### Actual result

*Test passing in build pipeline but failing in release pipeline..*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by habbes** [comment]
@ElizabethOkerio could you share the error stack trace?

**Comment by habbes** [comment]
Here's the stack trace, the error seems to come from `JsonDocument.Parse` parsing the string, and not from the JSON writer:

```
[xUnit.net 00:00:13.05]     Microsoft.OData.Tests.Json.JsonWriterAsyncTests.WritesJsonElementCorrectly [FAIL]
  Failed Microsoft.OData.Tests.Json.JsonWriterAsyncTests.WritesJsonElementCorrectly [3 ms]
  Error Message:
   System.Text.Json.JsonReaderException : '0x00' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 1.
  Stack Trace:
     at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Microsoft.OData.Tests.Json.JsonWriterAsyncBaseTests.WritesJsonElementCorrectly() in D:\a\1\s\test\FunctionalTests\Microsoft.OData.Core.Tests\Json\JsonWriterAsyncBaseTests.cs:line 237
--- End of stack trace from previous location ---
[xUnit.net 00:00:07.11] Skipping: Microsoft.OData.Edm.Tests (could not find dependent assembly 'Microsoft.OData.Edm, Version=8.0.0')
```
