### ISSUE TITLE
Reques not executed. Exception thrown: System.TypeLoadException: Could not load type of field 'Microsoft.OData.WriterValidator:duplicatePropertyNameCheckerObjectPool'

### ISSUE THREAD

**Issue by ecomation-matthijs** [OData/odata.net#2950]
We just updated the packages Microsoft.Odata.Client, Microsoft.Odata.Core, Microsoft.Odata.Edm and Microsoft.Spatial from 7.20.0 to 7.21.0, but we are getting a weird exception when we try to POST data to our Odata API.

### Assemblies affected

Microsoft.Odata.Client 7.21.0
Microsoft.Odata.Core 7.21.0
Microsoft.Odata.Edm 7.21.0
Microsoft.Spatial 7.21.0

### Reproduce steps

```
var dsc = new DataServiceCollection<PerformanceModel>(context, "Performances", null, null);
// Create an Item and add it to the OData context.
var item = new PerformanceModel();
dsc.Add(item);
item.ActivityId = 1;
item.EmployeeId = 1;
item.LocationId = 1;
item.StartTime = DateTime.Now;
item.Note = "Example";
DataServiceResponse responses = await context.SaveChangesAsync(SaveChangesOptions.PostOnlySetProperties);
```

### Expected result

The request would be executed and returned a response from the server.

### Actual result

The request is not executed, instead it throws an exception:
System.TypeLoadException: Could not load type of field 'Microsoft.OData.WriterValidator:duplicatePropertyNameCheckerObjectPool' (1) due to: Could not load file or assembly 'Microsoft.Extensions.ObjectPool, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
   at Microsoft.OData.Client.ODataMessageWritingHelper.CreateSettings(Boolean isBatchPartRequest, Boolean enableWritingODataAnnotationWithoutPrefix)
   at Microsoft.OData.Client.Serializer.CreateMessageWriter(ODataRequestMessageWrapper requestMessage, RequestInfo requestInfo, Boolean isParameterPayload)
   at Microsoft.OData.Client.Serializer.WriteEntry(EntityDescriptor entityDescriptor, IEnumerable`1 relatedLinks, ODataRequestMessageWrapper requestMessage)
   at Microsoft.OData.Client.BaseSaveResult.CreateRequestData(EntityDescriptor entityDescriptor, ODataRequestMessageWrapper requestMessage)
   at Microsoft.OData.Client.BaseSaveResult.CreateChangeData(Int32 index, ODataRequestMessageWrapper requestMessage)
   at Microsoft.OData.Client.SaveResult.CreateNonBatchChangeData(Int32 index, ODataRequestMessageWrapper requestMessage)
   at Microsoft.OData.Client.SaveResult.BeginCreateNextChange()
   at Microsoft.OData.Client.DataServiceContext.BeginSaveChanges(SaveChangesOptions options, AsyncCallback callback, Object state)
   at Microsoft.OData.Client.DataServiceContext.<>c__DisplayClass297_0`2[[Microsoft.OData.Client.SaveChangesOptions, Microsoft.OData.Client, Version=7.21.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Microsoft.OData.Client.DataServiceResponse, Microsoft.OData.Client, Version=7.21.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].<FromAsync>b__0(SaveChangesOptions arg1, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1[[Microsoft.OData.Client.DataServiceResponse, Microsoft.OData.Client, Version=7.21.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].FromAsyncImpl[SaveChangesOptions](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, SaveChangesOptions arg1, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1[[Microsoft.OData.Client.DataServiceResponse, Microsoft.OData.Client, Version=7.21.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].FromAsync[SaveChangesOptions](Func`4 beginMethod, Func`2 endMethod, SaveChangesOptions arg1, Object state)
   at Microsoft.OData.Client.DataServiceContext.FromAsync[SaveChangesOptions,DataServiceResponse](Func`4 beginMethod, Func`2 endMethod, SaveChangesOptions arg, CancellationToken cancellationToken)
   at Microsoft.OData.Client.DataServiceContext.SaveChangesAsync(SaveChangesOptions options, CancellationToken cancellationToken)
   at Microsoft.OData.Client.DataServiceContext.SaveChangesAsync(SaveChangesOptions options)
   at EcotouchMobile.Services.PerformanceModelService.CreateModel(Dictionary`2 values) in C:\repo\ecotouch-mobile\Services\PerformanceModelService.cs:line 72
   at EcotouchMobile.Modules.Time.Pages.TimeDetail.TimeDetailViewModel.SaveAsync() in C:\repo\ecotouch-mobile\Modules\Time\Pages\TimeDetail\TimeDetailViewModel.cs:line 383

**Comment by ecomation-matthijs** [comment]
If you install Microsoft.Extensions.ObjectPool via nuget fixes the issue. But why was this depenency added? And why is this not automatically installed when you update via nuget?

**Comment by habbes** [comment]
@ecomation-matthijs thanks for reporting this. It appears to be a regression.
