### ISSUE TITLE
Add an untype json property in a feed

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#318]
In the same level of `value:[...]`.  Now it fails with a validation:
>
Result StackTrace:	
at Microsoft.OData.Core.ODataMessageWriter.VerifyWriterNotDisposedAndNotUsed()
   at Microsoft.OData.Core.ODataMessageWriter.VerifyCanWriteProperty(ODataProperty property)
   at Microsoft.OData.Core.ODataMessageWriter.WriteProperty(ODataProperty property)
   at WriteODataPayload.Class1.Test() in C:\WriteODataPayload\Class1.cs:line 39
Result Message:	Microsoft.OData.Core.ODataException : The ODataMessageWriter has already been used to write a message payload. An ODataMessageWriter can only be used once to write a payload for a given message.

**Comment by challenh** [comment]
Track this with #248 . close now..
