### ISSUE TITLE
[V3 Client] ProjectionPlanCompiler failed to visit expression which contains a null propagation check on the second level property

### ISSUE THREAD

**Issue by LaylaLiu** [OData/odata.net#379]
When querying with projections involving implicit expands you often need to include null propagation checks in the projector to guard against null exceptions during materialization in the special scenario where the projected instance is null. This is accomplished by the notation “P1 = x.P1 == null ? null : new P1 { … }”. Null propagation checks only works on the first level part of the projection, on deeper levels in the projection it fails during materialization with the following exception:

System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=An entity of type 'TwoLevelNullPropagationBug.NorthwindSvc.Customer' cannot be projected because there is already an instance of type 'TwoLevelNullPropagationBug.NorthwindSvc.Order' for 'http://services.odata.org/V3/Northwind/Northwind.svc/Orders(10248)'.
  Source=Microsoft.Data.Services.Client
  StackTrace:
       at System.Data.Services.Client.Materialization.ODataEntityMaterializer.ProjectionInitializeEntity(ODataEntityMaterializer materializer, MaterializerEntry entry, Type expectedType, Type resultType, String[] properties, Func`4[] propertyValues)
       at System.Data.Services.Client.Materialization.ODataEntityMaterializerInvoker.ProjectionInitializeEntity(Object materializer, Object entry, Type expectedType, Type resultType, String[] properties, Func`4[] propertyValues)
       at _dynamic_ODataEntityMaterializerInvoker_ProjectionInitializeEntity(Object , Object , Type , Type , String[] , Func`4[] )
       at lambda_method(Closure , Object , Object , Type )
       at System.Data.Services.Client.Materialization.ODataEntityMaterializer.ProjectionInitializeEntity(ODataEntityMaterializer materializer, MaterializerEntry entry, Type expectedType, Type resultType, String[] properties, Func`4[] propertyValues)
       at System.Data.Services.Client.Materialization.ODataEntityMaterializerInvoker.ProjectionInitializeEntity(Object materializer, Object entry, Type expectedType, Type resultType, String[] properties, Func`4[] propertyValues)
       at _dynamic_ODataEntityMaterializerInvoker_ProjectionInitializeEntity(Object , Object , Type , Type , String[] , Func`4[] )
       at lambda_method(Closure , Object , Object , Type )
       at System.Data.Services.Client.Materialization.ODataEntityMaterializer.ProjectionInitializeEntity(ODataEntityMaterializer materializer, MaterializerEntry entry, Type expectedType, Type resultType, String[] properties, Func`4[] propertyValues)
       at System.Data.Services.Client.Materialization.ODataEntityMaterializerInvoker.ProjectionInitializeEntity(Object materializer, Object entry, Type expectedType, Type resultType, String[] properties, Func`4[] propertyValues)
       at _dynamic_ODataEntityMaterializerInvoker_ProjectionInitializeEntity(Object , Object , Type , Type , String[] , Func`4[] )
       at lambda_method(Closure , Object , Object , Type )
       at System.Data.Services.Client.ProjectionPlan.Run(ODataEntityMaterializer materializer, ODataEntry entry, Type expectedType)
       at System.Data.Services.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
       at System.Data.Services.Client.MaterializeAtom.MoveNextInternal()
       at System.Data.Services.Client.MaterializeAtom.MoveNext()
       at System.Linq.Enumerable.<CastIterator>d__1`1.MoveNext()
       at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
       at System.Data.Services.Client.DataServiceQueryProvider.ReturnSingleton[TElement](Expression expression)
       at System.Data.Services.Client.DataServiceQueryProvider.Execute[TResult](Expression expression)
       at System.Linq.Queryable.First[TSource](IQueryable`1 source)
       at TwoLevelNullPropagationBug.Program.Main(String[] args) in c:\users\ufe\documents\visual studio 2015\Projects\TwoLevelNullPropagationBug\TwoLevelNullPropagationBug\Program.cs:line 69
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by LaylaLiu** [comment]
When using conditional on second level property(entity type), ProjectionPlanCompiler doesn't RegisterRewrite for this entry.

**Comment by AlanWong-MS** [comment]
@LaylaLiu, do you know the status of this issue? #670 appears to have a workaround for this; do you think it works as a full solution?

**Comment by LaylaLiu** [comment]
This issue should have been fixed  by commit https://github.com/OData/odata.net/commit/e101af0c030047b5c3c41849f6289272f50b8863

**Comment by AlanWong-MS** [comment]
Thanks! Closing this issue as such.
