### ISSUE TITLE
OData client library memory leak causes app to run out of virtual memory

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#389]
The leak stack:
```
Microsoft.OData.Client.DataServiceQueryException: An error occurred while processing this request. ---> System.InvalidOperationException: An error occurred while processing this request. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.OData.Client.QueryResult.AsyncEndRead(IAsyncResult asyncResult)
   at Microsoft.OData.Client.BaseAsyncResult.<>c__DisplayClass2.<GetDataServiceAsyncCallback>b__1(IAsyncResult asyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.ChunkParser.CompleteUserRead(Object result)
   at System.Net.ChunkParser.CompletePayloadReadOperation(Int32 bytesRead)
   at System.Net.ChunkParser.HandlePayload()
   at System.Net.ChunkParser.ProcessResponse()
   at System.Net.ChunkParser.ReadCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Microsoft.OData.Client.BaseAsyncResult.EndExecute[T](Object source, String method, IAsyncResult asyncResult)
   at Microsoft.OData.Client.QueryResult.EndExecuteQuery[TElement](Object source, String method, IAsyncResult asyncResult)
```

**Comment by LaylaLiu** [comment]
1. To store an object with small bytes instead of the whole object itself as the key into the dictionary.
2. If there isn't any instance annotation, don't store an empty collection into the dictionary.

**Comment by congysu** [comment]
Checked in 490ff86d5bd6092de380443f8ab2ed023f748094.
