### ISSUE TITLE
[OData client] NullReferenceException on GetOrCreateEdmTypeInternal

### ISSUE THREAD

**Issue by viazovskyi** [OData/odata.net#417]
Hi guys, we recently switched Odata.Client lib from 6.13 ver to 6.14 Microsoft.OData.Client.6.14.0-Nightly20151206 and now we are facing NullReferenceException exception on concurrent executions of 2 client requests. After some debugging we found that TypeResolver ctor runs simultaneously and fills clientEdmModel.EdmStructuredSchemaElements with duplicates and null values. here is the exception:

{
  "$type": "System.NullReferenceException, mscorlib",
  "Message": "Object reference not set to an instance of an object.",
  "StackTrace": "
      at Microsoft.OData.Client.ClientEdmModel.<>c__DisplayClass19.<GetOrCreateEdmTypeInternal>b__d(IEdmSchemaElement et)
      at System.Linq.Enumerable.FirstOrDefault[[TSource]](IEnumerable`1 source, Func`2 predicate)
      at Microsoft.OData.Client.ClientEdmModel.GetOrCreateEdmTypeInternal(IEdmStructuredType edmBaseType, Type type, PropertyInfo[] keyProperties, Boolean isEntity, Nullable`1 hasProperties)
      at Microsoft.OData.Client.ClientEdmModel.GetOrCreateEdmType(Type type)
      at Microsoft.OData.Client.TypeResolver.ResolveExpectedTypeForReading(Type clientClrType)
      at Microsoft.OData.Client.Materialization.ODataMaterializer.CreateMaterializerForMessage(IODataResponseMessage responseMessage, ResponseInfo responseInfo, Type materializerType, QueryComponents queryComponents, ProjectionPlan plan, ODataPayloadKind payloadKind)
      at Microsoft.OData.Client.DataServiceRequest.Materialize(ResponseInfo responseInfo, QueryComponents queryComponents, ProjectionPlan plan, String contentType, IODataResponseMessage message, ODataPayloadKind expectedPayloadKind)
      at Microsoft.OData.Client.QueryResult.CreateMaterializer(ProjectionPlan plan, ODataPayloadKind payloadKind)
      at Microsoft.OData.Client.QueryResult.ProcessResult[[TElement]](ProjectionPlan plan)
      at Microsoft.OData.Client.DataServiceRequest.Execute[[TElement]](DataServiceContext context, QueryComponents queryComponents)
      at Microsoft.OData.Client.DataServiceContext.InnerSynchExecute[[TElement]](Uri requestUri, String httpMethod, Nullable`1 singleResult, OperationParameter[] operationParameters)
      at Microsoft.OData.Client.DataServiceContext.Execute[[TElement]](Uri requestUri, String httpMethod, Boolean singleResult, OperationParameter[] operationParameters)
      at Microsoft.OData.Client.DataServiceQuery`1.Execute()
      at ...SOME CODE...
  "Source": "Microsoft.OData.Client",
  "HResult": -2147467261
}

Then inside GetOrCreateEdmTypeInternal method call we get this exception on FirstOrDefault, because one or several elements of EdmStructuredSchemaElements is null. Also, want to add that issue is not 100% always reproducible.

**Comment by LaylaLiu** [comment]
@viazovskyi Thanks for reporting this issue. I will close this issue right now. If you have more update on this issue or if you have still questions about this issue, please reopen it.
