### ISSUE TITLE
[OData client] IndexOutOfRangeException in TypeResolver.ctor

### ISSUE THREAD

**Issue by viazovskyi** [OData/odata.net#423]
Guys, one more exception with nightly build from Dec 15:

Unhandled exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Contains(T item)
   at Microsoft.OData.Client.TypeResolver..ctor(ClientEdmModel model, Func`2 resolveTypeFromName, Func`2 resolveNameFromType, IEdmModel serviceModel)
   at Microsoft.OData.Client.RequestInfo..ctor(DataServiceContext context)
   at Microsoft.OData.Client.DataServiceRequest.CreateExecuteResult(Object source, DataServiceContext context, AsyncCallback callback, Object state, String method)
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at Microsoft.OData.Client.DataServiceQuery`1.Execute()
   at Microsoft.OData.Client.DataServiceQuerySingle`1.GetValue()

looks like this list EdmStructuredSchemaElements is modified by some one. Probably related to [issue 417](https://github.com/OData/odata.net/issues/417).

**Comment by LaylaLiu** [comment]
Viazovskyi, Is it possible that you provide us with the odata service you are accessing, which might be helpful for us to repro the issue.

**Comment by LaylaLiu** [comment]
@viazovskyi Thanks for reporting this issue. I will close this issue right now. If you have more updates on this issue or if you have still questions about this issue, please reopen it.
