### ISSUE TITLE
Confusing error thrown when a Primitive is found where a ComplexType belongs

### ISSUE THREAD

**Issue by JefWight** [OData/odata.net#487]
When a client specifies a body that contains a Primitive value for a property that is actually a ComplexType, the ODataReader.Read() method will throw an error like:
```
An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected.
````

It's an ODataException, so we can easily raise this up as a BadRequest, but the error is really confusing and doesn't provide enough information for the client to know what the problem with their request was.

Call Stack:
```
at Microsoft.OData.Core.Json.JsonReaderExtensions.ValidateNodeType(JsonReader jsonReader, JsonNodeType expectedNodeType)
at Microsoft.OData.Core.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String payloadTypeName, IEdmTypeReference expectedTypeReference, DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideComplexValue, String propertyName, Nullable`1 isDynamicProperty)
at Microsoft.OData.Core.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadEntryDataProperty(IODataJsonLightReaderEntryState entryState, IEdmProperty edmProperty, String propertyTypeName)
at Microsoft.OData.Core.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadEntryPropertyWithValue(IODataJsonLightReaderEntryState entryState, String propertyName)
at Microsoft.OData.Core.JsonLight.ODataJsonLightEntryAndFeedDeserializer.<>c__DisplayClass2.<ReadEntryContent>b__0(PropertyParsingResult propertyParsingResult, String propertyName)
at Microsoft.OData.Core.JsonLight.ODataJsonLightDeserializer.ProcessProperty(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
at Microsoft.OData.Core.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadEntryContent(IODataJsonLightReaderEntryState entryState)
at Microsoft.OData.Core.JsonLight.ODataJsonLightReader.ReadEntryStart(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, SelectedPropertiesNode selectedProperties)
at Microsoft.OData.Core.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker)
at Microsoft.OData.Core.ODataReaderCore.ReadImplementation()
at Microsoft.OData.Core.ODataReaderCore.InterceptException[T](Func`1 action)
```

It would be **much** more useful if the exception was something more like:
```
An unexpected 'PrimitiveValue' node was found when attempting to read the property 'Foo' from the JSON reader. A 'StartObject' node for a complex value was expected.
```

**Comment by LianwMS** [comment]
submit 942180da8e2ced01c81364150be153de1f93cdbb and closed
