### ISSUE TITLE
ODataQueryOptions.Apply.ApplyClause error when using date hierarchy

### ISSUE THREAD

**Issue by rwerlang** [OData/odata.net#529]
*When using $apply=groupby((Field/Year)) the ApplyClause throws an exception*  

### Assemblies affected
*System.Web.OData*  

### Reproduce steps

- Using a ODataController with EnableQuery on an entityset with a DateTime field
- Set the url to "<odataurl>/<entityset>?$apply=groupby((MyDate**/Year**))"
- Call the action with ODataQueryOptions as a parameter
- Inspect ODataQueryOptions.Apply.ApplyCause to see exception.

Is not using /Year at the url it works.
  

### Expected result
*The result should be grouped by year*  

### Actual result
*It throws the following exception: Can only bind segments that are Navigation, Structural, Complex, or Collections. We found a segment 'MyDate' that isn't any of those. Please revise the query.

   at Microsoft.OData.Core.UriParser.Parsers.InnerPathTokenBinder.BindInnerPathSegment(InnerPathToken segmentToken)
   at Microsoft.OData.Core.UriParser.Parsers.MetadataBinder.BindInnerPathSegment(InnerPathToken token)
   at Microsoft.OData.Core.UriParser.Parsers.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.Core.UriParser.Parsers.EndPathBinder.DetermineParentNode(EndPathToken segmentToken)
   at Microsoft.OData.Core.UriParser.Parsers.EndPathBinder.BindEndPath(EndPathToken endPathToken)
   at Microsoft.OData.Core.UriParser.Parsers.MetadataBinder.BindEndPath(EndPathToken endPathToken)
   at Microsoft.OData.Core.UriParser.Parsers.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.Core.UriParser.Aggregation.ApplyBinder.BindGroupByToken(GroupByToken token)
   at Microsoft.OData.Core.UriParser.Aggregation.ApplyBinder.BindApply(IEnumerable`1 tokens)
   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseApplyImplementation(String apply, ODataUriParserConfiguration configuration, IEdmType elementType, IEdmNavigationSource navigationSource)
   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseApply()
   at System.Web.OData.Query.ApplyQueryOption.get_ApplyClause()
*

**Comment by VikingsFan** [comment]
@rwerlang if you want to use `year` build-in function, the url should looks like `$apply=groupby((year(MyDate)))"` but now build-in function in not support in Groupby, open bug https://github.com/OData/odata.net/issues/553 to track. Close this one.
