### ISSUE TITLE
KeyAsSegment changes in ODL nightly 20160717.1 doesn't work for Url template

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#642]
For example:

```C#
IEdmModel model = GetEdmModel();
string uriTemplate = "MyOrders({orderId})/OrderLines/System.Web.OData.Builder.TestModels.SpecialOrderLine";
var uriParser = new ODataUriParser(model, new Uri(uriTemplate, UriKind.Relative))
{
     EnableUriTemplateParsing = true
};

var path = uriParser.ParsePath();

```
It will throw exception.

```
   at Microsoft.OData.UriParser.ODataUriResolver.ResolveKeys(IEdmEntityType type, IList`1 positionalValues, Func`3 convertFunc) in d:\github\odata\odata.net\src\Microsoft.OData.Core\UriParser\Resolver\ODataUriResolver.cs:line 257
   at Microsoft.OData.UriParser.SegmentArgumentParser.TryConvertValues(IEdmEntityType targetEntityType, IEnumerable`1& keyPairs, ODataUriResolver resolver) in d:\github\odata\odata.net\src\Microsoft.OData.Core\UriParser\Parsers\SegmentArgumentParser.cs:line 202
   at Microsoft.OData.UriParser.SegmentKeyHandler.CreateKeySegment(ODataPathSegment segment, KeySegment previousKeySegment, SegmentArgumentParser key, ODataUriResolver resolver) in d:\github\odata\odata.net\src\Microsoft.OData.Core\UriParser\Parsers\SegmentKeyHandler.cs:line 179
   at Microsoft.OData.UriParser.SegmentKeyHandler.TryHandleSegmentAsKey(String segmentText, ODataPathSegment previous, KeySegment previousKeySegment, ODataUrlKeyDelimiter odataUrlKeyDelimiter, ODataUriResolver resolver, KeySegment& keySegment, Boolean enableUriTemplateParsing) in d:\github\odata\odata.net\src\Microsoft.OData.Core\UriParser\Parsers\SegmentKeyHandler.cs:line 108
   at Microsoft.OData.UriParser.ODataPathParser.TryHandleAsKeySegment(String segmentText) in d:\github\odata\odata.net\src\Microsoft.OData.Core\UriParser\Parsers\ODataPathParser.cs:line 356
   at Microsoft.OData.UriParser.ODataPathParser.CreateNextSegment(String text) in d:\github\odata\odata.net\src\Microsoft.OData.Core\UriParser\Parsers\ODataPathParser.cs:line 902
   at Microsoft.OData.UriParser.ODataPathParser.ParsePath(ICollection`1 segments) in d:\github\odata\odata.net\src\Microsoft.OData.Core\UriParser\Parsers\ODataPathParser.cs:line 129
   at Microsoft.OData.UriParser.ODataPathFactory.BindPath(ICollection`1 segments, ODataUriParserConfiguration configuration) in d:\github\odata\odata.net\src\Microsoft.OData.Core\UriParser\Parsers\ODataPathFactory.cs:line 23
   at Microsoft.OData.UriParser.ODataUriParser.ParsePathImplementation() in d:\github\odata\odata.net\src\Microsoft.OData.Core\UriParser\ODataUriParser.cs:line 477
   at Microsoft.OData.UriParser.ODataUriParser.Initialize() in d:\github\odata\odata.net\src\Microsoft.OData.Core\UriParser\ODataUriParser.cs:line 496
   at Microsoft.OData.UriParser.ODataUriParser.ParsePath() in d:\github\odata\odata.net\src\Microsoft.OData.Core\UriParser\ODataUriParser.cs:line 253
   at Microsoft.OData.Tests.UriParser.Parsers.UriTemplateParserTests.ParseKeyTemplateWithTemplateParser222() in d:\github\odata\odata.net\test\FunctionalTests\Microsoft.OData.Core.Tests\UriParser\Parsers\UriTemplateParserTests.cs:line 126
```

Please investigate it. Thanks.

**Comment by biaol-odata** [comment]
Updated the repo case above to indicate the usage of keyAsSegment URI (instead of ParenthessAsSegment URI).
string uriTemplate = "MyOrders/{orderId}/OrderLines/System.Web.OData.Builder.TestModels.SpecialOrderLine"; 

Also tried C:\github\OData-master\myOdata.net\test\FunctionalTests\Microsoft.OData.Core.Tests\UriParser\Parsers\UriTemplateParserTests.cs ParseEnumKeyTemplateWithTemplateParser with "Shapes/{enumKey}/", it passes.
