### ISSUE TITLE
Update geo function request URL in OData.org blog to correct one

### ISSUE THREAD

**Issue by chinadragon0515** [OData/odata.net#648]
For request like this one,

http://localhost:18384/api/Spatial/People?$filter=geo.distance(PointLocation,%20POINT(-127.89734578345%2045.234534534))%20lt%200.5

Note point location is type of GeographyPoint

Exception will be thrown during URL parsing.

### Assemblies affected
6.15 and newer

### Reproduce steps
1. create a model with GeographyPoint type.
2. parsing a url with geo function.

refer to http://www.odata.org/blog/geospatial-properties/ for more detail about geography type and function.

### Expected result
URL is parsing correctly

### Actual result
Exception will be thrown

message: "')' or ',' expected at position 51 in 'geo.distance(PointLocation, POINT(-127.89734578345 45.234534534)) lt 0.5'.",
type: "Microsoft.OData.Core.ODataException",
stacktrace: "   at Microsoft.OData.Core.UriParser.Parsers.FunctionCallParser.ParseArgumentListOrEntityKeyList()
   at Microsoft.OData.Core.UriParser.Parsers.FunctionCallParser.ParseIdentifierAsFunction(QueryToken parent)
   at Microsoft.OData.Core.UriParser.Parsers.IdentifierTokenizer.ParseIdentifier(QueryToken parent)
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParsePrimaryStart()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParsePrimary()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseUnary()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseMultiplicative()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseAdditive()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseComparison()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseLogicalAnd()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseLogicalOr()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseExpression()
   at Microsoft.OData.Core.UriParser.Parsers.FunctionCallParser.ReadArgumentsAsPositionalValues()
   at Microsoft.OData.Core.UriParser.Parsers.FunctionCallParser.ParseArguments()
   at Microsoft.OData.Core.UriParser.Parsers.FunctionCallParser.ParseArgumentListOrEntityKeyList()
   at Microsoft.OData.Core.UriParser.Parsers.FunctionCallParser.ParseIdentifierAsFunction(QueryToken parent)
   at Microsoft.OData.Core.UriParser.Parsers.IdentifierTokenizer.ParseIdentifier(QueryToken parent)
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParsePrimaryStart()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParsePrimary()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseUnary()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseMultiplicative()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseAdditive()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseComparison()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseLogicalAnd()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseLogicalOr()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseExpression()
   at Microsoft.OData.Core.UriParser.Parsers.UriQueryExpressionParser.ParseExpressionText(String expressionText)
   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, IEdmType elementType, IEdmNavigationSource navigationSource)
   at Microsoft.OData.Core.UriParser.ODataQueryOptionParser.ParseFilter()
   at System.Web.OData.Query.FilterQueryOption.get_FilterClause()
   at System.Web.OData.Query.Validators.FilterQueryValidator.Validate(FilterQueryOption filterQueryOption, ODataValidationSettings settings)
   at System.Web.OData.Query.FilterQueryOption.Validate(ODataValidationSettings validationSettings)
   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)
   at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)
   at Microsoft.Restier.Publishers.OData.RestierController.ApplyQueryOptions(IQueryable queryable, ODataPath path, Boolean applyCount, Boolean& isIfNoneMatch, ETag& etag) in D:\dev\githome\RESTier.vin\src\Microsoft.Restier.Publishers.OData\RestierController.cs:line 601
   at Microsoft.Restier.Publishers.OData.RestierController.<Get>d__7.MoveNext() in D:\dev\githome\RESTier.vin\src\Microsoft.Restier.Publishers.OData\RestierController.cs:line 126

**Comment by chinadragon0515** [comment]
With help from Layla, the request should be like 
http://localhost:18384/api/Spatial/People?$filter=geo.distance(PointLocation,geography'SRID=0;Point(142.1 64.1)') gt 0 

The sample request in Odata blog in this link is incorrect,  http://www.odata.org/blog/geospatial-properties/

I will leave this issue open for document update only,

**Comment by Lingxi-Li** [comment]
HTML source fixed in https://github.com/OData/odataorg.github.io/commit/fa1a3c1fe98d53237567e68ca60ff8ae8727c17b

**Comment by Lingxi-Li** [comment]
Published and website updated.
