### ISSUE TITLE
[OData v6] Issue with enable query option for web api

### ISSUE THREAD

**Issue by thqnhat** [OData/odata.net#705]
Hi,

I had a web api project  (ASP.NET API V2) which used OData v6.15.0.
For more information, I used HTTP endpoints with query options supported by OData.

Here is my code sample:
1. Enable OData Query Option in WebApiConfig.cs:
config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
**System.Web.OData.Extensions.HttpConfigurationExtensions.AddODataQueryFilter(config);**

2. Query for example
[EnableQuery]
 **public IQueryable<ApplicationModel> Get()
 {
 return ModelFactory.CreateList(_applicationService.GetApplications(null, true, true, true)).AsQueryable();
 }**

This worked very well for the version OData 6.15.0.

However, when I updated my nuget packages, my APIs don't working anymore. I saw that the version of OData (Microsoft.AspNet.OData, Microsoft.OData.Core, Microsoft.OData.Edm) has been update to v7.0.0.

And I had the exception below:
**exception.StackTrace:
at** System.Web.OData.Extensions.HttpConfigurationExtensions.**GetNonODataRootContainer**(HttpConfiguration configuration)
at
System.Web.OData.Extensions.HttpRequestMessageExtensions.GetRootContainer(HttpRequestMessage request, String routeName)
at System.Web.OData.EnableQueryAttribute.GetModel(Type elementClrType, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)
at System.Web.OData.EnableQueryAttribute.ContainsAutoSelectExpandProperty(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)
at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)
at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutedAsync(HttpActionExecutedContext actionExecutedContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**TargetSite = {System.IServiceProvider GetNonODataRootContainer(System.Web.Http.HttpConfiguration)}**

**Message: No non-OData HTTP route registered.**
**Source: System.Web.OData**

I must do something?

Thanks for your help.

Nhat

**Comment by thqnhat** [comment]
I added this line: config.EnableDependencyInjection(); to WebApiConfig.cs
It worked.
