### ISSUE TITLE
OData query throws InvalidOperationException: Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by onlyann** [OData/odata.net#898]
Exception of type `InvalidOperationException: Collection was modified; enumeration operation may not execute`  occurs when running queries from a generated OData client. 

### Assemblies affected

6.17.0

### Reproduce steps

I will try to come back with a consistent way to reproduce the behaviour. However, I feel that the additional detail section should give enough information to fix it.

It happens while calling an ASP.NET application that uses `DataServiceQuery<T>.GetAllPagesAsync`. However, it doesn't happen every time.
No `DataServiceContext` instance is shared between requests.

### Additional detail

Here's a stack trace of the exception
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.OData.Client.ClientEdmModel.GetOrCreateEdmTypeInternal(IEdmStructuredType edmBaseType, Type type, PropertyInfo[] keyProperties, Boolean isEntity, Nullable`1 hasProperties)
   at Microsoft.OData.Client.ClientEdmModel.GetOrCreateEdmType(Type type)
   at Microsoft.OData.Client.ClientEdmModel.CreateEdmProperty(IEdmStructuredType declaringType, PropertyInfo propertyInfo)
   at Microsoft.OData.Client.ClientEdmModel.<>c__DisplayClass19.<GetOrCreateEdmTypeInternal>b__e(EdmEntityTypeWithDelayLoadedProperties entityType)
   at Microsoft.OData.Client.Providers.EdmEntityTypeWithDelayLoadedProperties.EnsurePropertyLoaded()
   at Microsoft.OData.Client.Providers.EdmEntityTypeWithDelayLoadedProperties.get_DeclaredProperties()
   at Microsoft.OData.Client.Metadata.ClientTypeAnnotation.<DiscoverEdmProperties>d__8.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.OData.Client.Metadata.ClientTypeAnnotation.EdmProperties()
   at Microsoft.OData.Client.Metadata.ClientTypeAnnotation.BuildPropertyCache()
   at Microsoft.OData.Client.Metadata.ClientTypeAnnotation.GetProperty(String propertyName, Boolean ignoreMissingProperties)
   at Microsoft.OData.Client.Materialization.StructuralValueMaterializationPolicy.MaterializeDataValues(ClientTypeAnnotation actualType, IEnumerable`1 values, Boolean ignoreMissingProperties)
   at Microsoft.OData.Client.Materialization.EntryValueMaterializationPolicy.MaterializeResolvedEntry(MaterializerEntry entry, Boolean includeLinks)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializerInvoker.DirectMaterializePlan(Object materializer, Object entry, Type expectedEntryType)
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at Microsoft.OData.Client.DataServiceQuery`1.<ContinuePage>d__3.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```
Judging from the exception, it points to an issue with [ClientEdmModel.EdmStructureSchemaElements](https://github.com/OData/odata.net/blob/75df8f44f2b81f984589790be4885b6ee8946ad0/src/Microsoft.OData.Client/ClientEdmModel.cs#L414) that gets modified by another thread through [TypeResolver constructor](https://github.com/OData/odata.net/blob/75df8f44f2b81f984589790be4885b6ee8946ad0/src/Microsoft.OData.Client/TypeResolver.cs#L64-L77). 

Should there be a lock to make `ClientEdmModel.EdmStructureSchemaElements` modifications thread safe ?

**Comment by robward-ms** [comment]
Released in 7.3.0, issue still open in 6.x.
