### ISSUE TITLE
Some client 2e2 test cases related to EF failed on VSTS, but pass on local

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#974]
Some client 2e2 test cases (6) related to EF failed on VSTS, but pass on local machine.

Ignore then to unblock the rolling and nightly build.

### Assemblies affected

* 7.x

### Reproduce steps

* un-ignore the test cases to run on VSTS

### Expected result

* should pass

### Actual result

* failed with the following error message:
```C#
Failed   ValidReadEFEntity
Error Message:
   Test method Microsoft.Test.OData.Tests.Client.PublicProviderTests.EFServiceTests.ValidReadEFEntity threw exception:
Microsoft.OData.Client.DataServiceQueryException: An error occurred while processing this request. ---> Microsoft.OData.Client.DataServiceClientException: {"error":{"code":"","message":"An error occurred while processing this request."}}
Stack Trace:
    at Microsoft.OData.Client.QueryResult.ExecuteQuery() in C:\BuildAgent\_work\22\s\src\Microsoft.OData.Client\QueryResult.cs:line 222
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents) in C:\BuildAgent\_work\22\s\src\Microsoft.OData.Client\DataServiceRequest.cs:line 155
 --- End of inner exception stack trace ---
    at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents) in C:\BuildAgent\_work\22\s\src\Microsoft.OData.Client\DataServiceRequest.cs:line 177
   at Microsoft.OData.Client.DataServiceQuery`1.Execute() in C:\BuildAgent\_work\22\s\src\Microsoft.OData.Client\DataServiceQueryOfT.cs:line 259
   at Microsoft.OData.Client.DataServiceQuery`1.GetEnumerator() in C:\BuildAgent\_work\22\s\src\Microsoft.OData.Client\DataServiceQueryOfT.cs:line 346
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Test.OData.Tests.Client.PublicProviderTests.EFServiceTests.ValidReadEFEntity() in C:\BuildAgent\_work\22\s\test\EndToEndTests\Tests\Client\Build.Desktop\PublicProviderTests\EFServiceTests.cs:line 31
Standard Output Messages:
```
### Additional detail

none

**Comment by xuzhg** [comment]
fixed it.

The reason is the database access deny at the build agent. After remove the old database, the test cases can pass all.
